### ISSUE TITLE
XHTML - Self Closing Tags

### ISSUE THREAD

**Issue by nfplee** [mganss/HtmlSanitizer#1]
I've just been playing around with a few different HTML sanitizer libraries. This one was looking promising until I realized it changed:

```<img src="..." />```

to:

```<img src="...">```

Which is invalid XHTML. Although technically this is allowed in HTML I don't think it looks good and usually most people prefer to use a self closing tag.

**Comment by wobu** [comment]
please have a look onto your postet CsQuery Issue.

I think it is possible, you just have to extend the Sanitize() method to allow a custom 

     CQ.Create(html)

Maybe with a Func?
