### ISSUE TITLE
.Net Fiddle Demo Boken.

### ISSUE THREAD

**Issue by nezoic** [mganss/HtmlSanitizer#100]
The .Net Fiddler demo throws:
Compilation error (line 0, col 0): Metadata file 'C:\Resources\directory\a35fcf6677bc4db79cbce852f9910cbd.DotNetFiddle.Web.LocalResources\NuGetPackages\Microsoft.Bcl.Async\1.0.168\lib\net40\Microsoft.Threading.Tasks.dll' could not be found
Compilation error (line 0, col 0): Metadata file 'C:\Resources\directory\a35fcf6677bc4db79cbce852f9910cbd.DotNetFiddle.Web.LocalResources\NuGetPackages\Microsoft.Bcl.Async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.Desktop.dll' could not be found
Compilation error (line 0, col 0): Metadata file 'C:\Resources\directory\a35fcf6677bc4db79cbce852f9910cbd.DotNetFiddle.Web.LocalResources\NuGetPackages\Microsoft.Bcl.Async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll' could not be found

**Comment by tiesont** [comment]
Just needs the NuGet package updated. Version 3.3.142 works just fine.

**Comment by 304NotModified** [comment]
Fixed in https://github.com/mganss/HtmlSanitizer/pull/101
