### ISSUE TITLE
Only sanitize denied tags/attributes - everything else is ok

### ISSUE THREAD

**Issue by lewismoten** [mganss/HtmlSanitizer#103]
I'm having trouble trying to use this library. It's stripping out text that must have < and > characters. I don't know what that text will be. 

How do I allow all tags except:
- script
- frame
- iframe
- link

And how do I allow all attributes except:
- on.*

**Comment by mganss** [comment]
HtmlSanitizer is whitelist-based, not blacklist-based. Although I'd advise against it, you can achieve your desired behavior by using the events `RemovingTag` and `RemovingAttribute`. First disallow all elements and attributes and then add your blacklisting logic to the event handlers. Something like this:

```C#
var sanitizer = new HtmlSanitizer() { AllowedTags = { }, AllowedAttributes = { } };
var badElements = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "script", "frame", "iframe", "link" };
sanitizer.RemovingTag += (s, e) => e.Cancel = !badElements.Contains(e.Tag.NodeName);
sanitizer.RemovingAttribute += (s, e) => e.Cancel = !e.Attribute.Name.StartsWith("on", StringComparison.OrdinalIgnoreCase);

var html = @"<div id=""test"" onclick=""test()""><script>test();</script><b>Test</b></div>";

var actual = sanitizer.Sanitize(html);

Assert.Equal(@"<div id=""test""><b>Test</b></div>", actual);
```

**Comment by lewismoten** [comment]
Thanks. I was able to override onRemovingTag, however the resulting html got really weird. ie - "<My Home>" becomes "<my></my>". I believe I need to find another way to sanitize while preserving original content structure that is deemed safe.

**Comment by mganss** [comment]
See the discussion in #91 and [this gist](https://gist.github.com/mganss/00bec2c2245c0ef86d9c82d6211def7b) on how to deal with this use case.

**Comment by ynrajasekhar** [comment]
test

**Comment by ynrajasekhar** [comment]
<body> <html> 
<form action="" method="GET"> User name: <input type="text" name="Name"></br> 
Password: <input type="text" name="Password"></br>
<input type="submit" name="button" value="Click Me"></br> </form> </html> </body>

**Comment by ynrajasekhar** [comment]
<p><span style="background-color: #6666ff">asdfdsafds</span></p>
<p><span style="background-color: #6666ff"><strong>asfasdf</strong></span></p>
<p><span style="background-color: #6666ff"><em>adfds</em></span>
<em></em></p><p><em>
<span style="background-color: #6666ff">&nbsp;</span>
</em></p><p><em>
<span style="text-decoration: underline; color: #6633ff">asdfsd&nbsp;</span>
<span style="text-decoration: underline; color: #003366">adsfsdf</span>
</em></p><p><em><span style="text-decoration: underline; color: #003366">&nbsp;</span>
</em></p><p style="text-align: left"><em><span style="text-decoration: underline; color: #003366">asdfsdf</span></em>
</p><p style="text-align: center"><em><span style="text-decoration: underline; color: #003366">asdfsadfsf</span></em>
</p><p style="text-align: right"><em><span style="text-decoration: underline; color: #003366">adsfasdffd</span></em></p>
<p style="text-align: right"><em><span style="text-decoration: underline; color: #003366">&nbsp;</span></em></p>
<p style="text-align: justify"><em><span style="text-decoration: underline; color: #003366">asdfsdfsdfdf</span></em>
</p><ul><li><em><span style="text-decoration: underline; color: #003366">a</span></em></li><li><em>
<span style="text-decoration: underline; color: #003366">a</span></em></li><li><em>
<span style="text-decoration: underline; color: #003366">adf</span></em></li></ul><ol><li><em>
<span style="text-decoration: underline; color: #003366">asdfsdfsdf</span></em></li><li><em>
<span style="text-decoration: underline; color: #003366">3</span></em></li><li><em>
<span style="text-decoration: underline; color: #003366">5</span></em></li></ol><p>&nbsp;</p>
<p style="margin-left: 30px">asdfsdf</p><p>asdfsdf</p><p style="margin-left: 60px">adfsadfsadf</p>
<p style="margin-left: 60px">&nbsp;</p><p style="margin-left: 60px">
<a href="http://google.com" target="_blank" title="test">adsfsdfsdf</a></p>
