### ISSUE TITLE
The src attribute of <img> is removed if it contains data:image/png

### ISSUE THREAD

**Issue by mofadevs** [mganss/HtmlSanitizer#111]
Good Day
Using Summer Note rich text editor, when an image is inserted, it is added as base64 encoded string. For example for a .png file, it ends up something like:
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA........data-filename="pin.png"> When it is sanitized, I get **img data-filename="pin1.png"** with angle brackets and rest is removed from the src attribute.
If for testing, I remove "data:image/png" from the src attribute, and then sanitize, the tag is completely preserved. But image will not be rendered, of course. 

Is it somehow possible to overcome this, since we want to allow embedded images in base64 encoding.

Thanks.

**Comment by 304NotModified** [comment]
is this the same question? https://github.com/mganss/HtmlSanitizer/issues/66

**Comment by mganss** [comment]
No feedback, closing.
