### ISSUE TITLE
Semicolon gets removed from style attribute

### ISSUE THREAD

**Issue by lbmankala** [mganss/HtmlSanitizer#112]
Semicolon gets removed from style attribute after sanitization. 
e,g. 
![semicolon_replacement](https://cloud.githubusercontent.com/assets/16317385/23705150/673f6236-042e-11e7-9717-8bf91446d7fd.png)

is there solution for this or am I missing any configuration?

**Comment by mganss** [comment]
This occurs because the style is parsed and then rendered back out. There is currently no way to influence this behavior.

**Comment by Dantiberg** [comment]
I think it might be a good idea to make it a feature, so you can choose whether or not you want the final semicolon.

**Comment by tiesont** [comment]
@Dantiberg That is a suggestion for the [AngleSharp](https://github.com/AngleSharp/AngleSharp) folks, methinks.

**Comment by mganss** [comment]
This might become possible with AngleSharp.Css,  i.e. AngleSharp 0.10.

**Comment by liesahead** [comment]
Any updates for this, is this possible to avoid?

**Comment by mganss** [comment]
This is possible from 7.1.475 through a custom style formatter. See a code example here: https://github.com/mganss/HtmlSanitizer/blob/ea681df15ba8690bccb55743dee2f8ea16f1552d/test/HtmlSanitizer.Tests/Tests.cs#L3286-L3332

**Comment by liesahead** [comment]
@mganss , great news, thanks!

**Comment by AndriusPukenas** [comment]
Does not work for:
<style>table, th, td { border-collapse: collapse; border: none; }</style>
it returns:
<style>table, th, td { border-collapse: collapse; border: none }</style>

**Comment by mganss** [comment]
@AndriusPukenas Have you used a custom style formatter like in the example above? It doesn't work with the default style formatter, i.e. default behavior has stayed the same.

**Comment by AndriusPukenas** [comment]
@mganss , yes, just changed into:
        [Fact]
        public void StyleFormatterTest()
        {
            // see https://github.com/mganss/HtmlSanitizer/issues/112
            var html = @"<style>table, th, td { border-collapse: collapse; border: none; }</style>";
            var sanitizer = new HtmlSanitizer();
            var styleFormatter = new SemicolonStyleFormatter();

            sanitizer.StyleFormatter = styleFormatter;
            sanitizer.AllowedTags.Add("style");

            var sanitized = sanitizer.Sanitize(html);

            Assert.Equal(html, sanitized);
        }
actually my situation is a little bit different, since I am not using inline css, but global

**Comment by mganss** [comment]
@AndriusPukenas The style formatter in the example works just for the unit test case. For more general cases, you need to flesh out more of the `IStyleFormatter` methods, possibly just by copying over from `CssStyleFormatter`. For your case above, you need to add the `Sheet()` method:

```c#
public string Sheet(IEnumerable<IStyleFormattable> rules)
{
    var sb = new StringBuilder();
    var sep = Environment.NewLine;

    using (var writer = new StringWriter(sb))
    {
        foreach (var rule in rules)
        {
            rule.ToCss(writer, this);
            writer.Write(sep);
        }

        if (sb.Length > 0)
        {
            sb.Remove(sb.Length - sep.Length, sep.Length);
        }
    }

    return sb.ToString();
}
```
