### ISSUE TITLE
StackOverflowException when parsing many invalid HTML Tags

### ISSUE THREAD

**Issue by aschiffmann** [mganss/HtmlSanitizer#113]
When sanitizing html which contains a lot (~21.000) invalid html tags, a StackOverflow exception is thrown.

[This is the HTML](http://pastebin.com/g4nsaUYh) which produces the stackoverflow.
Also the [online demo](http://xss.ganss.org/) crashes when trying to parse the given html.

The [debugger shows](https://ibin.co/3ExBplOz9Knt.png) that the excaption is actually thrown by the AngleSharp lib, so I also created an [issue](https://github.com/AngleSharp/AngleSharp/issues/543) in the angleSharp repository.

However I noticed, that this exception only happens when running the code within an IIS AppPool. When running it within an unitTest instead, the sanitizing runs without any problems in less than one second.

Can you provide any workaround, so this won't happen when parsing large html within an IIS appPool?

**Comment by mganss** [comment]
This is an issue in AngleSharp. Please see the discussion at AngleSharp/AngleSharp#543. I currently see no way to work around this.

**Comment by TheDarkCode** [comment]
This issue with AngleSharp was resolved, see the [relevant PR](https://github.com/AngleSharp/AngleSharp/pull/544).

**Comment by vivekscripts** [comment]
https://github.com/vivekscripts/AngleSharp - I fixed this on the current version, you might want to try.

**Comment by mganss** [comment]
I can't get it to build out of the box using `build.ps1`.

**Comment by mganss** [comment]
Fix was released in [AngleSharp 0.9.9.1](https://github.com/AngleSharp/AngleSharp/releases/tag/v0.9.9.1)
