### ISSUE TITLE
Encoded <script> still rendered in html

### ISSUE THREAD

**Issue by robertpmansion** [mganss/HtmlSanitizer#114]
I tried this following string:

`&lt;test&gt; me <script>alert('test');</script> &lt;script&gt;alert('test');&lt;/script&gt;`

and the result still rendered the encoded <script> which should.

![image](https://cloud.githubusercontent.com/assets/18090549/23764286/f587b71e-0537-11e7-9fb4-bb69ab1901fb.png)

**Comment by mganss** [comment]
This is expected behavior. See the discussion at #61.
