### ISSUE TITLE
Should "RemovingAtRuleEventArgs" and "RemovingCommentEventArgs" contain a Reason property?

### ISSUE THREAD

**Issue by tiesont** [mganss/HtmlSanitizer#115]
In going through and trying to flesh out some documentation for HtmlSanitizer, I noticed that there is a slight inconsistency between the event arguments in the most recently added Removing.. events and the "original" events.

To be brief, the majority of the Removing...EventArgs classes have a Reason property (of type RemoveReason), but "RemovingAtRuleEventArgs" and "RemovingCommentEventArgs" do not. Is this intentional?

**Comment by mganss** [comment]
I'd say yes. If these had a Reason property, it would always be set to a single value anyway. The Reason property on RemovingTagEventArgs is redundant, too.

**Comment by tiesont** [comment]
Okay, just to confirm: the two event args I'm referring to should **NOT** have a Reason property? I'm only asking because I'm working on [wiki content for the "hooks"/events](https://github.com/tiesont/HtmlSanitizer/wiki/Hooks) and I want to make sure I'm not making assumptions.

**Comment by mganss** [comment]
Yes, IMO these events should *not* have a Reason property.

Thanks for your work on the wiki 👍 Looking forward to the PR.
