### ISSUE TITLE
Feature Request: optionally disable encoding of angle brackets and ampersand

### ISSUE THREAD

**Issue by Matthewsre** [mganss/HtmlSanitizer#116]
I would like to strip out all tags identified, but prevent the encoding of the remaining angle brackets and ampersands. In not all scenarios will the end output be html so I would like to prevent encoding the remaining values. Would this be easy to add as a feature or something I was missing when poking around at the available methods/properties?

**Comment by tiesont** [comment]
You could implement a custom `IMarkupFormatter` ([here's the default implementation](https://github.com/mganss/HtmlSanitizer/blob/master/src/HtmlSanitizer/HtmlFormatter.cs)) which you would then pass into the `Sanitize` method, but you might also find it easier to simply run the sanitized output through [WebUtility.HtmlDecode](https://msdn.microsoft.com/en-us/library/ee388354.aspx).

**Comment by mganss** [comment]
I second what @tiesont has said, but I'm curious what you had in mind with "In not all scenarios will the end output be html"?

**Comment by Matthewsre** [comment]
We have an API where we are sanitizing values as they come into our service. The end applications that view these results are not all websites, some are websites and others are desktop and mobile applications. For the non-html rendering applications we would not want the values html encoded, but we would like to sanitize the input to remove ALL tags. 

`var htmlSanitizer = new HtmlSanitizer(new string[] {});`

Maybe using this library is overkill for this, but there are other use cases in our application and we already have a dependency on it. In some scenarios we would like to allow html and sanitize it, but other scenarios we want to prevent html all together. I will look into leveraging the IMarkupFormatter interface to resolve this for my scenario.

**Comment by mganss** [comment]
I think it might be best for this use case to use AngleSharp to render the text as a second step after sanitization:

```C#
var html = "<div><script>test();</script><p>Test &amp; <b>run</b></p></div>";
var sanitizer = new HtmlSanitizer();
var sanitizedHtml = sanitizer.Sanitize(html);
var parser = new HtmlParser();
var dom = parser.Parse(sanitizedHtml);
var text = dom.Body.TextContent; // -> "Test & run"
```

**Comment by tiesont** [comment]
@mganss I've run into at least one scenario where it would be useful to leave an angle-bracket as an unencoded angle-bracket - I'm using a sanitizer with all tags removed as a way of only allowing Markdown/CommonMark text in a editor I'm building, and it's encoding the `>` you would use for a blockquote. Your suggestion fixes that, though, as would a string.Replace or WebUtility.HtmlDecode.

**Comment by mganss** [comment]
@tiesont Have you considered hooking into your Markdown processor's extensibility points to disable output of raw HTML in Markdown?

**Comment by tiesont** [comment]
@mganss Well, I want to sanitize the input string anyway, so it's low-hanging fruit to just use HtmlSanitizer to strip out any HTML that gets entered. Using the HtmlParser on the sanitized output gets me the result I'm looking for, so... I'm not sure of the point I was trying to make, other than there _are_ limited scenarios where it makes sense to not encode things like angle-brackets. Not sure how you would allow those and not wind up with things like `&` not being encoded as `&amp;`.

**Comment by mganss** [comment]
@tiesont I still don't believe it's a good idea to use HtmlSanitizer on anything other than HTML. Are you sure the HTML parser doesn't mess up your Markdown in some cases (I'm thinking significant whitespace for example)?

**Comment by tiesont** [comment]
@mganss Yes and no. Does it screw up Markdown/CommonMark syntax? Not that I've noticed, but I haven't done a thorough test suite yet. Does it mangle, say, a blob of HTML that a user submitted through my editor? Yes, to a degree, but I'm not unhappy with that. This is for a (mostly) internal project, for a handful of users, and if they don't like the output, we can discuss _why_ it works that way.

Not that I'm saying this is justification, but I'm basically following the line of thought from https://talk.commonmark.org/t/cross-site-scripting-issue-in-standard-markdown-example-at-try-standardmarkdown-com/55

**Comment by mganss** [comment]
Closing
