### ISSUE TITLE
Sanitizer not behaving properly for svg tags

### ISSUE THREAD

**Issue by rajeshchada** [mganss/HtmlSanitizer#119]
Below is the code:
```
HtmlSanitizer sanitizer = new HtmlSanitizer();
sanitizer.AllowedTags.Add("svg");
Console.WriteLine("Output");
Console.WriteLine(sanitizer.Sanitize(args[0]));
```

Input provided:
`<svg onchange='alert(1)'>123</svg>`

Expected outcome:
`<svg>123</svg>`

Actual outcome:
`<svg onchange="alert(1)">123</svg>`

Issue:
onchange event or attribute should be stripped off, as it happens for similar input for anchor tags.

**Comment by mganss** [comment]
Thanks for reporting this! I've released 3.5169 with a fix.
