### ISSUE TITLE
docs claim href attribute is allowed by default. It is sanitized

### ISSUE THREAD

**Issue by microsoftly** [mganss/HtmlSanitizer#124]

**Comment by tiesont** [comment]
I'm not sure what you're claiming is broken/incorrect. The href attribute is allowed on the tags _for which it is valid_. Assuming the href attribute is valid for the tag, the value of the href attribute will be sanitized. Are you expecting otherwise?

**Comment by mganss** [comment]
Trying to clarify what @tiesont has said: HtmlSanitizer doesn't have a mapping of elements to attributes, i.e. from HtmlSanitizer's viewpoint there are no good elements where href is allowed or bad ones where it is not. If the href attribute is in the set of allowed attributes (which it is by default) then it won't be stripped. For example, this is ok (just tested in the [online demo](http://xss.ganss.org/)):

```HTML
<h1 href="xyz">test</h1>
```

**Comment by mganss** [comment]
Closing
