### ISSUE TITLE
Email addresses in HTML content are removed when sanitizing text coming from a plaintext email

### ISSUE THREAD

**Issue by istrasoft** [mganss/HtmlSanitizer#126]
When the string to sanitize comes from a plaintext email, such items are present in the original content :

```
blah blah

From: Mark <mailto:mark@mail.com>
Sent: Wednesday, August 16, 2017 19:47
To: John <john@mail.com>
Subject: Re: Document Test

Hello John
```

If the email was a HTML email, the < and > around "`<john@mail.com>`" are aleady escaped as &lt; and &gt; but if the email was plaintext, they are not.

In this specific case, the part `<john@mail.com>` is considered to be an invalid HTML tag and is removed, along with all the following content from that point.

If option "Keep child nodes of removed elements" is chosen, then only these email tags are lost.

It would be great if after testing a tag against the whitelist, an additional test was made to attempt to match it to these two authorized and standard and safe instances.

**Comment by mganss** [comment]
This is the same problem as #91. See there for a workaround.

**Comment by istrasoft** [comment]
Thanks @mganss !

**Comment by mganss** [comment]
I'd like HtmlSanitizer to ["do one thing well"](https://en.wikipedia.org/wiki/Unix_philosophy) and that's sanitize HTML, so adding this would be outside of this scope. If you have something that's not HTML, you'll need to do preprocessing.

**Comment by istrasoft** [comment]
Indeed, makes sense.. Maybe your gist could be included in the distribution and accessed through an additional call or option/flag.

**Comment by mganss** [comment]
I have added it to the [Examples](/mganss/HtmlSanitizer/wiki/Examples) wiki page.

**Comment by istrasoft** [comment]
Thanks a lot @mganss !

**Comment by sunitana** [comment]
Hi, Just FYI want to update how I am handling this issue.

Created a method which identifies if the tag to be removed is in email format.
`sanitizer.RemovingTag += (sender, evt) =>
                {
                    if (IsValidMailAddress(evt.Tag)) //tag won't be removed if it is n email format
                    {
                        isValid = true;
                        evt.Cancel = true;
                    }
                else if (!invalidTags.ContainsKey(evt.Tag.TagName))
                    {
                        //invalidTags.Add(evt.Tag.TagName, evt.Reason.ToString());
                        isValid = false;
                    }
                };`

`public static bool IsValidMailAddress(AngleSharp.Dom.IElement emailAddress)
        {
            try
            {
                if (emailAddress.NodeName.ToLower().StartsWith("mailto:"))
                {
                    System.Net.Mail.MailAddress mTo = new System.Net.Mail.MailAddress(emailAddress.NodeName.Substring("mailto:".Length, emailAddress.NodeName.Length - "mailto:".Length));
                }
                else
                {
                    System.Net.Mail.MailAddress m = new System.Net.Mail.MailAddress(emailAddress.NodeName);
                }
                return true;
            }
            catch (Exception Ex)
            {
                return false;
            }
        }`
