### ISSUE TITLE
Question: why are "id" and "class" commented out in DefaultAllowedAttributes ?

### ISSUE THREAD

**Issue by istrasoft** [mganss/HtmlSanitizer#127]
Tried to find the commit where it happened, but it contains the whole new file, so no clues ...

Would you have more details or maybe an explanation of why "id" and "class" are commented out and excluded from DefaultAllowedAttributes ?

Thanks a lot !

**Comment by mganss** [comment]
I believe it wasn't ever included. It's to prevent [classjacking](https://html5sec.org/#123) and interference with existing classes and IDs.

**Comment by istrasoft** [comment]
Thanks!
