### ISSUE TITLE
Unclosed Tag gets reopened after closing it first time.

### ISSUE THREAD

**Issue by VijayBhatter** [mganss/HtmlSanitizer#130]
When trying to sanitize the following html code an extra B tag is opened.

**Input:**

`<a href="http://www.india.com"><a href="test.asp"><b>kk
Hello</a>
kk
`

**Output:**

`<a href="http://www.india.com"></a><a href="test.asp"><b>kk
Hello</b></a><b>
kk
</b>`

**Comment by mganss** [comment]
That's expected behavior. Try this in a browser:

```js
var e = document.createElement("div");
e.innerHTML = '<a href="http://www.india.com"><a href="test.asp"><b>kk Hello</a> kk';
e.innerHTML // -> "<a href="http://www.india.com"></a><a href="test.asp"><b>kk Hello</b></a><b> kk</b>"
```
