### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by huww98** [mganss/HtmlSanitizer#131]
I'm experiencing an memory leakage in my project. This package can eat over 500MB of memory in a few hours. Now I have to restart my service periodically.

I can use a very simple piece of code to reproduce it.

````C#
var html = "<p>1234</p>";

for (int i = 0; i < 100000; i++)
{
    var sanitizer = new HtmlSanitizer();
    sanitizer.Sanitize(html);
}
````

![2018-01-01_015235](https://user-images.githubusercontent.com/15710934/34463447-2c26fe4e-ee97-11e7-9854-f85f90c2fb96.png)

As you can see, the memory usage is growing unexpectedly. However, the size of the managed heap is only 1MB. So, I think there is some native code that is causing this leakage. But I have no idea how this happens. Is there any native code invoked by this package?

**Comment by huww98** [comment]
I can only reproduce this in a .net core console application, both in Windows and Ubuntu, but not in a .net framework console application, that's pretty strange. Maybe this is an issue in CoreCLR?

**Comment by huww98** [comment]
Ok, this is not an issue with this package. I just need to call `GC.Collect()` 2-5 times to get the memory usage back to normal. The GC is pretty lazy...

````C#
var html = "<p>1234</p>";

var sanitizer = new HtmlSanitizer();
for (int i = 0; i < 100000; i++)
{
    sanitizer.Sanitize(html);
}

for (int i = 0; i < 5; i++)
{
    GC.Collect();
    Thread.Sleep(2000);
}
````

![2018-01-01_031859](https://user-images.githubusercontent.com/15710934/34463802-89fc1922-eea2-11e7-80bc-e2d6086c0c5c.png)

**Comment by tiesont** [comment]
It probably also helped that you were not creating a new HtmlSanitizer instance in each loop, in your second example. It's also possible that AngleSharp (the DOM parser used internally) is still having some memory leak issues (supposed to have been fixed, see https://github.com/AngleSharp/AngleSharp/issues/45), but I would assume someone else would have reported this before now. 

@mganss is there any benefit to adding an IDisposable implementation to HtmlSanitizer?

**Comment by huww98** [comment]
@tiesont As you can see in my second example, I'm using only one `HtmlSanitizer` instance, the memory usage is still growing steadily. So, I think implementing `IDisposable` will not help in this case.

However, I have another problem now. In my real project, I'm using server GC. Server GC runs my code at twice the speed. However, it requires much more memory, and it is not willing to give the memory back to OS after the work is done, even after I call `GC.Collect()` 1000 times.

````C#
Console.WriteLine(GCSettings.IsServerGC); // True

var html = "<p>1234</p>";

var sanitizer = new HtmlSanitizer();
for (int i = 0; i < 100000; i++)
{
    sanitizer.Sanitize(html);
}

for (int i = 0; i < 1000; i++)
{
    GC.Collect();
    Thread.Sleep(2);
}
````

![2018-01-01_133725](https://user-images.githubusercontent.com/15710934/34465773-0ef07f8c-eef9-11e7-81c7-641a4fc896b8.png)

It seems that if I force GC to collect every 1000 iterations, the memory usage becomes controllable, and the performance remains good (even a little better?).

```C#
for (int i = 0; i < 100000; i++)
{
    sanitizer.Sanitize(html);
    if (i%1000 == 0)
    {
        GC.Collect();
    }
}
```

![image](https://user-images.githubusercontent.com/15710934/34465808-9218d8f4-eefa-11e7-92f7-a066e1ef44ea.png)

**Comment by huww98** [comment]
I ended up limit the memory usage using cgroup (my real project runs on an Ubuntu server). This works very well.

**Comment by mganss** [comment]
@tiesont I'll wrap the usage of `IHtmlDocument` in a `using()`. Other than that I see no reason for `IDisposable` since we are not using unmanaged resources. Or is there something I am missing?

**Comment by tiesont** [comment]
@mganss No, that was just a quick thought when seeing that the objects in the examples above may not be getting GC'd for a while. I've always understood `GC.Collect()` to be more of a polite suggestion than an explicit call, though, so even being able to explicitly dispose an HtmlSanitizer probably doesn't gain anything.

**Comment by mganss** [comment]
@tiesont You're probably right. In my experience, trying to force the GC to do things is not a good idea 😄
