### ISSUE TITLE
CSS Styles getting removed

### ISSUE THREAD

**Issue by vivekscripts** [mganss/HtmlSanitizer#132]
Input :
```html
<table style="border-collapse: collapse; width: 100%"><tbody><tr><td align="left"><table align="left" style="display: inline-block; overflow: hidden; text-align: center; vertical-align: middle; height: 100px">
```
Output : 
```html
<table><tbody><tr><td align="left"><table align="left"></table></td></tr></tbody></table>
```
Why HTML Sanitizer is removing these styles?

**Comment by vivekscripts** [comment]
Here is the encoded version - 
Input:

&lt;table style=\&quot;border-collapse: collapse; width: 100%\&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=\&quot;left\&quot;&gt;&lt;table align=\&quot;left\&quot; style=\&quot;display: inline-block; overflow: hidden; text-align: center; vertical-align: middle; height: 100px\&quot;&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;

Output:
&lt;table style=\"border-collapse: collapse; width: 100%\"&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td align=\"left\"&gt;&lt;table align=\"left\" style=\"display: inline-block; overflow: hidden; text-align: center; vertical-align: middle; height: 100px\"&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;


However, I just tried that if my HTML is encoded , it retains the styles however if you decode the input HTML above using https://www.web2generators.com/html-based-tools/online-html-entities-encoder-and-decoder
then you will see the output from the sanitizer strips the Css styles.

**Comment by vivekscripts** [comment]
When I inspect in SanitizeStyle Method I see inner HTML for table element as follows - Notice how styles are messed up and values are being treated as a style attribute itself.  Could you please help understand that?

<table align="\&quot;left\&quot;" style="\&quot;display:" inline-block;="" overflow:="" hidden;="" text-align:="" center;="" vertical-align:="" middle;="" height:="" 100px\"="">

**Comment by tiesont** [comment]
Going to be hard to answer without some sample code. Can you fork this fiddle, https://dotnetfiddle.net/qqpiDh, to demonstrate what you're seeing / how you're using HtmlSanitizer?

At a minimum, I would guess that if the encoded version is what you're passing verbatim, it's not being parsed as you are expecting.

**Comment by vivekscripts** [comment]
Input: 

"<span style="\&quot;font-size:" 16px\"="">Account:</span> <b style="\&quot;font-size:" 14px\"="">Test</b>"

Output: 
<span>Account:</span> <b>Test</b>

Just a console application with latest DLL's does produce this output. I am expecting to retain the styles but it removes them.

**Comment by tiesont** [comment]
If your content contains the literal value you've shown, that's going to be invalid and therefore be removed. Is there a reason you have quote entities inside the existing quotes?

**Comment by vivekscripts** [comment]
Ok. I figured out the issue. It's the allowedCss setting that is messing it up. Add any other css attribute such as "word-wrap" along with the default allowed css attributes (copied from the documentation page) and create sanitizer object with these settings. you will see the CSS styles will get removed.

**Comment by vivekscripts** [comment]
[TestSanitizer.zip](https://github.com/mganss/HtmlSanitizer/files/1684278/TestSanitizer.zip)

**Comment by tiesont** [comment]
Given your code (try to delete the `\bin` and `\obj` before zipping, if you don't mind), I get this same result with or without overriding the allowedCssProperties setting:

```markup
<table style="border-collapse: collapse; width: 100%"><tbody><tr><td align="left"><table border="1"><tbody><tr><th style="padding: 0 3px" align="left">Buckets with failures</th><td style="padding: 0 3px; max-width: 650px">3,4,5,6,7,8,9,10,11,14,15</td></tr><tr><th align="left">Bucket evaluations</th><td style="padding: 0 3px; max-width: 650px">9993.18011321012,9990.89189378547,9986.00517808411,9979.67194728726,9985.71224460637,9986.8073878628,9971.85225868461,9952.84000277412,9977.02749738949,9974.89014438167,9988.88811723036,9990.85794655415,9993.0924915383,9978.94145725116,9982.51625987831</td></tr><tr><th style="padding: 0 3px" align="left">Monitor.MetricData</th><td style="padding: 0 3px; max-width: 650px">Only upto last 60 minutes [TemplateData] [Reliability] [99.9318011321012,99.9089189378547,99.8600517808411,99.7967194728726,99.8571224460637,99.868073878628,99.7185225868461,99.5284000277412,99.7702749738949,99.7489014438167,99.8888811723036,99.9085794655415,99.930924915383,99.7894145725116,99.8251625987831] [MicrosoftAccountUX,IncomingQos,Reliability,DataCenter=westcentralus]</td></tr></tbody></table></td></tr></tbody></table>
```

Near as I can tell, that's exactly the expected outcome. What am I missing?

**Comment by vivekscripts** [comment]
the reason for that is -> HtmlSanitizer sanitizer = new HtmlSanitizer(allowedtags, allowedSchemes, null, null, allowedCss);

Whats the diffrence between CSS properties and CSS class? This is the most hilarious miss I ever did :-)

**Comment by vivekscripts** [comment]
by the way the version I am using (not in sample) does not have cssClass , below is the constructor -  and this one fails still.

public HtmlSanitizer(IEnumerable<string> allowedTags = null, IEnumerable<string> allowedSchemes = null, IEnumerable<string> allowedAttributes = null, IEnumerable<string> uriAttributes = null, IEnumerable<string> allowedCssProperties = null)
    {
      this.AllowedTags = (ISet<string>) new HashSet<string>(allowedTags ?? (IEnumerable<string>) HtmlSanitizer.DefaultAllowedTags, (IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);
      this.AllowedSchemes = (ISet<string>) new HashSet<string>(allowedSchemes ?? (IEnumerable<string>) HtmlSanitizer.DefaultAllowedSchemes, (IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);
      this.AllowedAttributes = (ISet<string>) new HashSet<string>(allowedAttributes ?? (IEnumerable<string>) HtmlSanitizer.DefaultAllowedAttributes, (IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);
      this.UriAttributes = (ISet<string>) new HashSet<string>(uriAttributes ?? (IEnumerable<string>) HtmlSanitizer.DefaultUriAttributes, (IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);
      this.AllowedCssProperties = (ISet<string>) new HashSet<string>(allowedCssProperties ?? (IEnumerable<string>) HtmlSanitizer.DefaultAllowedCssProperties, (IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);
      this.AllowedAtRules = (ISet<CssRuleType>) new HashSet<CssRuleType>((IEnumerable<CssRuleType>) HtmlSanitizer.DefaultAllowedAtRules);
    }

**Comment by mganss** [comment]
The problem in your code is that the individual items in the `allowedCssProperties` contain leading whitespace. You need to trim the items after splitting:

```C#
var allowedCss = Csssetting.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
    .Select(c => c.Trim());
```

The difference between CSS properties and CSS classes is this: CSS properties are values of the style attribute in HTML, e.g. `border-collapse`, while CSS classes are values of the class attribute in HTML, e.g. `container` in `<div class="container">...</div>`.

@vivekscripts When including demo code in an issue, please use [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)

**Comment by vivekscripts** [comment]
Oh My...thank you so much for looking into it @mganss AND @tiesont , I tested out without leading whitespaces and it works like a charm.

**Comment by mganss** [comment]
🆗 Closing this then.
