### ISSUE TITLE
Self closing tag normalization

### ISSUE THREAD

**Issue by Narrenschyff** [mganss/HtmlSanitizer#133]
I am passing an html containing `<u></u>`, which when passed to the sanitizer spits out `<u />`. This in turn does not get rendered properly on the browser. It is rendering an underline to every text after that tag. Upon observing the html, the structure appears to be broken as well. I understand this is related to AngleSharp parsing the html, could you please confirm there is no additional processing on your side that could be causing this tag transformation? How could this be avoided?

Thanks,
Yulia

**Comment by mganss** [comment]
I can't repro using the latest version. Which version are you using and what does your code look like?

**Comment by Narrenschyff** [comment]
@mganss I have made a reproducer https://dotnetfiddle.net/aaJolo

**Comment by mganss** [comment]
The reason the self-closed `u` is output is the use of `OutputFormatter = AngleSharp.XHtml.XhtmlMarkupFormatter.Instance`. Is there a specific reason you are using this?

**Comment by Narrenschyff** [comment]
You are right, thanks for the help!. We want to be able to construct xml containing this content as well, but in the same time we want it to be browser renderable as well. May be it's worth raising an issue with AngleSharp.

**Comment by mganss** [comment]
This doesn't seem like an issue to me. `<u />` is well-formed XHTML, isn't it?

**Comment by Narrenschyff** [comment]
It is indeed. I guess the issue is in our side then. Thanks @mganss for working with me on this one!
