### ISSUE TITLE
Return a result object rather than a raw string

### ISSUE THREAD

**Issue by anaximander23** [mganss/HtmlSanitizer#134]
Would it be possible for `Sanitise()` (or an adjacent method) to return an object containing the output along with a collection of all the things that were removed? We're using HtmlSanitizer to clean up user-entered HTML, and this would make it much easier to give the user a list of exactly what was wrong with the text they entered. We can use the existing event handlers to throw exceptions on things we don't like, but this only tells the user about the first problem, which isn't a great user experience if there were several problems with the document.

**Comment by mganss** [comment]
No, but you can collect all items that were removed by using the existing event handlers like so:
```C#
var sanitizer = new HtmlSanitizer();
var removedTags = new List<string>();
sanitizer.RemovingTag += (s, e) => removedTags.Add(e.Tag.TagName);
```

**Comment by anaximander23** [comment]
Yeah, that's effectively what I'm doing, but it feels a bit like a hack, and it takes a lot of setup, not least because if you reuse the same HtmlSanitizer you'd have to reset the removed tags list or re-do all the event handlers in between every call to `Sanitize()`.

**Comment by mganss** [comment]
I don't think that's a hack at all. You can wrap the call to `Sanitize()` in its own function/class/etc. to avoid duplicating the setup code.
