### ISSUE TITLE
Sanitize throws when encountering square brackets ([])

### ISSUE THREAD

**Issue by pazb** [mganss/HtmlSanitizer#137]
Since square brackets are a major part in Angular 2+ binding, we should have a way of marking them as valid (instead of throwing) attribute name

**Comment by mganss** [comment]
Do you have an example?

**Comment by pazb** [comment]
Sure.
I have this html snippet:
```
<div class="cs-viewer-page">
    <div class="cs-viewer-page-content">
      <div class="cs-viewer-page-content-left">
        <count-down [minutes]="2"></count-down>
        <div class="cs-viewer-page-main-title">
        {{Name}}
        </div>
        <div class="cs-viewer-page-description">
        {{Description}}
        </div>
      </div>
      <div class="cs-viewer-page-content-right">
      </div>
    </div>
  </div>
```

Which throws "Invalid character detected" because of the 

> [Minutes]

Attribute. In angular 2+ this simply means one way binding.

**Comment by pazb** [comment]
You are right. Javascript's "setAttribute" also throws when trying to add "[minutes]" attribute (I actually just learned that).
Therefor in Angular 2+ you need to use [Renderer2](https://angular.io/api/core/Renderer2) in order set attribute.
It seems strange to me, that this is a valid html, Angular is taking advantage of it, and still the native "setAttribute" (and the corresponded "SetAttribute" in AngelSharp) does not allow it... 
do you think there it will be possible to ignore this when calling Sanitize? if you want I can try to create a PR  (though I cannot commit for a timeline :) )

Thanks for your thorough answer!

**Comment by pazb** [comment]
You are right. Javascript's "setAttribute" also throws when trying to add "[minutes]" attribute (I actually just learned that).
Therefor in Angular 2+ you need to use [Renderer2](https://angular.io/api/core/Renderer2) in order set attribute.
I find it a bit strange that a valid html, with property notation being used by Angular 2+, cannot be supported by Javascript's setAttribute (or the corresponding AngleSharp SetAttribute)... 
Do you think Sanitize can be modified to support that? (I can try and create a PR, though I cannot commit to an exact time  :) )

Thanks for your thorough answer!

**Comment by mganss** [comment]
I find it strange, too. The [HTML5 validator](https://html5.validator.nu/) says:
```
Warning: Attribute [minutes] is not serializable as XML 1.0.
```
If you could provide a PR that would be great.
