### ISSUE TITLE
Consider replacing AngleSharp (e.g. with HAP)

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#140]
I'am a bit sad that I have to open this issue (see also #34)

AngleSharp was promising, but:

- It's still not stable
- Too many breaking changes IMO,
- Too many issues related to AngleSharp: https://github.com/mganss/HtmlSanitizer/issues?utf8=%E2%9C%93&q=is%3Aissue+AngleSharp+in%3Atitle+
- the development of AngleSharp stalled. Even critical fixes took ages.

So, I propose to:

- replace AngleSharp with e.g. Html Agility Pack - http://html-agility-pack.net/

     - please note they don't follow semver: https://github.com/zzzprojects/html-agility-pack/issues/74
- and/or make the current implementation Parser independent (so we could inject parsers like HAP or AngleSharp)

Just let me know what you think.

**Comment by mganss** [comment]
I agree, although currently there doesn't seem to be a better choice. HAP doesn't seem to have CSS support and is lacking in other areas as well, see https://github.com/AngleSharp/AngleSharp/wiki/Performance

FWIW: [sanitize.rb](https://github.com/rgrove/sanitize) uses [Nokogumbo](https://github.com/rubys/nokogumbo) which in turn is based on [Google's Gumbo HTML5 parser](https://github.com/google/gumbo-parser) in C and [crass](https://github.com/rgrove/crass) for CSS (pure Ruby).

**Comment by JiriZidek** [comment]
If possible, consider at least upgrade to AngleSharp 0.9.10 https://github.com/AngleSharp/AngleSharp/releases/tag/v0.9.10.0

**Comment by ChrisMaunder** [comment]
There's a certain irony in discussions on a feeling that AngleSharp isn't being updated while HtmlSanitiser is now 2 years behind the latest AngleSharp. My suggestion is that if motivation or timing is scarce to continue supporting HtmlSanitiser then please remove the binding to a specific version of AngleSharp. Doing so would allow those of us who use both HtmlSanitiser and AngleSharp together to upgrade AngleSharp without having to work around the fixed binding to an older version.

**Comment by glen-84** [comment]
@mganss Should this be closed now?
