### ISSUE TITLE
Cannot strip protocol relative URIs using allowed schemes.

### ISSUE THREAD

**Issue by richcocks** [mganss/HtmlSanitizer#143]
This may be an unusual request, but I would like to include img elements only when the src attribute is a data: URI.

I tried the following code:

```
var s = new HtmlSanitizer();
s.AllowedSchemes.Remove("http");
s.AllowedSchemes.Remove("https");
s.AllowedSchemes.Add("data");
```

This removes any URIs which try to use http or https, however someone can get around this rule with:

`@"<p><img src=""//example.com/example.png""></img></p>";`

Which has no protocol specified, but of course in practice will typically be evaluated as https.

Even by removing all entries from AllowedSchemes, the relative-protocol is allowed through.

Is there a way I can specify a custom scheme or protocol filter to not allow the protocol-relative URL or will I have to handle this in the application accepting the output of this sanitizer?

**Comment by mganss** [comment]
You can use the `RemovingAttribute` event:

```C#
s.AllowedAttributes.Remove("src");
s.RemovingAttribute += (_, e) => e.Cancel = e.Tag.TagName == "IMG" && e.Attribute.Name == "src" && e.Attribute.Value.StartsWith("data:");
```

**Comment by richcocks** [comment]
Thank you, hooking into the event like this is exactly what I'm after and this solves my issue.
