### ISSUE TITLE
evil javascript string in href of anchor element and summernote

### ISSUE THREAD

**Issue by lolcat9000** [mganss/HtmlSanitizer#144]
hi.

i think just found the following issue in combination with a link and summernote (visit https://summernote.org/ if you don't know what summernote is).

the href in question is:
`http://testsite.test/<script>alert("TEST");</script>`

when you pass that href into summernote by clicking "link" in the toolbar, summernote creates the following html-element:
`<a href="http://testsite.test/&lt;script&gt;alert(&quot;TEST&quot;);&lt;/script&gt;" target="_blank">evil link</a>
`
after POSTing summernote's content to the server it seems like that link doesn't get sanitized by the `Ganss.XSS.HtmlSanitizer.Sanitize`-method.

thanks for HtmlSanitizer btw. it's a great tool! love it! 😺

**Comment by mganss** [comment]
Thanks for the kudos. The angle brackets in the link are already escaped, so there's nothing to do for the sanitizer. Here's the link pasted verbatim into this comment: <a href="http://testsite.test/&lt;script&gt;alert(&quot;TEST&quot;);&lt;/script&gt;" target="_blank">evil link</a>
