### ISSUE TITLE
HtmlSanitizer is not cleaning up specific script tags

### ISSUE THREAD

**Issue by vikramjb** [mganss/HtmlSanitizer#145]
Hello

Below given is one of of the test cases we are using and sanitizer does not seem to be cleaning up the script tags. I have already tested an attack using below given tag and the attack works. For some reason AngleSharp does not seem to be recognizing the ＜ tag.

Test＜script＞alert('XSS')＜/script＞

Is this a valid test case or is it expected behavior ?

Thank You for the library. It's a great tool!

**Comment by tiesont** [comment]
You can find the test suite for this library here: https://github.com/mganss/HtmlSanitizer/blob/master/test/HtmlSanitizer.Tests/Tests.cs

What you've included in your question would be sanitized by the default options. If it isn't, you'd need to provide a most complete example of what you're doing, including the versions of HtmlSanitizer and AngleSharp you're using.

**Comment by mganss** [comment]
@tiesont The angle brackets in the example are not regular ones but a different symbol ("full width less than sign", 0xFF1C).

@vikramjb In which browser does this work? I can't repro using a current browser.

GitHub outputs this untreated, too: ＜script＞alert('XSS')＜/script＞

**Comment by mganss** [comment]
Here's a question at StackOverflow about this topic: https://stackoverflow.com/questions/12558875/is-unicode-based-xss-an-issue
(tl;dr no XSS potential)

**Comment by mganss** [comment]
@vikramjb So you get alerts on this issue page here at GitHub, too?

**Comment by tiesont** [comment]
If I paste that exact code into a view in an ASP.NET MVC page, it's just text. If I throw it in ViewBag and echo it as raw text, it's just text. I also ran it through the sanitizer and echoed the sanitized value, and it was still just text, in IE, Edge, Chrome, and Firefox. If I had a Mac, I'd test Safari, but Webkit and Blink probably aren't that different.

Am I missing something? Not trying to be argumentative, I just can't reproduce. The only thing I haven't tried is posting a form with that content, to see if it gets transformed at some point (which seems unlikely).

**Comment by vikramjb** [comment]
@mganss not in github. But on my application where my display of output is using Html.Raw which allows content to be rendered as is since there will be valid html content. 

@tiesont There are two sides, one is sanitizing the input and then controlling the output. Currently the input sanitisation happens however, the content is rendered using Html.Raw which is allowing the browser the execute the script. 

I can show you guys a screenshot but its just going to be of an alert in the chrome. I am not trying to be opnionated here but I am just curious, shouldn't any script tags be cleansed regardless of the symbol ?

**Comment by vikramjb** [comment]
@mganss Also, currently what I am doing is this

```
byte[] propertyValueInBytes= Encoding.Default.GetBytes(dirtyPropertyValue);
string cleanedUpValue = Encoding.UTF8.GetString(propertyValueInBytes);
cleanedUpValue = new HtmlSanitizer().SanitizeDocument(cleanedUpValue );
```
The UTF8 encoding convert the special symbol back to a normal angular sign that HtmlSanitizer is able to sanitize.

**Comment by vikramjb** [comment]
Let me get a sample project going and show how it is doing. I am definitely getting an alert when that specific tag was used.

**Comment by vikramjb** [comment]
OK I wrote the following code in a console application .

`            string testCase1 = "Test<script>console.log(new Date().toLocaleString())</script>";
            string testCase2 = "Pen%ef%bc%9cscript%ef%bc%9ealert(\"Vulnerable to XSS!\")%ef%bc%9c/script%ef%bc%9e";
            string testCase3 = "Pen＜script＞alert('Vulnerable to XSS!')＜/script＞";
            string testCase4 = "Pen<script>alert('Vulnerable to XSS!')</script>";
            string testCase5 = "Test\\u003cscript\\u003econsole.log(new Date().toLocaleString())\\u003c/script\\u003e";
            HtmlSanitizer htmlSanitizer = new HtmlSanitizer();

            Console.WriteLine(htmlSanitizer.Sanitize(testCase1));
            Console.WriteLine(htmlSanitizer.Sanitize(testCase2));
            Console.WriteLine(htmlSanitizer.Sanitize(testCase3));
            Console.WriteLine(htmlSanitizer.Sanitize(testCase4));
            Console.WriteLine(htmlSanitizer.Sanitize(testCase5));`


testCase1, testCase4 is getting cleaned up. Rest of the test case have their script tags intact. \u003c is definitely a less than sign. And it should have been cleaned up but it never did.

I am new to this encoding and decoding business so apologies if I am mis-understanding the core concept. Does the console example help ?

**Comment by tiesont** [comment]
Not seeing that, although a console app isn't the best test case. If I create a throw-away ASP.NET MVC app, and create this view, it's all sanitized properly:

```html
@{
    ViewBag.Title = "Home Page";

    string testCase1 = "testCase1: Test<script>console.log(new Date().toLocaleString())</script>";
    string testCase2 = "testCase2: Pen%ef%bc%9cscript%ef%bc%9ealert(\"testCase2: Vulnerable to XSS!\")%ef%bc%9c/script%ef%bc%9e";
    string testCase3 = "testCase3: Pen＜script＞alert('testCase3: Vulnerable to XSS!')＜/script＞";
    string testCase4 = "testCase4: Pen<script>alert('testCase4: Vulnerable to XSS!')</script>";
    string testCase5 = "testCase5: Test\\u003cscript\\u003econsole.log(new Date().toLocaleString())\\u003c/script\\u003e";
    var htmlSanitizer = new Ganss.XSS.HtmlSanitizer();
}

<div class="jumbotron">
    <h1>Ganss.XSS.HtmlSanitizer</h1>
    <p class="lead">This is a test of the HtmlSanitizer project.</p>
    <p>
        See <a href="https://github.com/mganss/HtmlSanitizer/issues/145">https://github.com/mganss/HtmlSanitizer/issues/145</a>
    </p>
</div>

<div class="row">
    <div class="col-sm-12">
        <p>
            @Html.Raw(htmlSanitizer.Sanitize(testCase1))
        </p>
        <p>
            @Html.Raw(htmlSanitizer.Sanitize(testCase2))
        </p>
        <p>
            @Html.Raw(htmlSanitizer.Sanitize(testCase3))
        </p>
        <p>
            @Html.Raw(htmlSanitizer.Sanitize(testCase4))
        </p>
        <p>
            @Html.Raw(htmlSanitizer.Sanitize(testCase5))
        </p>
    </div>
</div>
```

Here's the page as I see it:

![htmlsanitizer-test_](https://user-images.githubusercontent.com/420293/45278018-3101d600-b499-11e8-9ecf-0fedd7b789cf.png)

I didn't have any alerts to dismiss. 

Test case 3 _looks_ like a script tag (which is what I thought with your original post), but it's not. A console window tends to use a monospace font, so it's not likely to show a visual difference between the two characters. Their character values are not the same, though, so a browser isn't supposed to treat something like `＜script＞` as if it were HTML.

The only way I can see this working (or would that be _not_ working?) is if the `＜` character is somehow being decomposed into the half-width version (`<`), where the "wide" bits are being striped out when you output the value (so you're actually rendering `<`).

**Comment by vikramjb** [comment]
@tiesont Thanks a ton for the effort 👍 

Let me get a sample app from my side and see if the same goes.

**Comment by mganss** [comment]
In test case 5 the backslash is escaped, that's why it's not a Unicode literal but simply a backslash followed by 003c.

**Comment by tiesont** [comment]
Just a quick follow-up: the only way I can get "real" script tags is if I copy and paste the output of a Console.WriteLine (like the example from https://github.com/mganss/HtmlSanitizer/issues/145#issuecomment-419784347) into a new editor (Notepad++, in this case). So I would hazard a guess that monospace fonts (like what Windows uses in the command window), since they can't display wide characters, effectively discard half the character when displaying text (so it only displays the half-width character). So, there _is_ (in theory) a path to injecting script tags using `＜script＞`, but it seems convoluted and (IMHO) outside the scope of the problem HtmlSanitizer is meant to solve.

**Comment by vikramjb** [comment]
@tiesont @mganss Currently the way I am mitigating the script tag is using the best fit. Once I get the input, I do an Encoding.UTF8 and then pass it through the sanitiser. When I do that, it works flawlessly. I haven't been able to whip up an example web app.

I agree with doing all possible best fit replacements, not sure if it needs be a tight knit part of the sanitize method or provided like a flag which can be used on optional basis depending on the need.
