### ISSUE TITLE
Single quotes within style attributes are converted to &quot; on Html output

### ISSUE THREAD

**Issue by starlight54** [mganss/HtmlSanitizer#146]
Sometimes single quotes are required in CSS, a simple repro of the issue is as follows:

```
var htmlSan = new HtmlSanitizer();
var input = "<div style=\"font-family: 'Open Sans'\">text</div>";
Console.WriteLine(htmlSan.Sanitize(input));
```

Which outputs:

`<div style="font-family: &quot;Open Sans&quot;">text</div>`

Because during execution of `SanitizeStyle` there is a call to `element.Style.ToCss()` which returns:

`font-family: "Open Sans"`

As this doesn't have the context that it is already inside double quotes for the attribute value, and it doesn't return the single quotes that were originally used.

This is then set as the `element.SetAttribute("style", element.Style.ToCss())` directly, resulting in the double quotes in the DOM being nested, and giving the final (after some fixes it seems) output.

I've had a little dig into the AngleSharp side of it, it appears that the value for the style attribute in `element.Attributes` is as expected (with single quotes), but the `element.Style` property doesn't have (or is not concerned with) the context and so is storing values with double quotes.

I wouldn't mind fixing this but you might know a trick or two that I don't regarding AngleSharp or your own library? I can't see any obvious fix like telling AngleSharp to use single quotes in the formatter etc.

**Comment by mganss** [comment]
Thanks for your input. The line https://github.com/mganss/HtmlSanitizer/blob/82d8ca44aac1e7e8a5419b9d5ba420523b01acc7/src/HtmlSanitizer/HtmlSanitizer.cs#L723 sets the `style` attribute's value to the parsed CSS. This gets rid of all extraneous crap in the CSS, possibly even some XSS that relies on parser bugs in specific browsers (although I can't think of an example off the top of my head). The `&quot;`s in the output are syntactically correct HTML so this boils down to a cosmetic issue. I agree that it might be preferable to preserve the original formatting, though OTOH someone might argue that it's better to normalize the quote formatting.

If you can come up with something that preserves the original formatting and still uses the parsed CSS in the output that would be interesting. You might want to look into how https://github.com/rgrove/sanitize deals with this problem.

**Comment by starlight54** [comment]
Sorry I've been away for a few days. 

This is my mistake really, I was operating under the assumption that using `&quot;` would not be valid for inline styles! I should have tested that first, but my output isn't in viewer at the moment...

Since it is valid, and most of the time this is not required, I think this falls under the same bracket as all the other normalisation in the HTML output, I'm fine with quote normalisation in this case, so we can close this I think.
