### ISSUE TITLE
Sanitizer removes place-holders considering as tags

### ISSUE THREAD

**Issue by sunitana** [mganss/HtmlSanitizer#151]
Consider the following text.

Input:
```
"Please provide your details in the below placeholders.
My Name is <insert name here>. I am belong to <Insert location here>."
```

Output:
```
"Please provide your details in the below placeholders.
My Name is . I am belong to ."
```

Here the content in between the < and > symbols are valid data. COuld there be any way to address this? or we have to consider that we should not use < & > character like above pattern at all ??

Please respond. Thanks in advance.

**Comment by mganss** [comment]
Duplicate of #91. Please see there for possible solutions.

**Comment by sunitana** [comment]
Hi Michael, Thanks for your response. I reviewed the post #91 as you suggested and agree with the hack (putting a space next to  <) you have mentioned. However, if we have one "<" symbol and some important data after that, the issue becomes critical.
for Ex:
input: "Here are <some important information"
output: "Here are "

We are loosing the data here even if with a single "<" as well and it is really huge task to put a blank space in huge amount of data when it is stored somewhere in database.
Could you please look into this issue and find some other workaround for this?

Thanks,
Sunita

**Comment by tiesont** [comment]
If you're displaying this content in something like a web browser, then I would assume using the encoded versions of `<` and `>` would work.

So
```html
"Please provide your details in the below placeholders.
My Name is &lt;insert name here&gt;. I am belong to &lt;Insert location here&gt;."
```
or
```html
"Please provide your details in the below placeholders.
My Name is &#60;insert name here&#62;. I am belong to &#60;Insert location here&#62;."
```
Either of those would render as:
> Please provide your details in the below placeholders.
> My Name is &lt;insert name here&gt;. I am belong to &lt;Insert location here&gt;.

An alternative (which I would not really recommend) is to try adding `insert` as an allowed tag, since the core issue is that `<insert` is being treated as if it were an opening tag (which is how a web browser would likely interpret it, too). You could also try something like [this FAQ](https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing).

**Comment by sunitana** [comment]
> If you're displaying this content in something like a web browser, then I would assume using the encoded versions of `<` and `>` would work.
> 
> So
> 
> ```
> "Please provide your details in the below placeholders.
> My Name is &lt;insert name here&gt;. I am belong to &lt;Insert location here&gt;."
> ```
> 
> or
> 
> ```
> "Please provide your details in the below placeholders.
> My Name is &#60;insert name here&#62;. I am belong to &#60;Insert location here&#62;."
> ```
> 
> Either of those would render as:
> 
> > Please provide your details in the below placeholders.
> > My Name is <insert name here>. I am belong to <Insert location here>.
> 
> An alternative (which I would not really recommend) is to try adding `insert` as an allowed tag, since the core issue is that `<insert` is being treated as if it were an opening tag (which is how a web browser would likely interpret it, too). You could also try something like [this FAQ](https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing).

Thanks for your quick response again ! :)
About the example I gave above is purely a made up string :) 
I do not use any such exact text (like 'insert' I mentioned above). However the input we get is from users who do not have any idea about HTML stuff. Hence if you consider about the second example I gave ("Here are <some important information"), we are loosing the data here just because of a `<` symbol.

About encoding the character, the tough task is to know when to encode, I mean when / how to know whether the input string is non-HTML. Please suggest.

And regarding the nonHTML file you have mentioned in gist, is it included in the new release ??

Thanks in Advance !

**Comment by tiesont** [comment]
I think you're confusing my response with that of mganss, but to answer your question, no, that code from the gist is just an example of how to handle content that might be incorrectly parsed as HTML.

**Comment by mganss** [comment]
@tiesont Sorry, I forgot we have that in the FAQ already 😄 

> About encoding the character, the tough task is to know when to encode, I mean when / how to know whether the input string is non-HTML. Please suggest.

If you have arbitrary input you cannot know what the intentions of the person were when they wrote it. Was it an XSS attempt or just a comment about HTML? If you want to allow some HTML then the code in the FAQ is the best you can do IMHO. If you don't want to allow any HTML, then just HTML encode your input and be done with it (no need for a sanitizer, no hacky workarounds).
