### ISSUE TITLE
HtmlSanitizer replacing carriage return symbol incorrectly.

### ISSUE THREAD

**Issue by SashaMalahov** [mganss/HtmlSanitizer#153]
Hello,
I have the following string:
some\r\ntext
I got such string when I wrote "some", put Enter and then wrote "text"
After calling Sanitize method, like 
var sanitizer = new HtmlSanitizer();
var sanitized = sanitizer.Sanitize("some\r\ntext");

sanitized had the following value : "some\ntext"

Is it a correct behavior or a bug?

Thanks in advance.

**Comment by mganss** [comment]
This is expected behavior and is the result of HTML parsing ([specification](https://www.w3.org/TR/2011/WD-html5-20110113/parsing.html#preprocessing-the-input-stream)). Quote:

> U+000D CARRIAGE RETURN (CR) characters and U+000A LINE FEED (LF) characters are treated specially. Any CR characters that are followed by LF characters must be removed, and any CR characters not followed by LF characters must be converted to LF characters. Thus, newlines in HTML DOMs are represented by LF characters, and there are never any CR characters in the input to the tokenization stage.
