### ISSUE TITLE
Attributes with empty values are always removed, but some are valid

### ISSUE THREAD

**Issue by starlight54** [mganss/HtmlSanitizer#155]
I see a fix was applied for https://github.com/mganss/HtmlSanitizer/issues/137

This fix appears to work by just not letting AngleSharp set the attribute values, such that values which the sanitiser is fine with just get left alone, hence the square brackets are fine.

However in commit https://github.com/mganss/HtmlSanitizer/commit/82d8ca44aac1e7e8a5419b9d5ba420523b01acc7#diff-9b7c5dba956424b630e28575945cfd7c there is another addition, which seems to me to be indiscriminately removing all attributes which don't have values without even calling the `RemoveAttribute` event.

The HTML fragment `<video controls></video>` thus has it's `controls` attribute removed (after allowing it by the usual means), without any possibility of prevention from the library user. But this is valid HTML, and there are other valid attributes which don't require values.

Am I missing something, or was this an oversight? Maybe AngleSharp had an update even earlier than this which caused it to start removing attributes without values so this was seen as a non-issue from the library side?

I think maybe a simple fix would be to call `RemoveAttribute` as normal with a new `RemovalReason` of `AttributeValueEmpty` or just reuse `NotAllowedValue`? This would still be a breaking change though...

**Comment by tiesont** [comment]
Your specific example isn't true in the current version: https://dotnetfiddle.net/XPvrpp

It's updated to have an empty value for controls, but not removed. Can you create an updated fiddle that does demonstrate what you're seeing?

**Comment by starlight54** [comment]
Sorry, just bumping this, my account was flagged by automation, so this has issue temporarily disappeared!

**Comment by mganss** [comment]
This was an oversight. The only reason empty attributes are removed is because otherwise empty `style` attributes are left behind if all style declarations are removed. I have changed this to only remove empty `style` attributes and only if they were not empty before sanitizing the style. Also, the `RemovingAttribute` event is invoked with a new reason enum value of `StyleAttributeEmpty`, making it possible to cancel removal.

**Comment by starlight54** [comment]
Thanks for the fix, awesome library btw! :)

**Comment by tiesont** [comment]
@mganss Should the wiki be updated to show the possible reason enum values? Looks like I missed those when I stubbed out the wiki pages before.

**Comment by mganss** [comment]
@tiesont Yes, I've just updated https://github.com/mganss/HtmlSanitizer/wiki/Hooks, but could you try and update the API docs, possibly using [DocFX](https://dotnet.github.io/docfx/)?

**Comment by mganss** [comment]
@tiesont Regarding API docs, it might be more flexible to actually add a GitHub Pages site. Unlike the FAQ, Examples, etc. the API docs are not something that should be edited but rather always generated from the source. Ideally, it would be generated (and pushed to GitHub) with every (successful) AppVeyor build. On the DocFX Getting Started page, there's even a section about [AppVeyor integration](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#4-use-docfx-with-a-build-server).

When [FuGet](https://www.fuget.org/) was announced, I thought it might be a good idea to just link to that, but unfortunately they're missing a lot of the XML documentation: https://www.fuget.org/packages/HtmlSanitizer
