### ISSUE TITLE
Sanitize URL post-filter

### ISSUE THREAD

**Issue by stevenmoberg** [mganss/HtmlSanitizer#156]
Could you add a filtering callback event for SanitizedURL so that they could be filtered to prevent against XSRF or SSRF from valid URI attributes, or mark it as virtual so that it can be overwritten and extended in sub classes.

Or should requests like these come from pull requests?

**Comment by stevenmoberg** [comment]
wow - thanks for the speedy reply

**Comment by smitburde** [comment]
@mganss Do you maintain the release notes for the security issues fixed for latest htmlsanitizer?

**Comment by mganss** [comment]
@smitburde Release notes can be found at https://github.com/mganss/HtmlSanitizer/releases (pretty spartan, I know :)
