### ISSUE TITLE
Is it possible set a flag(true/false)  property after sanitize?

### ISSUE THREAD

**Issue by chucklu** [mganss/HtmlSanitizer#159]
Hi,
```C#
       var html="";
     HtmlSanitizer sanitizer = new HtmlSanitizer();
      var sanitized = sanitizer.Sanitize(html);
```  
      
   

 What I want to achieve is, check if the input html is legal or not (according the xsss).
    After `var sanitized = sanitizer.Sanitize(html);`  I can use sanitizer.IsLegal property to decide if the input html is legal or not.

Currently, I might need register all [events](https://github.com/mganss/HtmlSanitizer/wiki/Hooks)  and mark flag to check if the events were fired or not.

**Comment by mganss** [comment]
Sorry for the late response and thank you for your feedback. 

I'd rather not add this feature as it would require additional bookkeeping and I would like to keep the library focused.

As you pointed out, the use case is already supported through events.

**Comment by chucklu** [comment]
@mganss Thanks
