### ISSUE TITLE
Recursively remove empty blocks

### ISSUE THREAD

**Issue by farlock85** [mganss/HtmlSanitizer#160]
I have the following input that I receive from Talon after parsing an email:

```
<html><head></head><body><div style="font-family: Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
This is a reply.</div>
<div>
<div id="appendonsend"></div>
<div style="font-family:Calibri,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0)">
<br>
</div>
<hr style="display:inline-block; width:98%" tabindex="-1">
</div></body></html>
```

I initialized the sanitizer with the options:
```
_htmlSanitizer = new HtmlSanitizer();
_htmlSanitizer.AllowedCssProperties.Remove("font-family");
_htmlSanitizer.AllowedCssProperties.Remove("font-size");
_htmlSanitizer.AllowedTags.Remove("hr");
```
The result is:
```
<div style="color: rgb(0, 0, 0)">
This is a reply.</div>
<div>
<div></div>
<div style="color: rgb(0,0,0)">
<br>
</div>
</div>
```
Should it remove the empty div?

**Comment by mganss** [comment]
No, the result looks fine. Keep in mind that the sanitizer does not fix invalid HTML (although the parser does fix some things like unbalanced tags). See also the examples at https://github.com/mganss/HtmlSanitizer#text-content-not-necessarily-preserved-as-is
It can even be the case that the HTML is more broken after sanitization than it was before, e.g. if a div had contained a single script element.
If you want empty divs to be removed (or fix other invalid constructs) you can use the `PostProcessNode` and `PostProcessDom`. There's also [HTML Tidy](http://www.html-tidy.org/) and a [.NET interface library](https://github.com/markbeaton/TidyManaged) for it exists.

**Comment by farlock85** [comment]
Thanks @mganss! I was confused by another issue where it was talking about the removal of empty attributes. Different issue!
