### ISSUE TITLE
Frame and Frameset tags do not trigger RemovingTag event

### ISSUE THREAD

**Issue by skylerberg** [mganss/HtmlSanitizer#163]
# Impact

Users relying on events like `RemovingTag` to determine if some HTML has dangerous elements will be vulnerable to XSS.

# Description

The `<frameset>` and `<frame>` tags are likely handled specially by AngleSharp. This causes them to not show up in the DOM and be missed by `HtmlSanitizer`'s event generation code.

# Reproduction
```
        // This test passes
        [Fact]
        public void RemovingScriptShouldTriggerEventTest()
        {
            var sanitizer = new HtmlSanitizer();
            bool anyNodeRemoved = false;
            sanitizer.RemovingTag += (s, e) => anyNodeRemoved = true;
            var html = @"<script></script>";
            sanitizer.Sanitize(html);
            Assert.True(anyNodeRemoved);
        }

        // This test fails
        [Fact]
        public void RemovingFramesetShouldTriggerEventTest()
        {
            var sanitizer = new HtmlSanitizer();
            bool anyNodeRemoved = false;
            sanitizer.RemovingTag += (s, e) => anyNodeRemoved = true;
            var html = @"<frameset><frame src=""javascript:alert(1)""></frame></frameset>";
            sanitizer.Sanitize(html);
            Assert.True(anyNodeRemoved);
        }
```

# Additional notes

My use case is implementing a wrapper class that can determine if HTML is safe without altering the original HTML. With previous versions of `HtmlSanitizer`, I have maintained a fork of the repository. To fix the frameset issue for my fork, I had to make some changes to `CsQuery`. It is likely that this bug is caused by how `AngleSharp` interprets `<frameset>` tags.

Let me know if you have any questions or any suggestions.

Cheers,
Skyler

**Comment by tiesont** [comment]
Possibly related? https://github.com/AngleSharp/AngleSharp/issues/631

**Comment by skylerberg** [comment]
@tiesont thanks for looking into this. That change is possibly related, however, setting `IsNotSupportingFrames` did not resolve the issue (test is still failing).

Note: The `IsNotSupportingFrames` option is only available in newer versions of AngleSharp. These new versions had lots of backwards incompatible changes and did not target the same framework versions that `HtmlSanitizer` does. In my tests, I did the minimum to get the new version working with `HtmlSanitizer` without regard for what else broke.

**Comment by mganss** [comment]
When you call `Sanitize()` it will sanitize a body fragment. A `frameset` element is ignored by the HTML parser inside the body. That's why it doesn't even reach the sanitizing stage. If you call `SanitizeDocument()` with a `frameset` element inside `<html>` you'll see it get removed:

```c#
var sanitizer = new HtmlSanitizer();
bool anyNodeRemoved = false;
sanitizer.RemovingTag += (s, e) => anyNodeRemoved = true;
var html = @"<html><frameset><frame src=""javascript:alert(1)""></frame></frameset></html>";
var actual = sanitizer.SanitizeDocument(html);
Assert.True(anyNodeRemoved);
Assert.Equal("<html><head></head></html>", actual);
```

**Comment by skylerberg** [comment]
@mganss Thanks for the explanation and thanks for your excellent maintenance of this package :)
