### ISSUE TITLE
SanitizeDocument does not sanitize the root html element

### ISSUE THREAD

**Issue by acostadelivra** [mganss/HtmlSanitizer#164]
The HtmlSanitizer's SanitizeDocument function does not sanitize the root html element.

For example, sanitizing the trivial document:
`<html onmousemove="alert(document.location)"><head></head><body></body></html>`
does not strip the onmousemove attribute, which is not an allowed attribute.

It appears to me this is due to the use of QuerySelectorAll("*") in DoSanitize which only returns descendants and effectively skips the "context" element.

**Comment by mganss** [comment]
Thanks for catching this! Fixed in 4.0.217 (and 5.0.218-beta).
