### ISSUE TITLE
[Feature request] Allowed urls

### ISSUE THREAD

**Issue by DmitrijOkeanij** [mganss/HtmlSanitizer#165]
For `iframe`, img and others tags with URL to make allowed list of domens.
For example I need to allow only `iframes` pointed to youtube and block others.

Or to allow images only from MyDomain.

**Comment by mganss** [comment]
I think the scope for this use case is too specific. You can achieve this by subscribing to the `RemovingAttribute` and `RemovingStyle` events (the `RemoveReason` will be `NotAllowedUrlValue`) and cancelling them when you see a URL that you want to allow.

**Comment by EvanSevy** [comment]
@mganss As far as protecting an iframe goes, I would only have to handle that by the `RemovingTag` event subscription and not the '`RemovingAttribute`' or '`RemovingStyle`' events that you mentioned above?  I don't think you can insert a iframe within an attribute or style, and so would not need those other events, is this correct?

Also, for further clarification and to put my mind to rest, the default Sanitize function provided by your 'HtmlSanitizer' should make my html XSS protected, correct?  For instance, I'm am using HtmlSanitizer to protect my WYSIWYG submissions.

Here is a snippet of my code if anybody is interested:
```
static void FilterTags(object sender, RemovingTagEventArgs e)
{
	IframeWhitelistBase.ForEach((baseUrl) =>
	{
		if (e.Tag.TagName.ToLower().Equals("iframe") && e.Tag.GetAttribute("src").StartsWith("//" + baseUrl))
		{
			e.Reason = RemoveReason.NotAllowedUrlValue;
			e.Cancel = true;
		}
	});
}
```

and the subscription and call:
```
var sanitizer = new HtmlSanitizer();
sanitizer.RemovingTag += FilterTags;
var sanitized = sanitizer.Sanitize(projectSubmit.projectHtmlPage);
```

**Comment by mganss** [comment]
@EvanSevy Yes, but I recommend thinking about exactly which elements you want to allow. For example, if your use case is a comments section of a web application, you might just want to allow a very restricted set of, say, `b`, `i`, and `u` plus perhaps a few others. You probably wouldn't want to allow your users to add forms, footers, or `h1`s. Same goes for attributes and CSS.

**Comment by EvanSevy** [comment]
@mganss Is there a blacklist option in contrast with '.AllowedTags', just so I can get rid of a few tags, such as 'form' and 'input'?  As I'm fine with keeping most of your defaults.

**Comment by mganss** [comment]
@EvanSevy You can remove elements from the `AllowedTags` set (and thus disallow them):
```c#
sanitizer.AllowedTags.ExceptWith(new[] { "form", "input" }); // for a single instance
// or
HtmlSanitizer.DefaultAllowedTags.ExceptWith(new[] { "form", "input" }); // change the default
```
