### ISSUE TITLE
Image with relative path - src attribute disappears

### ISSUE THREAD

**Issue by CodePala** [mganss/HtmlSanitizer#176]
by using sanitizer.Sanitize(html), src attribute values disappears. 

`<img src="c:/temp/test.png"  />`

becomes 

`<img>`

How do we handle this with images ? Please suggest ?

**Comment by mganss** [comment]
You'll need to allow the `file` scheme in URLs:

```c#
sanitizer.AllowedSchemes.Add("file");
```
