### ISSUE TITLE
Odd behavior of online sanatize demo when given certain text

### ISSUE THREAD

**Issue by giwleb** [mganss/HtmlSanitizer#180]
Not sure why this causes a connection reset one the demo page: 

&username=%3Cscript%3Ealert(%22XSSmattINFOSEC%22)%3C%2Fscript%3E

http://xss.ganss.org/

**Comment by giwleb** [comment]
This text also causes a reset for me:

<script>alert('XSSmartINFOSEC')</script>

Am I using it wrong?

**Comment by mganss** [comment]
The demo page doesn't show anything on the right hand side if the output string is empty (odd, I know, but it is how it is :) That explains the second example. If I enter your first example I get output but I'm not sure if the text in your comment is the example you had input or if it's an escaped form. Please use backticks when entering literal code.
