### ISSUE TITLE
Javascript junction sanitizer

### ISSUE THREAD

**Issue by blueberry80** [mganss/HtmlSanitizer#181]
Hi , why is it that  the following will become :
`<a href="#" onclick="javascript:__doPostBack('laaa','', 'aaa');return false;" rel="noopener noreferrer" style="color:red" target="_blank"> here</a>`
will become : 
`<a rel="noopener noreferrer" style="color:red" target="_blank"> here</a>`? 

The whole href is taken out.

**Comment by mganss** [comment]
I can't repro. Which version are you using? Can you post a code example?

**Comment by blueberry80** [comment]
I went to this URL : http://xss.ganss.org/ to test out the html script . Is version HtmlSanitizer 4.0.181

**Comment by mganss** [comment]
The online demo doesn't show the problem 🤷‍♂ I get
```html
<a href="#" rel="noopener noreferrer" style="color: red" target="_blank"> here</a>
```
