### ISSUE TITLE
Everything removed after < with no space

### ISSUE THREAD

**Issue by Dominic-Emond** [mganss/HtmlSanitizer#191]
Hey,
In the example below, everything after the bracket gets removed:
```
_Text <test even more text
text........_
```
Is this working as intended? Also, would it be an XSS issue to remove that bracket before the sanitization happens?

**Comment by mganss** [comment]
Duplicate of #91. See [this example in the Wiki](https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing) for  a possible solution.
