### ISSUE TITLE
[Possible bug] Sanitizer strips &lt; if there isn't a space after it

### ISSUE THREAD

**Issue by ChrisSwinchatt** [mganss/HtmlSanitizer#192]
Hi there,

I'm generating HTML emails from templates which are allowed to contain a subset of HTML tags and plan to use HtmlSanitizer to remove the tags we don't allow (precisely, the templates can contain HTML but the values being substituted in can't).

The problem is that the sanitizer interprets things like "X&lt;Y?" as containing a "&lt;Y&gt;" tag. I've tried to work around this by replacing &lt; and &gt; in substituted values with `&lt;` and `&gt;` but it still removes the sanitized tags, unless I insert a space after the &lt;. 

Is this intentional behaviour or a bug?

For now I can remove the extra spaces after substitution, but it's ugly and I'd like to get rid of it at some point.

## Repro

```csharp

using System;
using Ganss.XSS;

public class Program
{
    public static void Main()
    {
        var sanitizer = new HtmlSanitizer();
        var html = @"Uh oh I accidentally &lt; put an html tag in my email what a fool";
        var sanitized = sanitizer.Sanitize(html, "http://www.example.com");
        Console.WriteLine(sanitized);
    }
}
```

Output: `Uh oh I accidentally &lt; put an html tag in my email what a fool`

```csharp
using System;
using Ganss.XSS;


					
public class Program
{
	public static void Main()
	{
		var sanitizer = new HtmlSanitizer();
		var html = @"Uh oh I accidentally &lt;put an html tag in my email what a fool";
		var sanitized = sanitizer.Sanitize(html, "http://www.example.com");
		Console.WriteLine(sanitized);	
	}
}
```

Output: `Uh oh I accidentally`

**Comment by tiesont** [comment]
This is similar to #191. You'll need to manually handle cases like this. The [wiki](https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing) has an example of how this can be done.

**Comment by mganss** [comment]
I can't repro your repro. Which version of HtmlSanitizer are you using?

**Comment by ChrisSwinchatt** [comment]
It was version 4.0.217. But it looks like dotnetfiddle was silent replacing my `&lt;` and `&gt;` with `<` and `>` during compilation.
