### ISSUE TITLE
HTML sanitizer online tool vs fiddleissue

### ISSUE THREAD

**Issue by geobenedwin** [mganss/HtmlSanitizer#193]
I tried the  same string in both online tool as well as in the .net fiddle both seems to give a different result

html string - "<img alt=\"a\" src=\"a\" title=\"<iframe/foo=&quot><script>alert(document.domain)</script></iframe>\">"

online tool output - "<img alt="\&quot;a\&quot;" src="\&quot;a\&quot;" title="\&quot;&lt;iframe/foo=&quot;">\"&gt;"
![image](https://user-images.githubusercontent.com/56097787/66090320-affbfd80-e537-11e9-9a2e-29f414b60bae.png)

fiddler output - <img alt="a" src="a" title="&lt;iframe/foo=&quot;&gt;&lt;script&gt;alert(document.domain)&lt;/script&gt;&lt;/iframe&gt;">
![image](https://user-images.githubusercontent.com/56097787/66090327-b8543880-e537-11e9-8acc-18be155ae1c9.png)

using the dll in code is also not sanitizing the HTML like the onlinetool, need some info what should be done in code to get an output as onlinetool

**Comment by mganss** [comment]
You can use [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/) to format and syntax highlight example code.

I assume the input is this:

```html
<img alt="a" src="a" title="<iframe/foo=&quot><script>alert(document.domain)</script></iframe>">
```

I get this from code as well as the online demo and .NET Fiddle:

```html
<img alt="a" src="a" title="&lt;iframe/foo=&quot;&gt;&lt;script&gt;alert(document.domain)&lt;/script&gt;&lt;/iframe&gt;">
```

The code used is this:

```c#
var html = @"<img alt=""a"" src=""a"" title=""<iframe/foo=&quot><script>alert(document.domain)</script></iframe>"">";
var s = sanitizer.Sanitize(html);
```

**Comment by geobenedwin** [comment]
Thankyou for your reply @mganss,
But I want the scrip tags and the alert to be removed after sanitization, which the online tool is doing, but the fiddle and dll in code fails to do.

Question here is what need to be done to get the script and alert removed after sanitization

**Comment by geobenedwin** [comment]
> You can use [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/) to format and syntax highlight example code.
> 
> I assume the input is this:
> 
> ```
> <img alt="a" src="a" title="<iframe/foo=&quot><script>alert(document.domain)</script></iframe>">
> ```
> 
> I get this from code as well as the online demo and .NET Fiddle:
> 
> ```
> <img alt="a" src="a" title="&lt;iframe/foo=&quot;&gt;&lt;script&gt;alert(document.domain)&lt;/script&gt;&lt;/iframe&gt;">
> ```
> 
> The code used is this:
> 
> ```cs
> var html = @"<img alt=""a"" src=""a"" title=""<iframe/foo=&quot><script>alert(document.domain)</script></iframe>"">";
> var s = sanitizer.Sanitize(html);
> ```

Thankyou for your reply @mganss,
But I want the script tags and the alert to be removed after sanitization, which the online tool is doing, but the fiddle and dll in code fails to do.

Question here is what need to be done to get the script and alert removed after sanitization
![image](https://user-images.githubusercontent.com/56097787/66145263-53dcbc00-e5bf-11e9-841f-bef69165825d.png)

**Comment by mganss** [comment]
This works identically in the online demo, .NET Fiddle, and code:

```c#
var html = @"<img alt=""a"" src=""a"" title=""<iframe/foo=&quot><script>alert(document.domain)</script></iframe>"">";
var s = sanitizer.Sanitize(html);
```
