### ISSUE TITLE
Comments Tag

### ISSUE THREAD

**Issue by doaji** [mganss/HtmlSanitizer#195]
Hi, i noticed sanitizer, cleans out all comments in a html text. is there a tag i can pass for sanitizer to ignore comments?

**Comment by mganss** [comment]
Subscribe to the `RemovingComment` event and set the `Cancel` property to true. See also the [Hooks](https://github.com/mganss/HtmlSanitizer/wiki/Hooks) entry in the Wiki.

**Comment by doaji** [comment]
thanks for the quick response
