### ISSUE TITLE
Dependency Injection Example with .Net Core

### ISSUE THREAD

**Issue by danielrjames** [mganss/HtmlSanitizer#199]
Hi, I found the following example of using this library with dependency injection in .net core and was wondering if this is a best practice that you would recommend?

```
IHtmlSanitizer sanitizer = new HtmlSanitizer();
services.AddSingleton<IHtmlSanitizer>(sanitizer);
```

https://stackoverflow.com/a/58065965/7882670

**Comment by mganss** [comment]
Looks fine to me but for the general case I would prefer using the other option mentioned in the StackOverflow answer:

```c#
services.AddSingleton<IHtmlSanitizer>(_ => new HtmlSanitizer());
```

The difference is that this allows for automatic object disposal by the container. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0#service-registration-methods

**Comment by danielrjames** [comment]
Good deal. Thank you!
