### ISSUE TITLE
Sanitizing custom self closed tags

### ISSUE THREAD

**Issue by erasmosoares** [mganss/HtmlSanitizer#202]
Hi,

I'm passing to the sanitizer some allowed tags.

`sanitizer.AllowedTags.Add("Date");
sanitizer.AllowedTags.Add("Time");
`

After applying the sanitizer on self closed tags I have these results:

`var content = @"<Date/><Time/>";`

Default Format:
`<date><time></time></date>`

XhtmlFormat:
`<date><time /></date>`

This was the format I was expecting:
`<Date/><Time/>`
or
`<Date></Date><Time></Time>`

**Comment by tiesont** [comment]
Just to clarify, you've tried using an XHTML formatter, as shown [here](https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex3-replacing-the-default-formatter)?

**Comment by erasmosoares** [comment]
Hi, 

Yes, I'm passing as second argument baseUrl an empty string. From what I've seen, I only have this sanitizer method:

`public string Sanitize(string html, string baseUrl = "", IMarkupFormatter outputFormatter = null);`

Here's an example:

```
using Ganss.XSS;
using System;

namespace SanityzerTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var content = @"<Date/><Time/>";

            var sanitizer = new HtmlSanitizer();
            sanitizer.AllowedTags.Add("Date"); 
            sanitizer.AllowedTags.Add("Time");

            var formatter = AngleSharp.XHtml.XhtmlMarkupFormatter.Instance;
            var sanitizedValue = sanitizer.Sanitize(content,string.Empty, formatter);

        //returned value: "<date><time /></date>"
            Console.WriteLine(sanitizedValue);
        }
    }
}
```
I am using version 4.0.217.

**Comment by tiesont** [comment]
Well, `<time />` is a real tag ([MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time), so it makes sense that it's processed properly. I assume the `<date>` tag is normalized to a "valid" XML tag - not sure how you'd declare it as a self-closing tag.

**Comment by erasmosoares** [comment]
The same goes for any custom tags I pass, for example:
```
var sanitizer = new HtmlSanitizer();
sanitizer.AllowedTags.Add("customTag1"); 
sanitizer.AllowedTags.Add("customTag2");

// Input   --> <customTag1/><customTag2/>
// Output --> <customtag1><customtag2 /></customtag1>
```
Yes, probably it would be a case where a custom formatter would have to be created.

**Comment by mganss** [comment]
This is how an HTML parser behaves: See e.g. [here](https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5) for more information. It's a misconception that HTML has self-closing tags. The parser treats them as opening tags.

In a browser you get the same:
```js
var e = document.createElement("div");
e.innerHTML = "<Date/><Time/>";
e.innerHTML // => "<date><time></time></date>"
```

What's your use case? It seems your input is not intended to be HTML to begin with. If your input is XML that has HTML inside the content of some elements it might be better to use an XML parser (say, LINQ to XML) and then use HtmlSanitizer only on the content of those elements that may contain HTML.

**Comment by erasmosoares** [comment]
Thank you for clarifying.

Actually I was using it in order to pass as XML input, exactly the scenario you indicated. 
I will apply the Sanitizer only to elements that contain HTML.

Thank you.
