### ISSUE TITLE
`style` Tag and `class` Attribute are being removed

### ISSUE THREAD

**Issue by om-ha** [mganss/HtmlSanitizer#203]
When sanitizing my HTML string, I'm losing style information. The library is supposed to retain my HTML style.

**Comment by mganss** [comment]
Can you provide a minimal example?

**Comment by om-ha** [comment]
Solved! What a beast of a library.

Here's how I sanitized my HTML but kept its style intact:

1. I followed mganss's advice [here](https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing) and encoded non-HTML elements.

2. I encoded non-HTML elements added by C#. 

```
    var preprocessedText = encodedText.Replace("\n", "").Replace("\r", "").Replace("\t", "").Replace(@"\""", @"""");
```

3.  I added "style" tag to `AllowedTags`

```
sanitizer.AllowedTags.Add("style");
```

4. I added "class" attribute to `AllowedAttributes`

```
sanitizer.AllowedAttributes.Add("class");
```

And viola! everything worked as expected!

I did text diff with VS Code and found some HTML normalization. Nothing major.

My notes, can I do the following with a PR?
1. Add "style" tag to `DefaultAllowedTags`
2. Add "class" attribute to `DefaultAllowedAttributes`

If there is any high-risk associated with them please elaborate.

Awesome library!!! 🎉🎊

**Comment by om-ha** [comment]
@mganss thank you so much for the blazing quick reply and awesome library.

I opened this issue just to provide a fix for others!

**Comment by mganss** [comment]
@om-ha There is an attack called [`classjacking`](https://web.archive.org/web/20191220154349/https://html5sec.org/#123) where an attacker could use class to have script functionality attached to their input HTML.

Also, I don't think it's a good idea to allow third party HTML to use style, possibly destroying your layout or making their HTML look like it's part of your site (say, an error message or a modal dialog).

**Comment by om-ha** [comment]
Much obliged @mganss, appreciate the great explanation.

As per the two attack vectors you mentioned:
1- Allowing third party HTML to use `<style>` in my case is not a big issue, as the end result wouldn't have a use case where malicious users could imitate first-party content masquerading third-party behavior.
2- As for `classjacking` don't you think this is not a big issue if script tags are already disallowed in the sanitation rules?

**Comment by tiesont** [comment]
@om-ha You're probably already aware of some (or all of this), but if you might find the OWASP cheatsheets handy, specifically, https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html.

That's not an answer to your question(s), but it's useful information to have available.

**Comment by mganss** [comment]
@om-ha The classjacking attack is not so much about script or style that comes alongside the input but rather about script that's already there. 

The classic use case is a blog where user comments with HTML are input. If the blog has script that attaches event handlers to elements that have a specific class it will do so also for elements that are in the comments. 

Let's say there's code that shows elements as a modal dialog if they have `class="modal"`. Then a malicious comment could be made to show as a modal dialog. There are probably a myriad of other ways this could be abused.
