### ISSUE TITLE
Does not remove default allowed tags

### ISSUE THREAD

**Issue by shiranimni** [mganss/HtmlSanitizer#205]
Hi, I added tag "form" to RemovingTag and 
var html= "< div >< form action='/page.php' >< /form >< /div >";
sanitizer.Sanitize(html). 

The returned value is "< div >< form action='/page.php' >< /form >< /div >"

**Comment by mganss** [comment]
This is expected behavior. "Allowed" in this context means that these elements are not removed. All others that are not in the list of allowed elements are removed (such as `<script>`).

**Comment by shiranimni** [comment]
it works!
thanks
