### ISSUE TITLE
Nuget release

### ISSUE THREAD

**Issue by jasenf** [mganss/HtmlSanitizer#207]
Hi there,

Any plans for an update to the Nuget package?  The one currently available is about 8 months old and incompatible with more recent versions of Anglesharp.

thanks!
jasen

**Comment by mganss** [comment]
Yes, I'd like to get in a fix for #206 before, though. Does the latest beta work for you?

**Comment by jasenf** [comment]
Unfortunately this is for a production app so I can't test the beta.  I usually love to work with preleases, but in this scenario I'm just stuck with the latest Nuget.   No hurry, was just wondering.  Will stick with latest Nuget release until you have time.  Thanks for you efforts!

**Comment by mganss** [comment]
Released 5.0.298
