### ISSUE TITLE
Bug: href with tel are removed.

### ISSUE THREAD

**Issue by shyamal890** [mganss/HtmlSanitizer#209]
For example if the html has something like

`<a href="tel:+91743****5" target="_blank">07433*****5</a>`

It is converted to

 `<a target="_blank">07433*****5</a>`

Using the following code:

```
var sanitizer = new HtmlSanitizer();
sanitizer.AllowedAttributes.Add("class");
sanitizer.AllowedSchemes.Add("mailto");

var sanitized = sanitizer.Sanitize(html);
```

**Comment by mganss** [comment]
You need to allow the `tel` scheme as well:

```c#
sanitizer.AllowedSchemes.Add("tel");
```
