### ISSUE TITLE
Question: Release notes

### ISSUE THREAD

**Issue by b3hdad** [mganss/HtmlSanitizer#210]
Hi,

Thank you for your hard work. I have upgraded the HtmlSanitizer from 4.x to 5.x. I see it compiles fine, but are there any breaking changes or things to watch out for?

Are there any release notes?

Thank you.

**Comment by tiesont** [comment]
#206 impacts the 5.x release, so you probably want to review that. Docs will likely be updated at some point with any other changes, but I think that's the most obvious change.

**Comment by b3hdad** [comment]
@tiesont, thank you for your reply. I believe that won't effect me as I am not using ``AllowedCssClasses``. I use only AllowedTags, AllowedAttributes, AllowedCssProperties and AllowedSchemes. If there is no other major concerns I will close this soon.

**Comment by mganss** [comment]
Release notes are here: https://github.com/mganss/HtmlSanitizer/releases/tag/v5.0.298
The other major change besides what @tiesont mentioned is that we're now using AngleSharp 0.13 (see #154)

**Comment by b3hdad** [comment]
@mganss thank you for the info. That looks also fine. They all seem to get along.
Thanks again everyone.
