### ISSUE TITLE
Idea: create Javascript / jQuery port

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#22]
This library uses heavily the CsQuery project, which is a good thing. CsQuery is a port of jQuery.

Would not it be cool if this library got ported to Javascript / jQuery?

**Comment by mganss** [comment]
Sure, though I can imagine there are already a good number of sanitizers in JavaScript.

**Comment by 304NotModified** [comment]
Well, can't find them!

**Comment by 304NotModified** [comment]
Really, can't find a mature project. Only some stuff on Gist (https://gist.github.com/kanokgan/3358126) 

google search: https://www.google.nl/search?q=anti-xss+library%3F+(jQuery+or+javascript)+github%3F

**Comment by mganss** [comment]
I see. If you could contribute a port, that would be awesome.

**Comment by 304NotModified** [comment]
Too bad I'm too busy with NLog for this.

**Comment by 304NotModified** [comment]
Found one: https://github.com/punkave/sanitize-html
