### ISSUE TITLE
Dependency injection in .Net Core - default constructor

### ISSUE THREAD

**Issue by vmati** [mganss/HtmlSanitizer#220]
I define service in .Net Core as follows:
`serviceCollection.AddSingleton<IHtmlSanitizer, HtmlSanitizer>();
`
Beacuse HtmlSanitizer is missing parameterless constructor in code default value for AllowedTags are not set. 

Everything is ok when I create instance with 'new'.
`serviceCollection.AddSingleton<IHtmlSanitizer, HtmlSanitizer>(_ => new HtmlSanitizer());`

In first case if class doesn't have default constructor, C# genertes it.

**Comment by mganss** [comment]
I believe in the first case the container passes empty collections into the constructor (not nulls). If we had a default constructor, wouldn't the container still choose the constructor with more parameters? Do you have a suggestion how to improve the situation (keep in mind versioning issues need to be addressed, see #206)?

**Comment by dk307** [comment]
This broke my use case where I was using all empty arrays in parameters for constructor to it strip all Html using empty arrays. 
Empty array and null as not same.

**Comment by mganss** [comment]
@dk307 I'm sorry. Passing an empty array for just the `allowedTags` parameter (leaving all others null) should yield the same behavior.

**Comment by dk307** [comment]
@mganss 
That worked, Thanks
