### ISSUE TITLE
Thread safety with HtmlSanitizer class

### ISSUE THREAD

**Issue by fatagun** [mganss/HtmlSanitizer#227]
Hello, 

I wanted to ask and possibly verify the thread safety of HtmlSanitizer object. 

Is it thread safe? Can I use it as singleton or I need make it transient?

Can you please elaborate?

Thanks.

**Comment by mganss** [comment]
From the [README](https://github.com/mganss/HtmlSanitizer#thread-safety):
> The `Sanitize()` and `SanitizeDocument()` methods are thread-safe, i.e. you can use these methods on a single shared instance from different threads provided you do not simultaneously set instance or static properties. A typical use case is that you prepare an `HtmlSanitizer` instance once (i.e. set desired properties such as `AllowedTags` etc.) from a single thread, then call `Sanitize()`/`SanitizeDocument()` from multiple threads.

**Comment by fatagun** [comment]
Thanks.
