### ISSUE TITLE
Modify Node Attributes in PostProcessNode Delegate

### ISSUE THREAD

**Issue by jlorek** [mganss/HtmlSanitizer#232]
The normalization of CSS Values done by Angle Sharp (https://github.com/mganss/HtmlSanitizer/issues/154) is a real show stopper for the use of this library in our project, since `rgba()` values are not interpreted correctly in HTML E-Mails by some Mail Clients (eg. Outlook).

As a workaround we try to transform the rgba() values back to #hex values. To only modify style attributes, we tried to modify the attributes in the `PostProcessNode` event, but it seems like they are not accessible at this point. Is there any recommended way doing a post process step like this, without working on the result string produced by `Sanitize()`?

**Comment by mganss** [comment]
It's possible but cumbersome:

```c#
sanitizer.PostProcessNode += (s, e) =>
{
    if (e.Node is IHtmlElement el)
    {
        el.SetAttribute("style", "color: red");
    }
};
```

Though you can also modify the style directly through `el.GetStyle().SetColor("red")` this will be processed by AngleSharp through its CSS parser resulting in rgba() values again (`SetProperty()` doesn't work, either). But perhaps you could at least use the `ICssStyleDeclaration` object returned by `GetStyle` to check if there are color values you need to manipulate and operate on them in isolation from the rest of the CSS declarations. So perhaps:

- Call `GetStyle()`
- Remove color declarations
- Call `ToCss()`
- Append modified color declarations

**Comment by jlorek** [comment]
Thanks a bunch!
Using the callback and operating on the styles directly, this approach now feels more like a legit hack and less like a dirty one :)

**Comment by Zaixer** [comment]
@jlorek do you have the code you used to get around this problem? We have the same problem with rgba in Outlook. Would appreciate seeing your implementation.

**Comment by Zaixer** [comment]
I did this implementation:

`htmlSanitizer.PostProcessDom += (sender, args) => { args.Document.Body.InnerHtml = Regex.Replace(args.Document.Body.InnerHtml, @"rgba\(([0-9]+, [0-9]+, [0-9]+), 1\)", x => $"rgb({x.Groups[1]})"); };`

**Comment by jlorek** [comment]
The implementation may be a bit verbose, but gets the job done and works without issues for a couple of months now.
```
        /// <summary>
        /// All CSS we use that may contain a rgba() value are postfixed (or named) "color".
        /// </summary>
        private static readonly Regex RegexColorRGBA = new Regex(
            @"color:\s*rgba\((?<r>\d+),\s*(?<g>\d+),\s*(?<b>\d+),\s*(?<a>\d+)\)", RegexOptions.Compiled);
...
        // https://github.com/mganss/HtmlSanitizer/issues/154#issuecomment-492680768
        // AngleSharp normalizes CSS values.
        // During this process, CSS color values are re-written to rgba() values.
        // These work in the browser, but do not render properly in Outlook (#hex values do).
        sanitizer.PostProcessNode += (sender, args) =>
        {
            // https://github.com/mganss/HtmlSanitizer/issues/232
            // We cannot use convenience methods like SetColor() or
            // SetProperty() since their values will be again parsed
            // and normalized by AngleSharp
            if (args.Node is IHtmlElement htmlElement)
            {
                ICssStyleDeclaration style = htmlElement.GetStyle();
                string css = style.CssText;
                // only call SetAttribute when we actually have a style to
                // work on - otherwise, this will produce empty inline styles
                if (!string.IsNullOrEmpty(css))
                {
                    string modifiedCss = TryConvertRGBAToHex(css);
                    htmlElement.SetAttribute("style", modifiedCss);
                }
            }
        };
...
        private static string TryConvertRGBAToHex(string css)
        {
            try
            {
                return RegexColorRGBA.Replace(css, match =>
                {
                    int r = int.Parse(match.Groups["r"].Value);
                    int g = int.Parse(match.Groups["g"].Value);
                    int b = int.Parse(match.Groups["b"].Value);
                    return $"color: #{r:x2}{g:x2}{b:x2}";
                });
            }
            catch (System.Exception ex)
            {
                StaticApplicationLogging.CreateLogger<HtmlUtils>().LogError(
                    ex, "Could not transform CSS rgba() to #rgb value in style '{css}'.", css);

                return css;
            }
        }
```
