### ISSUE TITLE
How to sanitize a string with prompt embedded

### ISSUE THREAD

**Issue by leegrindon** [mganss/HtmlSanitizer#233]
How can I sanitize this string to remove the `onmouseover=\"prompt('Please enter your password:')\"` part?
```c#
var foo = "Test\" onmouseover=\"prompt('Please enter your password:')\" aaa=\".pdf";
```

**Comment by mganss** [comment]
There is no need to remove the onmouseover part in your example as it is not an attribute of an HTML element. It would be different if the input string were `<a onmouseover="...">test</a>`.
