### ISSUE TITLE
malformed html causes removing an unallowed attribute to remove whole tag

### ISSUE THREAD

**Issue by The-Nutty** [mganss/HtmlSanitizer#234]
So the best way to explain this is to look at the following html: 
```html
<STYLE>
pre {
white-space: pre-wrap;
}
</STYLE>
<html <META="" http-equiv="Content-Type" content="text/html; charset=US-ASCII"><head><meta http-equiv="Content-Type" content="text/html; charset=us-ascii"><title>abc</Title><style>
<!--
body,html,td,p {top-margin:0; padding:0; font-family:Arial,Helvetica,Geneva,sans-serif;}
-->
</Style></Head><body bgcolor="#FFFFFF">
<p><br>
Some text
<br>
</P>
</Body></Html>
```

So i know its horrid.. But i have to deal with it, using the `sanitizer.RemovingAttribute` I thinks `meta=""` is a attribute that it should remove, and when removing it its removed everything from `<meta=` to `</body>`

Where i would expect it to remove just the `=""` or call the `RemovingTag` event.

**Comment by mganss** [comment]
Are you parsing as a document or fragment (`SanitizeDocument()` vs `Sanitize()`)? In the latter case, only the body contents are returned. `<META` is parsed as an attribute name (the left angle bracket is a [legal character in an attribute name](https://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#attributes-0)).

**Comment by The-Nutty** [comment]
Im using `SanitizeDocument()`. Ok that makes a bit more sense, but then why is it remove the whole rest of the doc as opposed to just the `<META=""` if it is interpreting that as the attribute?

**Comment by mganss** [comment]
I can't repro. I'm getting this:

```html
<html><head>
</head><body bgcolor=""#FFFFFF"">
<p><br>
Some text
<br>
</p>
</body></html>
```

**Comment by The-Nutty** [comment]
Hmm im no longer able to as well, i will try to fix my working example and post it when i can.

**Comment by The-Nutty** [comment]
I have reproduced the issue, this was caused by some malformed html pared by Anglesharp, then html agilitypack then html santizer.
HTML:
```
<html></html><meta="" http-equiv="Content-Type" content="text/html; charset=US-ASCII"><head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii"><title>Oracle Workflow Notification (FYI)</title><style>
</style></head><body bgcolor="#FFFFFF">text here</body></meta="">
```
I am going to try to remove the html agility pack part but im not sure thats going to be posible

**Comment by mganss** [comment]
I don't understand. What is the issue?

**Comment by The-Nutty** [comment]
```
<html></html><meta="" http-equiv="Content-Type" content="text/html; charset=US-ASCII"><head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii"><title>Oracle Workflow Notification (FYI)</title><style>
</style></head><body bgcolor="#FFFFFF">text here</body></meta="">
```
Will be sanitised to 
```
<html><head></head><body bgcolor="#FFFFFF"></body></html>
```

Is the only solution to this to just  add the following on a case by case basis if we need this to work?
```
sanitizer.AllowedTags.Add("meta=\"\"");
```

**Comment by mganss** [comment]
The problem is that the input HTML is broken. It's outside of HtmlSanitizer's scope to fix broken HTML. I'd advise against hacks such as adding `meta=""` to allowed tags. Perhaps add a custom preprocessing step that fixes broken HTML for your specific use cases or try a lib like https://github.com/markbeaton/TidyManaged or https://github.com/martinjw/Tidier.

**Comment by The-Nutty** [comment]
Ok, thanks i might take a look at a custom processor if this happens again.
