### ISSUE TITLE
HtmlSanitizer doesn't sanitize html attribute values

### ISSUE THREAD

**Issue by amodlasalkar-gep** [mganss/HtmlSanitizer#240]
Hi,
I am using HtmlSanitizer library. In one of my case for href I only want to allow links from current domainname,
ex. <a href='https://github.com'>Click Here</a>  --- valid, other than github.com it should remove 'a' tag.

I tried with below code but found not working
sanitizer.RemovingAttribute += (s, e) => e.Cancel = e.Attribute.Name == "href"
&& e.Attribute.Value.StartsWith("https://github.com", StringComparison.OrdinalIgnoreCase);

is it possible by HtmlSanitizer ? Please let me know.

please suggest.

Thanks
Amod

**Comment by mganss** [comment]
Yes, this should work. By default, `href` is an allowed attribute. If you want the event handler to be called, you need to disallow the `href` attribute first by removing it from the collection of allowed attributes:

```c#
sanitizer.AllowedAttributes.Remove("href");
```

**Comment by amodlasalkar-gep** [comment]
indeed, it removed href with by adding suggested Remove("href");

but, with the same condition is it possible to remove 'a' tag than 'href' only?
tried below snippet but not working with conditional tag remove.

sanitizer.AllowedTags.Remove("a");
sanitizer.RemovingTag += (s, e) => e.Cancel = e.Tag.TagName == "a"
&& e.Tag.Attributes["href"].Value.StartsWith("https://github.com", StringComparison.OrdinalIgnoreCase);

**Comment by mganss** [comment]
Yes, this should work. Your best bet is to step inside the event handler with a debugger and compare the condition against the actual values. IIRC the tag name is normalized to upper case. Also, your code breaks if there is no `href` attribute.
