### ISSUE TITLE
System.Text.Encoding.CodePages.dll Is not a dependency

### ISSUE THREAD

**Issue by krptodr** [mganss/HtmlSanitizer#241]
HS does not require a dependency on System.Text.Encoding.CodePages.dll. Please remove the mandatory System.Text.Encoding.CodePages.dll version of 4.7.1 from the NuGet dependency requirements.

 The latest version of AngleSharp is what requires System.Text.Encoding.CodePages.dll and they have the dependency set for 4.5 or greater. However, anything over 4.5 breaks AngelSharp.

**Comment by mganss** [comment]
You're right. Done.
