### ISSUE TITLE
SanitizeDom is not sanitizing the root Body tag element.

### ISSUE THREAD

**Issue by ablakeharris** [mganss/HtmlSanitizer#246]
When calling SanitizeDom with a string input containing a `<body>` tag, the attributes within the body tag are not sanitized due to it being the root element and QuerySelectorAll in DoSanitize not including it.

```
string html = "<body onload=\"alert('test')\"><div>test</div></body>";
HtmlSanitizer testSanitizer = new HtmlSanitizer();
return testSanitizer.SanitizeDom(html).ToHtml();
```
This will return `<html><head></head><body onload="alert('test1')"></body></html>`

The workaround I'm currently using is the other SanitizeDom overload similar to this:

```
string html = "<body onload=\"alert('test')\"><div>test</div></body>";
HtmlSanitizer testSanitizer = new HtmlSanitizer();
IHtmlDocument document = testSanitizer.HtmlParserFactory().ParseDocument(html);
return testSanitizer.SanitizeDom(document).ToHtml();
```

**Comment by tiesont** [comment]
Have you tried using SanitizeDocument(), instead? I'm not sure that Sanitize() or SanitizeDom() were intended to be used with a snippet with body as the root element. Not saying that it isn't a bug, but SanitizeDocument() more or less already does what your work-around seems to do.

**Comment by mganss** [comment]
As @tiesont said, the `SanitizeDom()` methods sanitize only the body (or more specifically the inside of the body). For your use case either `Sanitize()` or `SanitizeDocument()` are better suited, depending on whether the input can include legitimate HTML outside the body (including the body element itself).

**Comment by ablakeharris** [comment]
In this particular scenario I don't want to include HTML outside of the body, but it looks like SanitizeDocument() will work for my use case in a similar way to the workaround I suggested as long as I only return the body.  I logged the issue being under the impression that this would happen with any root level element, but upon further testing found that isn't the case.  For example, this string:  `<div onload=\"alert('test')\"><span>test</span></div>` gets sanitized to this:  `<html><head></head><body><div><span>test</span></div></body></html>` so the issue is definitely a one-off around the body tag.

**Comment by mganss** [comment]
If you're only interested in the body then `Sanitize()` might probably be an even better fit for your use case.
