### ISSUE TITLE
How to add exception to not escape & ?

### ISSUE THREAD

**Issue by shahjay748** [mganss/HtmlSanitizer#247]
I'm trying to use this as asp.net Request filter module for all POST/PUT/DELETE requests, and I don't want to encode "&" as it will break the asp.net web forms application. And I don't think & can cause any harm in HTML.

**Comment by mganss** [comment]
What exactly is breaking the web application?
Perhaps you can try and [replace the formatter](https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex3-replacing-the-default-formatter).

**Comment by shahjay748** [comment]
Asp.net web forms uses & ; and " for it's internal post back and encoding those creates problems.

**Comment by shahjay748** [comment]
@mganss how can I replace that formatter so that & does not get encoded ?

**Comment by mganss** [comment]
Create your own implementation of `IMarkupFormatter` and assign an object of this class to the `OutputFormatter` property. You might want to derive from an existing formatter class, like here: https://github.com/mganss/HtmlSanitizer/blob/61008c6d0e492e641510726da881ee0c9577c305/src/HtmlSanitizer/HtmlFormatter.cs

How does Web Forms use `&` etc in a way that causes problems?

**Comment by shahjay748** [comment]
@mganss e.g. Asp.net web form is posting data as below, where we cannot encode &

FirstName=Jay&LastName=SHAH&Details=<script>alert('xss')</script><div onload="alert('xss')"style="background-color: test"> Hello World !&;"'=$? <img src="test.gif"style="background-image: url(javascript:alert('xss')); margin: 10px"></div>

![image](https://user-images.githubusercontent.com/17333887/100352493-0db09c00-2fbb-11eb-8313-93ebc5d57a91.png)

**Comment by shahjay748** [comment]
@mganss  In Custom OutputFormatter, which method/property should I override to stop the encoding of & ?
Overriding Attribute method is not helping here.

**Comment by mganss** [comment]
I'm confused. What exactly is the input for the sanitizer? Where does the input come from? Please post some demo code.

**Comment by shahjay748** [comment]
@mganss Below is the Input: 
FirstName=Jay&LastName=SHAH&Details=<script>alert('xss')</script><div onload="alert('xss')"style="background-color: test"> Hello World !&;"'=$? <img src="test.gif"style="background-image: url(javascript:alert('xss')); margin: 10px">

**Comment by mganss** [comment]
I think you're applying the sanitization at the wrong level. You should probably get only the value of the `Details` form variable and sanitize that:

```c#
var details = Request.Form["Details"];
details = sanitizer.Sanitize(details);
```

**Comment by shahjay748** [comment]
@mganss Yes, but unfortunately, that's not an option as this is a huge legacy applications and there's re 100s of fields that can have unsafe HTML. So is it possible to sanitize entire request body ?
encoding of & seems the biggest blocker in doing that.

**Comment by shahjay748** [comment]
@mganss It would be a great help if you can suggest any other way in your library to sanitize entire Request body, so we can just plug it in Asp.Net global Request filter without worrying about page/method/field. 
It's fine if we need to add different cases for different content types like application/x-www-form-urlencoded, multipart/form-data, application/json, text/plain, etc.

**Comment by mganss** [comment]
Where are you inserting the filter? Is it this: https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.filter ?

**Comment by shahjay748** [comment]
@mganss Yes, by overriding Read method and applying sanitizer there.

**Comment by mganss** [comment]
How about modifying the `Forms` collection in `Global.asax.cs`?

```c#
void Application_BeginRequest(object sender, EventArgs e)
{
    var form = Request.Form;
    var isReadOnly = form.GetType().GetProperty("IsReadOnly", BindingFlags.NonPublic | BindingFlags.Instance);
    isReadOnly.SetValue(form, false, null);
    form["Name"] = sanitizer.Sanitize(form["Name"]);
    isReadOnly.SetValue(form, true, null);
}
```
