### ISSUE TITLE
Using an opening angle bracket (as a less than symbol) causes data loss

### ISSUE THREAD

**Issue by cecilyth** [mganss/HtmlSanitizer#251]
Using a less than symbol "<" causes the following text to be treated as an html element that gets removed, even if there isn't a closing angle bracket.

Version: we were on 3.4.156, but I just updated to 5.0.355 and get the same results.

Input: `<p>Welcome to Online Registration.</p><p>Sign up <Oct 20th, 2019 to claim a <strong>Discount</strong></p>`

Expected Output: no change (`<p>Welcome to Online Registration.</p><p>Sign up <Oct 20th, 2019 to claim a <strong>Discount</strong></p>` )

Actual Output: `<p>Welcome to Online Registration.</p><p>Sign up </p>`
Actual Output with KeepChildNodes = true: `<p>Welcome to Online Registration.</p><p>Sign up Discount</p>`

Is this expected behaviour? I'm surprised that everything after the "<" is removed, even the `<strong>` tags when KeepChildNodes is set to true.

**Comment by tiesont** [comment]
Well, `<Oct` really should be `< Oct`, or "before Oct", if I'm being honest. Not really sure how AngleSharp would be able to differentiate that you didn't intend to create an element, otherwise.

**Comment by mganss** [comment]
Yes, this is expected behavior, see #91. See https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing for a work around.
