### ISSUE TITLE
when use json format with img tag,the src attribute can't be reserved

### ISSUE THREAD

**Issue by gouhan** [mganss/HtmlSanitizer#252]
For example,the posted data is:
`{
    "is_carousel": 0,
    "content_detail": "<p><img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAgAElEQVR4AdTBjWHjaqIY2SqKPc4/gw1jI9lc/LrFMn4I8AMJSur7ZmzvOf4//+//xyn5gsop5YXyQuSJyoPIE+VBGagMlCM5UtnJE5WRcqRMPuTXRQG9gLIrFJSBgMiJQOVMzASVQZwoJsrkFkHw+8aN/2sUf6niLxV/oXiv4oeK7xQ/VfxAxXvK1QnCBWIms0KRu0IZBXJXRIUyKVYx+6zPG7GLN4onFa+KTTG6ckreUXlH+QnlSOWJjJSByEhlo7yQgcpOnqjslCNlJVwv/rood8qDE2QjOxkoGzmhAkK8EAMZFcouuMHvG/ENIRBiJgQyC+QgZkL8I8q3ioHKmYo3lCfFW8qTYqNypuKJ8qoYKK+KE8qT4oXKGemiHyIzmQmIUCgzWSmFQuwCmSmlMmnC3Wfd4hZHMosXSjFSK95Tit2VV/KOyjvKGeVAeSYj5Uh5UEYqD8qRDFR2cqBypAyU3fXix8UrT0RGyi7uApV3VM4pz+QLn/AnPmMi35OZ3MmdPJM7 \"></p>",
    "view_count": 0,
    "create_time": "2020-12-10 10:44:29"
}`
after received the data in the api server,the `"` transfered to `\"`,and the `\` transfered to `\\`,so the value before Sanitize called is:
`"{\"content_detail\": \"<p><img src=\\\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAgAElEQVR4AdTBjWHjaqIY2SqKPc4/gw1jI9lc/LrFMn4I8AMJSur7ZmzvOf4//+//xyn5gsop5YXyQuSJyoPIE+VBGagMlCM5UtnJE5WRcqRMPuTXRQG9gLIrFJSBgMiJQOVMzASVQZwoJsrkFkHw+8aN/2sUf6niLxV/oXiv4oeK7xQ/VfxAxXvK1QnCBWIms0KRu0IZBXJXRIUyKVYx+6zPG7GLN4onFa+KTTG6ckreUXlH+QnlSOWJjJSByEhlo7yQgcpOnqjslCNlJVwv/rood8qDE2QjOxkoGzmhAkK8EAMZFcouuMHvG/ENIRBiJgQyC+QgZkL8I8q3ioHKmYo3lCfFW8qTYqNypuKJ8qoYKK+KE8qT4oXKGemiHyIzmQmIUCgzWSmFQuwCmSmlMmnC3Wfd4hZHMosXSjFSK95Tit2VV/KOyjvKGeVAeSYj5Uh5UEYqD8qRDFR2cqBypAyU3fXix8UrT0RGyi7uApV3VM4pz+QLn/AnPmMi35OZ3MmdPJM7\\\" ></p>\"}"`。
i get `{"content_detail": "<p><img></p>"}` finally. the src attribute value can not be saved.
Is there any work around to it?
Thanks.

**Comment by mganss** [comment]
Are you passing the whole JSON string into the call to `Sanitize()`? If so, you need to deserialize the JSON first, then pass only the HTML, i.e. the value of the `content_detail` key into `Sanitize()`. Also, you need to add `data` to the set of allowed schemes if you want to preserve the `src` attribute.

```c#
class Data
{
    public string content_detail { get; set; }
}

var data = JsonSerializer.Deserialize<Data>("{\"content_detail\": \"<p><img src=\\\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAgAElEQVR4AdTBjWHjaqIY2SqKPc4/gw1jI9lc/LrFMn4I8AMJSur7ZmzvOf4//+//xyn5gsop5YXyQuSJyoPIE+VBGagMlCM5UtnJE5WRcqRMPuTXRQG9gLIrFJSBgMiJQOVMzASVQZwoJsrkFkHw+8aN/2sUf6niLxV/oXiv4oeK7xQ/VfxAxXvK1QnCBWIms0KRu0IZBXJXRIUyKVYx+6zPG7GLN4onFa+KTTG6ckreUXlH+QnlSOWJjJSByEhlo7yQgcpOnqjslCNlJVwv/rood8qDE2QjOxkoGzmhAkK8EAMZFcouuMHvG/ENIRBiJgQyC+QgZkL8I8q3ioHKmYo3lCfFW8qTYqNypuKJ8qoYKK+KE8qT4oXKGemiHyIzmQmIUCgzWSmFQuwCmSmlMmnC3Wfd4hZHMosXSjFSK95Tit2VV/KOyjvKGeVAeSYj5Uh5UEYqD8qRDFR2cqBypAyU3fXix8UrT0RGyi7uApV3VM4pz+QLn/AnPmMi35OZ3MmdPJM7\\\" ></p>\"}");
var sanitizer = new HtmlSanitizer();
sanitizer.AllowedSchemes.Add("data");
var sanitized = sanitizer.Sanitize(data.content_detail);
```
