### ISSUE TITLE
Head Tag

### ISSUE THREAD

**Issue by mrkmrc34** [mganss/HtmlSanitizer#253]
Hello,

When I sanitize with the following line of code, the style tags in the head tag appear inside the body tag. Is this a problem? As far know the style tag can be inside the head tag. Can you help me?

**Comment by mganss** [comment]
I can't repro. Here's a fiddle: https://dotnetfiddle.net/BRweqZ

**Comment by mrkmrc34** [comment]
> I can't repro. Here's a fiddle: https://dotnetfiddle.net/BRweqZ

Thank you for help.

**Comment by mrkmrc34** [comment]
Hello,

When I sanitize an html file with encoding type utf-8 BOM the style tags in the head tag appear inside the body tag. How i this fix?

**Comment by mganss** [comment]
Can you attach a demo file?

**Comment by mrkmrc34** [comment]
[UTF8BOM.txt](https://github.com/mganss/HtmlSanitizer/files/5741525/UTF8BOM.txt)

Hi,

Attached.

**Comment by mganss** [comment]
If the string you're sanitizing contains the BOM the HTML parser won't parse the input correctly. You'll need to make sure the input string is read correctly. This can be achieved by using a string reading method that can detect the presence of a BOM, e.g. `File.ReadAllText()` or `StreamReader`.
