### ISSUE TITLE
Changelog 

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#26]
Hi,!

I saw there is a new release on nuget. Is there a changelog of the new release(s)?

**Comment by mganss** [comment]
Unfortunately, no. The latest change was the addition of a post processing hook (`PostProcessNode`).

**Comment by 304NotModified** [comment]
I think the changelog of the Github releases is sufficient (https://github.com/mganss/HtmlSanitizer/releases)
