### ISSUE TITLE
Incorrect removal of parenthesis in calc

### ISSUE THREAD

**Issue by lupuconst** [mganss/HtmlSanitizer#263]
calc((100% - 300px)/2)   is wrong transformed in calc(100% - 300px/2)

**Comment by mganss** [comment]
AFAICT the syntax for `calc()` doesn't allow parenthesized expressions: https://drafts.csswg.org/css-values-3/#calc-notation
You can use nested `calc()` expressions, though.

**Comment by mganss** [comment]
OTOH it seems parentheses are indeed supported: https://developer.mozilla.org/en-US/docs/Web/CSS/calc()#syntax
>  You may also use parentheses to establish computation order when needed.

In practice both Chrome and Firefox take parentheses into account when performing the calculation. I'll investigate more.

**Comment by lupuconst** [comment]
Yes. Thank you for info. The display of html was affected after sanitization. It will be great to have a fix
