### ISSUE TITLE
4.x packages no longer available on nuget.org

### ISSUE THREAD

**Issue by omarpiani** [mganss/HtmlSanitizer#267]
Hi, what's happened?! to 4.x nuget packages? 

![image](https://user-images.githubusercontent.com/2690653/112471065-bb666880-8d6b-11eb-9ae8-974a7c428e8c.png)

did you deleted/delisted that?

**Comment by mganss** [comment]
Yes, I delisted them because of https://github.com/mganss/HtmlSanitizer/security/advisories/GHSA-8j9v-h2vp-2hhv.

**Comment by omarpiani** [comment]
ok, tnx.. its still a bit strange :octocat:

**Comment by mganss** [comment]
@omarpiani Honestly, I didn't consider delisting them until I got a message from NuGet. But IMO it totally makes sense as I wouldn't want a user to install a package with a known vulnerability.
