### ISSUE TITLE
How to remove href attribute from only anchor tag? (Question)

### ISSUE THREAD

**Issue by danish937** [mganss/HtmlSanitizer#268]
I have been trying this, but this seems not to be working : **sanitizer.RemovingAttribute += (s, e) => e.Cancel = (e.Tag.NodeName.Equals("a"));**

**Comment by mganss** [comment]
`Cancel` needs to be set to true if the attribute should *not* be removed (i.e. the removal should be cancelled). Thus:

```c#
sanitizer.RemovingAttribute += (s, e) => e.Cancel = e.Attribute.Name != "href" || !(e.Tag.NodeName.Equals("a"));
```

Watch out for upper/lower case, not sure if the names are normalized to lowercase.

**Comment by danish937** [comment]
Hi, 

The code snippet is not working. I suppose I have a content like follows, I need the href attribute of the anchor (<a>) tag to be intact while the href attribute be removed from other tags during sanitization;

"<html><head></head><body><div><div>< font face =\"Arial, Helvetica, sans-serif\" size=\"2\"><meta content=\"text/html; charset=windows-1252\" http-equiv=\"Content-Type\"><meta name=\"GENERATOR\" content=\"MSHTML 11.00.10570.1001\"><div><img border=\"0\" hspace=\"0\" alt=\"\" src=\"cid:index.png-1616758903\" align=\"baseline\" attachmentidcr=\"2\"></div></font><br><div id=\"originalMessage\">Powered by CampusNexus CRM.</div></div> <a value=\"something\" href=\"https://something.com\"/> <span href=\"something\" ></span></div></body></html>" 

When I use your code snippet, the value of href is being retained for all the tags.

**Comment by danish937** [comment]
Thanks a lot @mganss, this is working, I was looking at the solution inverted.
