### ISSUE TITLE
Sanitize url containing []

### ISSUE THREAD

**Issue by fanmusic** [mganss/HtmlSanitizer#27]
Hi @mganss 

I'm using your library HtmlSanitizer in my website. It works very well. This week we got a problem that the HtmlSanitizer() remove an image url from photobucket.
Input: <code>&lt;a href=&quot;http://media.photobucket.com/user/jade95_2010/media/PHOTOGRAPHY-VARIED/cat-face.jpg.html?filters[term]=cat&amp;filters[primary]=images&amp;filters[featured_media]=1220&amp;filters[secondary]=videos&amp;sort=1&amp;o=2&quot; target=&quot;&quot;&gt;text&lt;/a&gt;. </code>
Output: <code>&lt;a target&gt;text&lt;/a&gt;</code>

The image url doesn't pass this check uri.IsWellFormedOriginalString(). Can you explain why we treat this url unsafe? Is there any security concern?

Thanks.

**Comment by mganss** [comment]
The square brackets make the URL invalid according to RFC 3986. Although there's no specific security concern with invalid URLs in general, at least not when it's a http URL, my original approach was to just throw out all invalid URLs.

I'll change this to a more relaxed handling by escaping invalid URLs through [Uri.GetComponents](https://msdn.microsoft.com/en-us/library/system.uri.getcomponents.aspx).
