### ISSUE TITLE
Add option to escape unknown tags instead of removing

### ISSUE THREAD

**Issue by PFight** [mganss/HtmlSanitizer#273]
Hi,

HtmlSanitizer hardly remove all data, that it doesn't know. Sometime it produces losing of some user data. For example, if user write some text like "When X<Y and Y>4 do something" we are getting "When X" in output. 

It is not acceptable for some usecases, and would be great to have setting - to replace unknown html tags to escaped sequences. For example, when we have input `<blabla>` produce `&lt;blabla&gt;` instead of cutting out whole text enty.

**Comment by mganss** [comment]
See this example: https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing
