### ISSUE TITLE
Mailto gets stripped

### ISSUE THREAD

**Issue by PdeJong-CCI** [mganss/HtmlSanitizer#28]
Hi,

Mailto gets stripped. Is there a way to allow this?

Example:
Input: `<a href="mailto:contact@me.please">Contact me!</a>`
Output: `<a>Contact me!</a>`

Kind regards,
Paul.

**Comment by mganss** [comment]
The URI schemes allowed by default are "http" and "https". You can add "mailto" like this e.g.:
```C#
var sanitizer = new HtmlSanitizer { AllowedSchemes = { "mailto" } };
```

**Comment by PdeJong-CCI** [comment]
Thanks!
