### ISSUE TITLE
Unexpected remove of style

### ISSUE THREAD

**Issue by eric-methorst** [mganss/HtmlSanitizer#285]
Input source is the string: "&lt;span style=&quot;background:#ccffff&quot;&gt;"
What happens is in HtmlSanitizer.SanitizeStyle line 864: var styles = element.GetStyle();
this returns all *possible* styles, not the ones just set
1) these styles should probably be filtered on style.RawValue != AngleSharp.Css.Values.CssInitialValue
but more importantly
2) the styles contain background-position-x and background-position-y. These are not in the default AllowedCSSProperties (only background-position) so we get an unexpected OnRemove. It is now being fixed by adding:
sn.AllowedCssProperties.Add("background-position-x");
sn.AllowedCssProperties.Add("background-position-y");
But I think it should be part of the Default.

**Comment by eric-methorst** [comment]
input string seems to have been sanitized. Was: &lt;span style=&quot;background:#ccffff&quot;&gt;

**Comment by mganss** [comment]
1. This is because AngleSharp.Css expands shorthand properties to longhands (see #178 and also https://github.com/AngleSharp/AngleSharp.Css/issues/9). Filtering all `initial` values would also filter out those that are present in the input, i.e. where the input contains e.g. `<span style="color: initial">` and not only those that are byproducts of AngleSharp's expansion of shorthands.

2. You're right. We've had a similar case in #243 and I seem to have missed `background-position` 🙄

**Comment by mganss** [comment]
> input string seems to have been sanitized. Was: <span style="background:#ccffff">

You can use [code syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to avoid this.

**Comment by eric-methorst** [comment]
Hi,


  1.  We kind of figured that AngleSharp expansion bit. However, what we noticed is that it expands all associated styles. In the tag <span style="background:#ccffff"> all we do is setting the background colour. You can see that in the style (which has a property Declarations. As you can see in the debugger:

***@***.***D75D45.50E4D6A0]

All declarations have the value set to initial, except for the last one, which is background-color. My point was that you are checking *all* 10 styles for validity, while only 1 style is actually being set, all the others have the value “initial’ and the RawValue CssIniailValue, and the Boolean value IsInitial set to true (hadn’t noticed that one earlier).

This is easily fixed on line 867 by doing something like:
SanitizeStyleDeclaration(element, styles.Where(s => ! s.IsInitial), baseUrl);



  1.  Yes, we actually pasted those 2 options in your code on line 270 and it was fine
            "background-position",

            "background-position-x",

            "background-position-y",


Kind regards, Eric

**Comment by mganss** [comment]
In `<span style="background: red">x</span>` you not only set `background-color` but all the other `background` properties as well (to their default values). In other words, it's as if you had also specified `background-position-x: initial` etc etc. See https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties
