### ISSUE TITLE
Jackson94 is being returned with sanitized string.

### ISSUE THREAD

**Issue by RickBlacker** [mganss/HtmlSanitizer#288]
We are using HtmlSanitizer **Version 5.0.404**.
Right out of the box, no config changes or code changes.  However, after calling Sanitize, we are seeing the string "Jackson94" being prepended to the sanitized string result.  Was hoping to get some guidance on this.  For now, we have a hack in place to manually check the string and pull off "Jackson94".  

Here is the original test string we were using.
```c#
"<table style=\"width:100%\">\n\n <tr>\n\n <th>Firstname</th>\n\n <th>Lastname</th>\n\n <th>Age</th>\n\n </tr\n\n <tr>\n\n <td>Jill</td>\n\n <td>Smith</td>\n\n <td>50</td>\n\n </tr>\n\n <tr>\n\n <td>Eve</td\n\n <td>Jackson</td\n\n <td>94</td\n\n </tr>\n\n</table"
```
Here is the code snippet. 
![CodeSnippet](https://user-images.githubusercontent.com/6207302/121753599-8bf00e00-cac7-11eb-90ea-7edd8650224e.png)

Original String when inspecting it in the debugger as text.
![OriginalString](https://user-images.githubusercontent.com/6207302/121753621-990cfd00-cac7-11eb-870a-2e488ab347c3.png)

What the string looks like immediatly after calling Sanitize( htmlStr )
![SanitizedString](https://user-images.githubusercontent.com/6207302/121753646-a629ec00-cac7-11eb-8732-149280ee5c15.png)

**Comment by mganss** [comment]
This occurs because the corresponding `td` tags are not properly closed: `</td`
You'll get the same result if you use the original string in a browser.
