### ISSUE TITLE
input string gets wrongly sanitized

### ISSUE THREAD

**Issue by eric-methorst** [mganss/HtmlSanitizer#293]
I don't know if this library was designed to handle this but we tried to feed it a json string containing html and it sanitizes it the wrong way. The input string was:
{&quot;context&quot;: &quot;&lt;h3 style=\\&quot;padding: 18px; top: 0;position: relative;\\&quot;&gt;A) ALGEMEEN (ALLE MATERIEEL) &lt;/h3&gt;\n&quot;}
Running the code is see that the problem arises in anglesharp which after parsing it into a DOM turns the string into
&lt;h3 style=&quot;\&amp;quot;padding:&quot; 18px;=&quot;&quot; top:=&quot;&quot; 0;position:=&quot;&quot; relative;\&quot;=&quot;&quot;&gt;A) ALGEMEEN (ALLE MATERIEEL) &lt;/h3&gt;

note it replaced the \\" by &amp;quot; and added the = at the end of the style section
I attached a file in case the Html encoding doesn't work
[Input.txt](https://github.com/mganss/HtmlSanitizer/files/6664098/Input.txt)
Is there a way around this?

also, position does not seem to be in the Css Whitelist

**Comment by mganss** [comment]
HtmlSanitizer is not designed to sanitize formats other than HTML. For your use case it's probably best to parse the JSON first, then sanitize only the value of the `context` key.

**Comment by eric-methorst** [comment]
Unfortunately, this happens during json deserialisation.
But I understand that this is not what is was designed to to.
