### ISSUE TITLE
Release for AngleSharp 0.16.0

### ISSUE THREAD

**Issue by ronaldkroon** [mganss/HtmlSanitizer#297]
AngleSharp 0.16.0 has been released, but the latest version of HtmlSanitizer depends on the previous version of AngleSharp (0.15.0).
I see the references have been updated on `master`, so I guess it's just a matter of releasing a new version.

**Comment by mganss** [comment]
You're right. The current prerelease versions (6.0.*) depend on AngleSharp 0.16.0. I'll make a stable release later today.

**Comment by mganss** [comment]
Version 6.0.437 has been released.
