### ISSUE TITLE
Self-closing nested tags are processing incorrectly for some cases

### ISSUE THREAD

**Issue by mnikolaev83** [mganss/HtmlSanitizer#302]
Hi there!
For some nested cases `<span />` and `<div />` are processed incorrectly by the `HtmlSanitizer`.

The example is below:

```
var sampleHtml = "<span /><span>Some Text</span>";
var sanitizer = new HtmlSanitizer();
Console.WriteLine($"HTML to parse: \n{sampleHtml}");
Console.WriteLine($"Expected result is: \n<span /><span>Some Text</span> \nor \n<span></span><span>Some Text</span>");
Console.WriteLine($"But actually it is:");
Console.WriteLine(sanitizer.Sanitize(sampleHtml, string.Empty, XhtmlMarkupFormatter.Instance));
```

The result is:

```
HTML to parse:
<span /><span>Some Text</span>
Expected result is:
<span /><span>Some Text</span>
or
<span></span><span>Some Text</span>
But actually it is:
<span><span>Some Text</span></span>
```

The same occurs with `<div>` nesting.

Could you please resolve it in some future releases?

With the best wishes,
Max Nikolaev

**Comment by mganss** [comment]
This behavior is expected. It's the way the HTML parser works. It works the same in a browser:

```js
var e = document.createElement("div");
e.innerHTML = "<span /><span>Some Text</span>";
e.innerHTML // -> "<span><span>Some Text</span></span>"
```

**Comment by mnikolaev83** [comment]
> This behavior is expected. It's the way the HTML parser works. It works the same in a browser:
> 
> ```js
> var e = document.createElement("div");
> e.innerHTML = "<span /><span>Some Text</span>";
> e.innerHTML // -> "<span><span>Some Text</span></span>"
> ```

Gotcha. Thank you!
