### ISSUE TITLE
Please push a release with AngleSharp v0.16.1

### ISSUE THREAD

**Issue by r-Larch** [mganss/HtmlSanitizer#306]
Please push a release with AngleSharp v0.16.1

I use [PreMailer.Net](https://www.nuget.org/packages/PreMailer.Net) and it uses AngleSharp v0.16.1, so I get the following warning:
```
warning NU1608: Detected package version outside of dependency constraint: 
  HtmlSanitizer 6.0.441 requires AngleSharp (= 0.16.0) but version AngleSharp 0.16.1 was resolved.
```

**Comment by mganss** [comment]
✅ Released 6.0.453.
