### ISSUE TITLE
When you set IsStrictMode to true, sanitize function throws exception

### ISSUE THREAD

**Issue by admirpajalic** [mganss/HtmlSanitizer#307]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of HtmlSanitizer?
- [x] Did you perform a search in the issues?

## Description

I've turned on **IsStrictMode** on html parser to restrict what can be sent to me (don't want ill html). On the first test case, exception is thrown on HtmlSanitizer.Sanitize() =>AngleSharp.Html.Parser.HtmlParseException : Error while parsing the provided HTML document. 

Test case:

`This text is <a href=\"https://example.com\"><b><i><u><strike><font color=\"#ffffff\">allowed</font></strike></u></i></b></a>.`

At first this was wired to me that AngleSharp is throwing exception for valid piece of html. Digging deeper into HtmlSanitizer I've found line 586: **var dom = parser.ParseDocument("&lt;html&gt;&lt;body&gt;" + html);** so decided to test it with AngleSharp alone just to verify that issue is not with HtmlSanitizer.

Test case:

```csharp
var parser = new HtmlParser(new HtmlParserOptions { IsStrictMode = true });
// notice  <!doctype html><html><body>  vs  <html><body>
var result = parser.ParseDocument("<!doctype html><html><body>This text is <a href=\"https://example.com\"><b><i><u><strike><font color=\"#ffffff\">allowed</font></strike></u></i></b></a>.");
```

This passed without problems. To me this seems to be bug with IsStrictMode enabled on this library.

## Steps to Reproduce

1. Test case with one node (strict mode)

```csharp
public void OneNodeStrictModeTest()
{
  var html = @"<p>Paragraph</p>";
  var s = new HtmlSanitizer { HtmlParserFactory = () => new HtmlParser(new HtmlParserOptions { IsStrictMode = true }) };
  var sanitized = s.Sanitize(html);
  Assert.Equal("<p>Paragraph</p>", sanitized);
}
```

**Expected behavior:** Expected test to pass

**Actual behavior:** Error is thrown: AngleSharp.Html.Parser.HtmlParseException : Error while parsing the provided HTML document

**Environment details:** Win10, DOTNET5

## Possible Solution

For this issue simple solution would be to add valid html doctype on start in line 586, file HtmlSanitizer.cs: 

```csharp
var dom = parser.ParseDocument("<!doctype html><html><body>" + html); 
```

and add test case to cover strict mode:

```csharp
[Fact]
public void Number307StrictModeValidHtmlTest()
{
  // see https://github.com/mganss/HtmlSanitizer/issues/307
  var html = @"<div>This is <p>Paragraph</p></div>";
  var s = new HtmlSanitizer { HtmlParserFactory = () => new HtmlParser(new HtmlParserOptions { IsStrictMode = true }) };
  var sanitized = s.Sanitize(html);
  Assert.Equal("<div>This is <p>Paragraph</p></div>", sanitized);
}

[Fact]
public void Number307StrictModeValidHtmlTest()
{
  // see https://github.com/mganss/HtmlSanitizer/issues/307
  var html = @"<div>This is <p>Paragraph/div>";
  var s = new HtmlSanitizer { HtmlParserFactory = () => new HtmlParser(new HtmlParserOptions { IsStrictMode = true }) };
  Assert.Throws<HtmlParseException>(() => s.Sanitize(html));
}
```

This is just proposal, I'm not familiar with all supported things with this library. Adding this change would not break anything on tests (at least what I've tested).

**Comment by mganss** [comment]
Thanks for the report and the thorough investigation. Could you make a PR with the proposed changes?

**Comment by admirpajalic** [comment]
Done, you can review it.
