### ISSUE TITLE
CSS3 properties missing in DefaultAllowedCssProperties

### ISSUE THREAD

**Issue by benoit-lefebvre** [mganss/HtmlSanitizer#315]
Hello,

A lot of CSS3 properties are missing in the `DefaultAllowedCssProperties` property, as you can see in the image below. On the left side are the official CSS3 property list, on the right side the sanitizer default allowed css properties :

![d1ac357d-8cb4-42f1-9e37-e46f2dfbe4c6](https://user-images.githubusercontent.com/50300942/142594051-d79fad42-75d3-41a3-a2da-21d5a8e5200c.png)

I know that missing properties can be added to the `AllowedCssProperties` property:

```
sanitizer.AllowedCssProperties.Add("transform");
sanitizer.AllowedCssProperties.Add("border-radius");
...
```

Is there any reason not to add these missing properties to the sanitizer default allowed properties ?

**Comment by mganss** [comment]
There is no reason, except backwards compatibility. Could you make a PR to add these?
