### ISSUE TITLE
background-position style attribute are being stripped

### ISSUE THREAD

**Issue by bfischcsod** [mganss/HtmlSanitizer#317]
The following example resulted in having its style attribute stripped:

- `<span style="background-position: top;"></span>`

**Comment by tiesont** [comment]
That's not what I'm seeing: https://dotnetfiddle.net/74EIKh

**Comment by bfischcsod** [comment]
Thanks @tiesont,  I think the issue may have been resolved already.  The online demo appears to use an older version
![image](https://user-images.githubusercontent.com/72379033/143328387-bd218096-e459-4305-aaab-1b0b62a14063.png)
