### ISSUE TITLE
How to consider non-HTML tags like <nothtml> as normal text within HtmlSanitizer?

### ISSUE THREAD

**Issue by raghuvtg** [mganss/HtmlSanitizer#318]
If the HTML text is like
![image](https://user-images.githubusercontent.com/94917372/144595322-5bf6e5c1-857f-4af2-b4cb-8c076524f838.png)

When tried to cancel the Remove Tag action, an end tag is being created for the same.

How to prevent that with getting a closed tag for it?

**Comment by mganss** [comment]
See https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing
