### ISSUE TITLE
How to prevent sanitizer from converting < and > to &lt; and &gt;

### ISSUE THREAD

**Issue by Prajwal-Jadhav** [mganss/HtmlSanitizer#319]
Basically users post Mathjax/Latex equations from the form and I am sanitizing this form value. But HtmlSanitizer keeps changing "<" and ">" to `&lt;` and `&gt;` respectively. 

These values are in the middle of the equation so it completely messes up the rendering of Mathjax. Mathjax requires symbols as they are instead of their html representation.

What should I do to prevent this from happening?

**Comment by Prajwal-Jadhav** [comment]
Nevermind, the problem was because of another library.

**Comment by tiesont** [comment]
To actually answer your question, https://github.com/mganss/HtmlSanitizer/wiki/Frequently-Asked-Questions#can-i-sanitize-markup-other-than-html-see-eg-91-103-like-xml-or-mathml and https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing

Basically, anything that _looks_ like HTML (even if it's not) is assumed to be by AngleSharp, the library used to parse and format HTML.
