### ISSUE TITLE
How to sanitize an url ?

### ISSUE THREAD

**Issue by MarcosCostaDev** [mganss/HtmlSanitizer#320]
Hello Everyone,

Is there a way for sanitizing the URL from a redirection using this tool?

Example:

The user can update the URL request to `http://localhost/page.aspx?fieldju%27*eval%28%22ale%22%2B%22rt%22%2B%22%28%222674%22%29%22%29%2B%27ju`.

Note: there is a javascript keyword `eval`, but this could be any other keyword.

**Comment by mganss** [comment]
Please provide more context to your issue. What's the input to the sanitizer and what are you expecting as output?

**Comment by MarcosCostaDev** [comment]
Hello @mganss, 

First, congratulation on your creation, it is an excellent library for helping us with security concerns.

As you know, there are many ways to inject some script into the application, and one of them is through an URL. In the scenarios that I described here. In the example, the URL has injectable splot that will be processed in javascript on the target page. If we decode the URL, you will have `http://localhost/page.aspx?fieldju'*eval("ale"+"rt"+"("2674")")+'ju`, for removing this, I would spect something like this `http://localhost/page.aspx?fieldju`.

**Comment by mganss** [comment]
I don't understand where exactly the XSS potential is in your example. What does the surrounding HTML that you are sanitizing look like and how does the JavaScript get executed?

**Comment by MarcosCostaDev** [comment]
@mganss maybe it is not within your library scope. I solve that with `regex` by gathering the javascript keywords and compare with the URL.
