### ISSUE TITLE
text-shadow is sanitited in a way where you cannot specify a colour

### ISSUE THREAD

**Issue by pingu2k4** [mganss/HtmlSanitizer#321]
`... style="text-shadow: 2px 2px 2px #000" ...`
The above example is cut off and the colour at the end is removed. If you remove the third "2px" part, then the colour is kept. It seems to only ever expect a maximum of 3 parts to a text shadow, and the 4th will be cut.

**Comment by pingu2k4** [comment]
Apologies, I mis-spoke. You cannot specify a colour regardless.

**Comment by mganss** [comment]
This seems to occur only if the color is (opaque) black. I've opened a corresponding issue at Angelsharp.Css: https://github.com/AngleSharp/AngleSharp.Css/issues/97

**Comment by pingu2k4** [comment]
Ahh I see, makes sense. Thanks.

**Comment by mganss** [comment]
This is by design (see discussion at AngleSharp/AngleSharp.Css#97).
