### ISSUE TITLE
background-image css attribute in inline style tags shows &quot in url

### ISSUE THREAD

**Issue by pragatibaheti** [mganss/HtmlSanitizer#323]
```<div style="background-image:url(https://url.com/xyz.jpg);"> hello </div> is sanitized to <div style="background-image: url(&quot;https://url.com/xyz.jpg&quot;)">hello </div>```

Is this expected?

**Comment by mganss** [comment]
Yes, see #146

**Comment by pragatibaheti** [comment]
Do we need to process the output to convert the &quot; to "?

**Comment by mganss** [comment]
No, `&quot;` is syntactically correct HTML.

**Comment by pragatibaheti** [comment]
But this wouldn't render correctly. So for that would we need to fix this cosmetic issue specific to this case? I am kinda confused

**Comment by mganss** [comment]
Why wouldn't it render correctly?

**Comment by pragatibaheti** [comment]
It does. Sorry my bad
