### ISSUE TITLE
Src attribute in image tag

### ISSUE THREAD

**Issue by pragatibaheti** [mganss/HtmlSanitizer#324]
Here is an example of XSS attack from OWASP cheat sheet ```<IMG SRC=   onmouseover="alert('xxs')">``` where no url/path in src attribute signifies null. When we sanitize this we get this ``` <img src="onmouseover=&quot;alert('xxs')&quot;"> ``` while expected should be ``` <IMG /> ```. Is this expected?

**Comment by mganss** [comment]
Yes, this is expected. The `src` attribute is allowed by default. The resulting value of the `src` attribute is a relative URL.
