### ISSUE TITLE
Margin as CSS property strips unnecessary values

### ISSUE THREAD

**Issue by pragatibaheti** [mganss/HtmlSanitizer#328]
Here is a code snippet:
```
<style>
div{margin:24px}
p{margin: inherit}
</style>
```
should return the same value. But the sanitized output is 
```
<style>div { margin: 24px }
p { }</style>
```
Margin has an allowable value "inherit". The same goes for another CSS property - padding. Then what can be the reason for it being stripped?

**Comment by mganss** [comment]
This seems to be an issue within AngleSharp.Css. I've submitted an issue here: https://github.com/AngleSharp/AngleSharp.Css/issues/100

**Comment by mganss** [comment]
This has been fixed in AngleSharp.Css 0.17.0.
