### ISSUE TITLE
Some property values are removed when sanitized

### ISSUE THREAD

**Issue by pragatibaheti** [mganss/HtmlSanitizer#329]
I have explored and have some open items that show wrong results (valid values are removed). Here is a short point-wise summary:
1.  background-image: conical-gradient(color,color,color) 
```
<style>       
 #grad 
{
background-image: conic-gradient(red, yellow, green);
 }
</style>
```

sanitized to 
```
<style> #grad{} </style>
```
Reference: https://www.w3schools.com/css/css3_gradients_conic.asp

2. transform: skew(20deg)
```
<style>       
 #grad 
{
 transform : skew(20deg);
}
</style>
```
sanitized to 
```
<style> #grad{} </style>
```
Reference: https://www.w3schools.com/css/css3_2dtransforms.asp

Seems like a bug. Can you confirm?

**Comment by mganss** [comment]
I have opened an issue with AngleSharp.Css: https://github.com/AngleSharp/AngleSharp.Css/issues/101

`skew` works if you specify both axes, e.g. `transform: skew(20deg, 15deg);`

**Comment by glen-84** [comment]
@mganss This can probably be closed now? (https://github.com/AngleSharp/AngleSharp.Css/releases/tag/v0.17.0)

**Comment by mganss** [comment]
Resolved in AngleSharp.Css 0.17.0 and thus HtmlSanitizer 8.0.638.
