### ISSUE TITLE
CSS styles stripping rgb when capitalized

### ISSUE THREAD

**Issue by cnoblests** [mganss/HtmlSanitizer#340]
I wasn't sure if this is an issue with the sanitizer or with AngleSharp, but since I'm experiencing it via your library, I figured it would be better to open this here. If you have an inline style on a node with an RGB or(RGBA) color defined, and RGB or RGBA are capitalized, the style is stripped.

For an example, see here: [https://dotnetfiddle.net/Mbf1RY](https://dotnetfiddle.net/Mbf1RY)

**Comment by mganss** [comment]
This is indeed an issue within AngleSharp.CSS. I've reported it here: https://github.com/AngleSharp/AngleSharp.Css/issues/109

**Comment by mganss** [comment]
This has been fixed in AngleSharp.Css 0.17.0.
