### ISSUE TITLE
Issue with input <svg onload=alert(111)/>

### ISSUE THREAD

**Issue by samrules** [mganss/HtmlSanitizer#36]
Hi,

I am using your HtmlSanitizer and it works great. But I found an issue with one kind of input.

html = 1<svg onload=alert(111)/>

When I give this input it just does not give response, 

but when I give encode input

html = 1<svg%20onload=alert(111)/>

![inputs](https://cloud.githubusercontent.com/assets/973258/8650778/8d956822-2992-11e5-9811-16cb3d26c55c.PNG)

it works great. 

Edit: Since issue editor was not allowing my inputs (thinking its an injection.) So, I have uploaded an image to show you my inputs.

**Comment by mganss** [comment]
Bizarre. This is an issue with CsQuery. None of these result in a hang:

```HTML
<div x=y/>
<svg x=y />
<svg x="y"/>
<xyz x=y/>
```

This does:

```HTML
<svg x=y/>
```

I'll open an issue in CsQuery, although I'm afraid this might not get fixed because CsQuery is abandoned (see #34).

**Comment by samrules** [comment]
Agreed, this is CsQuery bug. I was digging into it further and found that bug was indeed in CsQuery. CsQuery goes into infinite loop for this input.

For the time being I have fixed that bug for my code base :)

**Comment by mganss** [comment]
Opened jamietre/CsQuery#194

**Comment by 304NotModified** [comment]
This is a security hole? I think we should work around csquery for this.

**Comment by mganss** [comment]
Definitely DOS potential here. I tried to track down the problem in CsQuery. The hang occurs here: https://github.com/jamietre/HtmlParserSharp/blob/862e09cabdb6ebf75bb9556f07b1660a0902c882/HtmlParserSharp/Core/TreeBuilder.cs#L1163-L1167

I didn't get any further, though. Can you see what's going on there?

**Comment by mganss** [comment]
The original validator.nu HTML parser code had a `break eofloop;` there (up until Aug 14, 2013 when they added features and ripped that whole part out):
https://github.com/validator/htmlparser/blob/8417f703507931965b19e9540229ad6c56bb448d/src/nu/validator/htmlparser/impl/TreeBuilder.java#L1357

That would translate into `goto breakEofloop;` instead of `goto continueEofloop;`

Not sure how to proceed now since both CsQuery and HtmlParserSharp seem to be abandoned :confused:

**Comment by samrules** [comment]
I am not sure if it is a good fix or not. 
The way i fixed it was by replacing `goto continueEofloop;` with `goto breakEofloop;`

**Comment by mganss** [comment]
I'll make a PR to https://github.com/jamietre/HtmlParserSharp

**Comment by dmeagor** [comment]
I've included htmlsanitizer with nuget, what do I have to do to get the fix you pushed to htmlparsersharp added to our project?  Do we need to ditch nuget and download and install manually from github?

**Comment by mganss** [comment]
I've asked @jamietre to make a new NuGet release of CsQuery. Currently, you'd have to build CsQuery yourself to have this fix included.

**Comment by dmeagor** [comment]
Thanks.  Does removing SVG from the allowed tag list prevent this from being a problem?

**Comment by mganss** [comment]
No. The svg tag isn't even in the default white list. This is a parser bug that's triggered before disallowed elements are removed.

**Comment by dmeagor** [comment]
Ok thanks.  Maybe I'll just wait for the anglesharp version to be pushed to nuget.  Any idea when you think it will be stable enough for that?

**Comment by mganss** [comment]
For the record: This problem will most likely also occur with the math element because, like svg, this element has a different namespace in XHTML than HTML elements and that's where the parser bug sits.

**Comment by mganss** [comment]
I hope I can make a beta release with AngleSharp in the next few days.

**Comment by dmeagor** [comment]
Nice, I'll test it for you when you do.

**Comment by mganss** [comment]
There are still a few tests failing due to a minor issue which will be fixed in AngleSharp 0.9 (due out shortly).

**Comment by 304NotModified** [comment]
@mganss, any news on the anglesharp part?

**Comment by mganss** [comment]
All tests are passing. I just pushed v3.0-beta.

**Comment by 304NotModified** [comment]
Nice!

**Comment by 304NotModified** [comment]
PS: the coverity has been lowered a bit and I think you should exclude the tests them self ;)

https://coveralls.io/builds/4001780

**Comment by mganss** [comment]
Back up to ~100% after last commit :smile: 
I think tests should be covered as well, because what good is a test that is not executed (fully)?

**Comment by 304NotModified** [comment]
Good point! 

One downside, it "pollutes"  the average code coverage  IMO.

**Comment by mganss** [comment]
Good point, too :smile:

**Comment by mganss** [comment]
Closing this because we have moved to AngleSharp.
