### ISSUE TITLE
Normal text returned as HTML decoded value

### ISSUE THREAD

**Issue by vishal6code** [mganss/HtmlSanitizer#386]
When we use the input - `statement &paragraph ` , it is returned in HTML encoded format as - `statement ¶graph` instead of the complete text. 
This can also be tested in https://xss.ganss.org/

**Comment by mganss** [comment]
This is expected behavior: See #190 and #362.

**Comment by vishal6code** [comment]
@mganss Assume I have a URL with '&paragraph' in the URL text, and I pass this URL through the Sanitizer. The '&para' is decoded as ¶, and ¶ is an invalid URL character.
The URL is no longer valid.
