### ISSUE TITLE
SanitizeDocument not disposing of AngleSharp HtmlDocument leading to memory leak

### ISSUE THREAD

**Issue by fiseekade** [mganss/HtmlSanitizer#396]
I see that after running `SanitizeDocument(Stream html, string baseUrl = "", IMarkupFormatter? outputFormatter = null)` over many files for several hours, that the memory usage of my application keeps increasing and eventually runs out of memory. I've tracked down the memory leak to the `SanitizeDocument` call which calls AngleSharp `ParseDocument` that returns a `IHtmlDocument` that is not getting cleaned up it seems.

To get around this memory leak issue, I had to switch to using the `SanitizeDom` function and then dispose of the `IHtmlDocument` in my code. Can you fix the `SanitizeDocument` function so that it disposes of the `IHtmlDocument` ? Thanks.

**Comment by mganss** [comment]
See #131.

In your analysis, can you dig down further and see which unmanaged resources are not released?

The managed `IHtmlDocument` object returned by `ParseDocument` is only held in a local variable inside the `SanitizeDocument` method and is eligible for garbage collection when the method returns. Neither `IHtmlDocument` nor the concrete implementation class `HtmlDocument` implement `IDisposable` so it shouldn't be necessary to dispose them.

**Comment by mganss** [comment]
You're right. `IHtmlDocument` does implement `IDisposable` through `IDocument`. I've added a `using` statement.

**Comment by fiseekade** [comment]
Thanks for the quick response and fix. When would a new release be available?

**Comment by mganss** [comment]
I've just released 8.0.601.
