### ISSUE TITLE
Allow specific class names

### ISSUE THREAD

**Issue by icemanind** [mganss/HtmlSanitizer#40]
I know you can allow or disallow the class tag. It would be great if it were possible to be able to specify a list of valid class names. For example, if I wanted to allow the class tag and only allow the "control" class name, something like this:

    var sanitizer = new HtmlSanitizer();
    sanitizer.AllowedTags.Add("class");
    sanitizer.AllowedClassNames.Add("control");
    sanitizer.Sanitize("<div class=\"control\">"); // Passes sanitation
    sanitizer.Sanitize("<div class=\"tiger\">"); // Should remove class "tiger"

**Comment by mganss** [comment]
This can be achieved through events, e.g.:
```C#
var allowedClasses = new[] { "ok", "control" };
sanitizer.RemovingAttribute += (s, e) => e.Cancel = e.Attribute.Key == "class" 
    && allowedClasses.Contains(e.Attribute.Value);
```

**Comment by 304NotModified** [comment]
PS: Of course it would be nice if `allowedClasses` is a `HashSet`
