### ISSUE TITLE
The type or namespace name 'XSS' does not exist in the namespace 'Ganss'

### ISSUE THREAD

**Issue by scottebuchanan** [mganss/HtmlSanitizer#408]
### Discussed in https://github.com/mganss/HtmlSanitizer/discussions/407

After updating to HtmlSanitizer 8.0.601, my project does not compile due to error above (2X).
I have AngleSharp 0.17.1 and AngleSharp.Css 0.16.4 installed (not manually, but as package dependencies).

Best,
Scott

**Comment by tiesont** [comment]
The namespace was normalized to `Ganss.Xss`.
