### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#42]
Hi,

I see for some days "build failed"

https://ci.appveyor.com/project/mganss/htmlsanitizer/build/1.0.42

Is PublishCoverity  not working well? (we are also looking at PublishCoverity for NLog)

**Comment by mganss** [comment]
It's not PublishCoverity's fault but rather Coverity itself. I've tried using the curl command line provided by Coverity, same error (404). Using the regular web interface works. I've contacted their support, no response so far.

**Comment by mganss** [comment]
I have disabled Coverity for now.
