### ISSUE TITLE
55 Failed Tests, 66 Passed

### ISSUE THREAD

**Issue by geekmarine72** [mganss/HtmlSanitizer#43]
Current version (as of 2015-AUG-10) failed 55 unit tests, but passed 66. 

The consistent issues for failures include (SanitizeUnicodeUrlTest() and others):
1) Empty style tag (which is permitted) 
  Expected string length 14 but was 20. Strings differ at index 4.
  Expected: "<div>XSS</div>", ignoring case
  But was:  "<div style>XSS</div>"
  ---------------^
2) Closed tag is valid but not expected (JavaScriptIncludeAndAngleBracketsTest() and others):
  Expected string length 4 but was 6. Strings differ at index 3.
  Expected: "<BR>", ignoring case
  But was:  "<br />"
  --------------^
3) Semi-colon in Style attribute is not expected (DisallowCssPropertyValueTest() and others):
  Expected string length 47 but was 48. Strings differ at index 35.
  Expected: "<div style="background-color: white">Test</div>", ignoring case
  But was:  "<div style="background-color: white;">Test</div>"
  ----------------------------------------------^

I am willing to contribute but the question arises as the intended results.  All tests would pass HTML validation, though fail "good" html syntax verification (i.e. open tags are not considered a syntax failure in HTML).  Please let me know if / how I might participate in this project.

Paul
(PS, Code passed Fortify SCA 4.30 scans with 0 issues)

**Comment by mganss** [comment]
I can't repro. All tests are passing for me. Which environment are you running the tests in? How are you running the tests?

**Comment by geekmarine72** [comment]
Environment:
Microsoft Visual Studio Premium 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.50938
Typemock.VSExtension   1.0
TypeMock Isolator 8.1

Windows Server 2012 Datacenter Edition, 64-Bit

Will pull latest and rerun the tests.

Paul

On Tue, Aug 11, 2015 at 7:41 AM, Michael Ganss <notifications@github.com>
wrote:

> I can't repro. All tests are passing for me. Which environment are you
> running the tests in? How are you running the tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mganss/HtmlSanitizer/issues/43#issuecomment-129911519>
> .
>



-- 
Paul Vilevac
(925) 915- 9128

**Comment by 304NotModified** [comment]
FYI,

I did run the unit tests locally, and all are passing. Tested in .Net 4 and .Net 4.5 - Visual Studio 2013


also

> Tests run: 121, Errors: 0, Failures: 0, Inconclusive: 0, Time: 1.3276049 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
 
See https://ci.appveyor.com/project/mganss/htmlsanitizer/branch/master

**Comment by 304NotModified** [comment]
This one can be closed?

**Comment by mganss** [comment]
Yes.  Will close because no feedback.

**Comment by geekmarine72** [comment]
Yes
