### ISSUE TITLE
Download link for source code v.1.0.0 NetCore3.1

### ISSUE THREAD

**Issue by olexandrman** [mganss/HtmlSanitizer#434]
Hi, could you please tell me where is the download link from GitHub for the source code (https://www.nuget.org/packages/HtmlSanitizer.NetCore3.1)?

**Comment by mganss** [comment]
That NuGet package is not an official package, please do not use it. The [latest official NuGet package](https://www.nuget.org/packages/HtmlSanitizer) supports .NET Core 3.1 as well. Here's how you can download source if you need it:

- On https://github.com/mganss/HtmlSanitizer click the green button labeled "<> Code" at the top right
- Select "Download ZIP" from the dropdown menu that opens

This will download the most current source code. If you need the source code for a particular version:

- On https://github.com/mganss/HtmlSanitizer click the button labeled "master"
- Click "Tags" in the dropdown menu that opens
- Select the desired version
- Download ZIP using the steps above
