### ISSUE TITLE
The src attribute of the img tag is set to a whitelist and is filtered out

### ISSUE THREAD

**Issue by lycoris-xmin** [mganss/HtmlSanitizer#436]
I am using a rich text component, trying to use the function of pasting and copying pictures, but when submitting to the background for XSS filtering, the src attribute of the img tag will be filtered out

![image](https://user-images.githubusercontent.com/43264181/221885876-8094bef3-94d1-4092-b10d-7e1a0b64ae94.png)

Nuget Version: 8.0.645
Runtime platform: .Net 6

**Comment by tiesont** [comment]
This is by design. You need to allow data URIs: https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex2-allowing-data-uris

```c#
var sanitizer = new HtmlSanitizer();
sanitizer.AllowedSchemes.Add("data");
```

**Comment by lycoris-xmin** [comment]
Sorry, I have read some documents, but did not find relevant information, thank you for reminding. Let me try
