### ISSUE TITLE
Incorrect <Img> sanitize when source is empty or not URI

### ISSUE THREAD

**Issue by andreyshiryaev** [mganss/HtmlSanitizer#439]
Good day

`<img src='http://url.to.file.which/not.exist1' onerror='alert(document.cookie)'>` works fine 

But I found 2 issues
1. 
when i try to clear `<img src='' onerror='alert(document.cookie)'>` nothing happens i expect that to be deleted `onerror='alert(document.cookie)'`

I expect like <img src='''>

2. when src is not URI 
`<IMG SRC=j&#X41vascript:alert('test2')>`

I expect like <img src='''>

**Comment by mganss** [comment]
Both cases seem to work fine for me. What do you expect as output in each case?

**Comment by andreyshiryaev** [comment]
> 
I expect that onerror='alert(document.cookie)' and j&#X41vascript:alert('test2') will be removed. 

I try to fix XSS 
![image](https://user-images.githubusercontent.com/14107563/226434031-bab45da1-ee91-43dc-92be-d86e4857efaf.png)

**Comment by mganss** [comment]
Strange. Both work fine for me. Can you provide a short code example that shows the issue?

**Comment by andreyshiryaev** [comment]
> The case `<IMG SRC=j&#X41vascript:alert('test2')>` does not work in your demo because you have not included `src` in the `UriAttributes` collection. The `UriAttributes` collection determines the attributes which will be subject to URI sanitization.
> 
> I'm not sure I understand the `<p><img>&lt;img src=''alert(document.cookie)'&gt;&nbsp;<img><img></p>` case. What do you expect as output? There doesn't seem to be an img element that needs to be sanitized. The `src="..."` part is just text, it's not an attribute of an element.

Thanks a lot.
Close the issue

**Comment by andreyshiryaev** [comment]
> > The case `<IMG SRC=j&#X41vascript:alert('test2')>` does not work in your demo because you have not included `src` in the `UriAttributes` collection. The `UriAttributes` collection determines the attributes which will be subject to URI sanitization.
> > I'm not sure I understand the `<p><img>&lt;img src=''alert(document.cookie)'&gt;&nbsp;<img><img></p>` case. What do you expect as output? There doesn't seem to be an img element that needs to be sanitized. The `src="..."` part is just text, it's not an attribute of an element.
> 
> Thanks a lot. Close the issue. It is problem with the front side too. it send wrong data
