### ISSUE TITLE
Quoted background-image becomes unbalanced

### ISSUE THREAD

**Issue by brunomlopes** [mganss/HtmlSanitizer#44]
Sanitizing 
```html
<div style="background-image: url('some/random/url.img')"></div>
```
Removes the first '. This seems like a bug.

This was tested with nuget HtmlSanitizer 2.0.5623.30465

Here's a test case:
```c#
var _sanitizer = new Ganss.XSS.HtmlSanitizer();
var html = "<div style=\"background-image: url('some/random/url.img')\"></div>";
Assert.Equals("<div style=\"background-image: url('some/random/url.img')\"></div>", _sanitizer.Sanitize(html))
```

**Comment by mganss** [comment]
Thanks for reporting. Fix is up on NuGet as well.

**Comment by brunomlopes** [comment]
Many thanks!

**Comment by 304NotModified** [comment]
@mganss 

Nice it got tested with an unit test :)

It would be nice if this library would keep track of a change log. (or GitHub milestones)
