### ISSUE TITLE
Unresolvable conflicts Anglesharp

### ISSUE THREAD

**Issue by rekna1** [mganss/HtmlSanitizer#444]
I need to use both, but when I compile I get following:
dotNetRdf 3.0.0 -> dotNetRdf.Core 3.0.0 -> AngleSharp (>= 1.0.1) 
HtmlSanitizer 8.0.645 -> AngleSharp (= 0.17.1).

If I install Anglesharp package 1.0.1 I get warnings 
HtmlSanitizer 8.0.645 requires AngleSharp (= 0.17.1) but version AngleSharp 1.0.1 was resolved.
AngleSharp.Css 0.17.0 requires AngleSharp (>= 0.17.0 && < 0.18.0) but version AngleSharp 1.0.1 was resolved.

Any idea how to solve this ???

**Comment by mganss** [comment]
No way to solve it currently AFAICT. HtmlSanitizer depends on AngleSharp.Css whose latest version is still not compatible with AngleSharp 1.0.1. See discussion at #87
