### ISSUE TITLE
data<text removes <text part instead of sanitizing to data&lt;text

### ISSUE THREAD

**Issue by sg2707** [mganss/HtmlSanitizer#464]
Steps to reproduce:

Sanitise the following text
data<text

Actual output:
data

expected:
`data&lt;text`

![image](https://github.com/mganss/HtmlSanitizer/assets/28666415/471fdd67-af1c-4183-90b1-470e65371ede)

**Comment by mganss** [comment]
This is by design, see #91 and #126. See https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing on how to deal with non-HTML input.
