### ISSUE TITLE
Data URL Scheme Support

### ISSUE THREAD

**Issue by gedeh** [mganss/HtmlSanitizer#47]
[RFC 2397](http://tools.ietf.org/html/rfc2397) specifies data URL scheme. I understand that it may lead to an XSS attack if using text/html or text/plain media type, but I think media type like image/png in img tag should pass as browser will try to render it as image. Or is there any particular reason it wasn't?

I created 4 tests for this issue

    [Test]
    public void DataUrlSchemeImgTagUsingImageMediaTypeTest()
    {
        // Arrange
        var s = new HtmlSanitizer();

        // Act
        var htmlFragment = "<img src=\"data:image/gif;base64,R0lGODdhMAAwAPAAAAAAAP///ywAAAAAMAAwAAAC8IyPqcvt3wCcDkiLc7C0qwyGHhSWpjQu5yqmCYsapyuvUUlvONmOZtfzgFzByTB10QgxOR0TqBQejhRNzOfkVJ+5YiUqrXF5Y5lKh/DeuNcP5yLWGsEbtLiOSpa/TPg7JpJHxyendzWTBfX0cxOnKPjgBzi4diinWGdkF8kjdfnycQZXZeYGejmJlZeGl9i2icVqaNVailT6F5iJ90m6mvuTS4OK05M0vDk0Q4XUtwvKOzrcd3iq9uisF81M1OIcR7lEewwcLp7tuNNkM3uNna3F2JQFo97Vriy/Xl4/f1cf5VWzXyym7PHhhx4dbgYKAAA7\" alt=\"Larry\">";
        var actual = s.Sanitize(htmlFragment);

        // Assert
        var expected = "<img src=\"data:image/gif;base64,R0lGODdhMAAwAPAAAAAAAP///ywAAAAAMAAwAAAC8IyPqcvt3wCcDkiLc7C0qwyGHhSWpjQu5yqmCYsapyuvUUlvONmOZtfzgFzByTB10QgxOR0TqBQejhRNzOfkVJ+5YiUqrXF5Y5lKh/DeuNcP5yLWGsEbtLiOSpa/TPg7JpJHxyendzWTBfX0cxOnKPjgBzi4diinWGdkF8kjdfnycQZXZeYGejmJlZeGl9i2icVqaNVailT6F5iJ90m6mvuTS4OK05M0vDk0Q4XUtwvKOzrcd3iq9uisF81M1OIcR7lEewwcLp7tuNNkM3uNna3F2JQFo97Vriy/Xl4/f1cf5VWzXyym7PHhhx4dbgYKAAA7\" alt=\"Larry\">";
        Assert.That(actual, Is.EqualTo(expected).IgnoreCase);
    }

    [Test]
    public void DataUrlSchemeImgTagUsingImageMediaTypeContainMaliciousJavaScriptTest()
    {
        // Arrange
        var s = new HtmlSanitizer();

        // Act
        // base 64 encoded string of of <script>alert("Hello");</script> but specified as image/gif
        var htmlFragment = "<img src=\"data:image/gif;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4=\">";
        var actual = s.Sanitize(htmlFragment);

        // Assert
        var expected = "<img src=\"data:image/gif;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4=\">";
        Assert.That(actual, Is.EqualTo(expected).IgnoreCase);
    }

    [Test]
    public void DataUrlSchemeImgTagWithNonImageMediaType()
    {
        // Arrange
        var s = new HtmlSanitizer();

        // Act
        // base 64 encoded string of of <script>alert("Hello");</script>
        var htmlFragment = "<img src=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4=\">";
        var actual = s.Sanitize(htmlFragment);

        // Assert
        var expected = "<img>";
        Assert.That(actual, Is.EqualTo(expected).IgnoreCase);
    }

    [Test]
    public void DataUrlSchemeScriptTagTest()
    {
        // Arrange
        var s = new HtmlSanitizer();

        // Act
        // base 64 encoded string of of <script>alert("Hello");</script>
        var htmlFragment = "<script src=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4=\"></script>";
        var actual = s.Sanitize(htmlFragment);

        // Assert
        var expected = "";
        Assert.That(actual, Is.EqualTo(expected).IgnoreCase);
    }

**Comment by 304NotModified** [comment]
Is this not a problem with IE's "great" [MIME Type Detection](https://msdn.microsoft.com/en-us/library/ms775147(v=vs.85).aspx) ?

**Comment by gedeh** [comment]
But multimedia data type should be safe, no? for example audio, image, and video.

**Comment by 304NotModified** [comment]
>or example, when a web application allows users to upload an image and only checks the file extension, the user can upload an image.jpg that actually contains HTML code. Older versions of Internet Explorer (especially versions 6 and 7) then render the file as HTML, which opened the possibility for a persistent Cross-Site Scripting (XSS) attack. 

http://blog.fox-it.com/2012/05/08/mime-sniffing-feature-or-vulnerability/


Not sure if this counts for data uris

**Comment by gedeh** [comment]
I tried several case with image and script, also iframe tag in IE11 (MDN page says IE11 only support data URI for CSS, <link>, and <img>)

	<img alt="Incorrect image using image/png data type" src="data:image/png;base64,amF2YXNjcmlwdDphbGVydCgnWFNTJyk7"/>
	<img alt="Incorrect image using text/html data type contain javascript:alert('XSS');" src="data:image/png;base64,amF2YXNjcmlwdDphbGVydCgnWFNTJyk7"/>
	<img alt="Incorrect image using text/html data type contain <script>alert('Hello');</script>" src="data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4="/>
	<script src="data:text/html;base64,amF2YXNjcmlwdDphbGVydCgnWFNTJyk7"></script>
	<iframe src="data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8iKTs8L3NjcmlwdD4="></iframe>

img tag doesn't expose XSS threat although using invalid mime type and data. SO I think above link doesn't count for data uris

**Comment by mganss** [comment]
If you want to allow the data protocol, you can do so using the `AllowedSchemes` property. Potential problems with "wrong" MIME types apply equally to http, don't they? That is, if you allow img tags, you'll have to trust the browser because you have no control over what the server responds with.

**Comment by 304NotModified** [comment]
Agree on that :)

**Comment by gedeh** [comment]
Agreed too. Thanks for your explanation :)
