### ISSUE TITLE
I updated to the latest HtmlSanitizer - 8.0.746 and it won't run

### ISSUE THREAD

**Issue by rgoodman1977** [mganss/HtmlSanitizer#492]
I am getting this error when trying to load the sanitizer:

<img width="821" alt="image" src="https://github.com/mganss/HtmlSanitizer/assets/149836175/aecf7535-e769-4b14-81a2-40cdced15f98">

I can't see anything referencing AngleSharp, Version=0.17.0.0'

This is what my nuget screen look like right now:

<img width="680" alt="image" src="https://github.com/mganss/HtmlSanitizer/assets/149836175/6e2a87b4-d3da-4cb7-99a1-99741c54ac3e">

Any advice? Thanks

**Comment by tiesont** [comment]
What version of .NET does your project target? If there's an app.config or web.config, make sure that the assembly reference is correct. If this project references other projects which also reference AngleSharp for whatever reason, make sure that they target the same version.

Beyond that... I'm using HtmlSanitizer in a .NET6 project with no issues, so it's something abut your setup.

**Comment by mganss** [comment]
I'm going to close this for now.

**Comment by Arjanvanmaren** [comment]
This fixed it for me, adding this to my web config of the project.

`<dependentAssembly> 
    <assemblyIdentity name="AngleSharp" publicKeyToken="e83494dcdc6d31ea" culture="neutral"/> 
    <bindingRedirect oldVersion="0.0.0.0-0.17.1.0" newVersion="0.17.1.0"/> 
 </dependentAssembly> `
