### ISSUE TITLE
Configuration option to bypass changes for security advisory

### ISSUE THREAD

**Issue by jerriep** [mganss/HtmlSanitizer#511]
I want to enquire whether it would be possible to add a configuration option to bypass the encoding that was done as part of https://github.com/mganss/HtmlSanitizer/commit/ab29319866c020f0cc11e6b92228cd8039196c6e.

I have a use case where it is valid for users to pass custom content that I do not want to be encoded. In my case, I produce an HTML document like the one below:

```
<p>
  This is a test case to see whether we can pass raw content to a Contentful
  Long Text (markdown) field
</p>
<script data-cp-raw-block="">
  <CollapsibleSection label="Click to expand!">
  Content that was hidden before!
  </CollapsibleSection>

  <TextBox>__Title__
  Your text here.
  </TextBox>
</script>
<p>This is some text after the table</p>
```

The markup inside the `script` tag is user-generated and must not be encoded as it must be passed precisely as-is to an external system. With the changes made in the commit linked above, the custom tags inside that `script` element are encoded, breaking things down the line for me.

Would it be possible to add a configuration option to bypass the encoding?

I am happy to submit a PR for this.

**Comment by tiesont** [comment]
Curious - how does the browser treat that script tag? The default `type` for `<script>` is `text/javascript` ([according to the MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type)), so it should be throwing up errors once it encounters markup (since it wouldn't be valid JavaScript).

**Comment by tiesont** [comment]
I assumed it was something like that.

Would something like this example work for you? https://github.com/mganss/HtmlSanitizer/wiki/Examples#ex4-encode-non-html-before-sanitizing

**Comment by tiesont** [comment]
So, you're after something that could be referenced in `private void DoSanitize(IHtmlDocument dom, IParentNode context, string baseUrl = "")`?

So [this](https://github.com/mganss/HtmlSanitizer/blob/master/src/HtmlSanitizer/HtmlSanitizer.cs#L476):

```c#
// always encode text in raw data content
foreach (var tag in context.QuerySelectorAll("*")
	.Where(t => t is not IHtmlStyleElement
		&& t.Flags.HasFlag(NodeFlags.LiteralText)
		&& !string.IsNullOrWhiteSpace(t.InnerHtml)))
{
	var escapedHtml = tag.InnerHtml.Replace("<", "&lt;").Replace(">", "&gt;");
	if (escapedHtml != tag.InnerHtml)
		tag.InnerHtml = escapedHtml;
	if (tag.InnerHtml != escapedHtml) // setting InnerHtml does not work for noscript
		tag.SetInnerText(escapedHtml);
}
```
would change to something like:

```c#
if(EncodeRawDataContext)
{
    // Encode text in raw data content
    foreach (var tag in context.QuerySelectorAll("*")
        .Where(t => t is not IHtmlStyleElement
            && t.Flags.HasFlag(NodeFlags.LiteralText)
            && !string.IsNullOrWhiteSpace(t.InnerHtml)))
    {
        var escapedHtml = tag.InnerHtml.Replace("<", "&lt;").Replace(">", "&gt;");
        if (escapedHtml != tag.InnerHtml)
            tag.InnerHtml = escapedHtml;
        if (tag.InnerHtml != escapedHtml) // setting InnerHtml does not work for noscript
            tag.SetInnerText(escapedHtml);
    }
}
```

assuming `EncodeRawDataContext` is a new option which defaults to `true` according to the current behavior.

**Comment by mganss** [comment]
Thanks @jerriep for your effort. I prefer option 2 as in @tiesont's example above and `EncodeLiteralTextElementContent`.
