### ISSUE TITLE
Sanitize Vue.js scripts

### ISSUE THREAD

**Issue by gmarzaloni-onit** [mganss/HtmlSanitizer#515]
Hello,
HtmlSanitizer is not sanitize this example Vue.js script code:

```
{{$on.constructor('alert(1)')()}}
```

This code, placed for example in a OPTION item, creates a XSS vulnerability on the page.

```
<select>
  <option value="1">Item 1 {{$on.constructor(&#x27;alert(1)&#x27;)()}}</option>
  <option value="2">Item 2</option>
</select>
```

On load, the page shows the modal alert.

<img width="529" alt="image" src="https://github.com/mganss/HtmlSanitizer/assets/60892664/b42c1495-06fc-4768-8799-23d2beab38d0">

**Comment by mganss** [comment]
This scenario is out of scope as we only deal with HTML, not specific frameworks that have their own syntax. That said, the upcoming change in #511 would probably allow you to handle this use case. In the current version you can probably use the `PostProcessNode` to enable this use case.
