### ISSUE TITLE
System.MissingMethod exception with AngleSharp 0.9.4

### ISSUE THREAD

**Issue by rmichela** [mganss/HtmlSanitizer#53]
After updating to AngleSharp 0.9.4, `HtmlSanitizer.Sanitize()` started throwing a `MissingMethodException`.

    Method not found: 'System.String AngleSharp.IStyleFormattable.ToCss()'
    at Ganss.XSS.HtmlSanitizer.SanitizeStyle(IHtmlElement element, String baseUrl)
    at Ganss.XSS.HtmlSanitizer.Sanitize(String html, String baseUrl, IMarkupFormatter outputFormatter)

Reverting to AngleSharp 0.9.3 fixed the problem.

**Comment by 304NotModified** [comment]
I think angelsharp isn't following semver then.

**Comment by mganss** [comment]
The method was moved from the interface to an extension method in AngleSharp/AngleSharp@59d98f0cbf2d275acb1b6187b99ff0fe1b8d829a, causing binary incompatibility. Recompiling fixes it. Will release a new version shortly.

**Comment by 304NotModified** [comment]
Ow the apply to semver I see:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

http://semver.org/#spec-item-4
