### ISSUE TITLE
Sanitizer removes "px" from the source style attributes when it's "0px"

### ISSUE THREAD

**Issue by elninoisback** [mganss/HtmlSanitizer#539]
`<p style="margin: 0px;">TEST<p>`

Consider the above source input. The sanitizer removes "px" in the output, which is unnecessary and creates comparing very hard when need to know if sanitizer has changed the source or not.

Is there a way to turn off this default behavior?

**Comment by mganss** [comment]
No, unfortunately it's not currently. The style is parsed by AngleSharp and then rendered back out which results in these subtle differences in the output.
