### ISSUE TITLE
NuGet Package version 3.x unable to install into project..

### ISSUE THREAD

**Issue by adramalech** [mganss/HtmlSanitizer#54]
Hey,

So I am unable to install your 3.x NuGet package.  Tried running as Admin and normal user.

Error:  "Could not be found in your workspace, or you do not have permission to access it."
  
Packages:
Microsoft.Bcl.Build.1.0.14
Microsoft.Bcl.Async.1.0.168
AngleSharp 0.9.4
HtmlSanitizer 3.1.79
 
Any help would be greatly appreciated.  It seems I am able to install HtmlSanitize version 2.x is that stable and version 3.x still in beta?

**Comment by 304NotModified** [comment]
are you using TFS? http://stackoverflow.com/questions/11608627/files-could-not-be-found-in-workspace

**Comment by adramalech** [comment]
Yea on this project I am having to use TFS 2010..  Probably is a TFS error you think?

**Comment by 304NotModified** [comment]
Just a wild guess, as I never saw this error before. (and I never used TFS)

**Comment by mganss** [comment]
If this still occurs w/o TFS involved please provide steps to repro. 3.x is stable.

**Comment by mganss** [comment]
Closing this because no feedback.
