### ISSUE TITLE
FilterUrl event not raised for relative URLs if baseUrl is used

### ISSUE THREAD

**Issue by vanni-giachin** [mganss/HtmlSanitizer#542]
According to the documentation the FilterUrl event should be raised every time a URL is sanitized:

> Occurs when a URL is being sanitized

However if the URL to sanitize is relative, and a baseUrl is used as sanitization parameter, the URL filters are not invoked.

See code line: https://github.com/mganss/HtmlSanitizer/blob/v8.0.843/src/HtmlSanitizer/HtmlSanitizer.cs#L856

There is a _return_ statement before _OnFilteringUrl_ is invoked: `return new Uri(baseUri, iri.Value).AbsoluteUri;`

**Comment by mganss** [comment]
Great catch, thank you!
