### ISSUE TITLE
Unable to load assembly AngleSharp Version 0.17.0 when HtmlSanitizer Initialized 

### ISSUE THREAD

**Issue by dutchaussie** [mganss/HtmlSanitizer#549]
![image](https://github.com/mganss/HtmlSanitizer/assets/44717269/1e3109e2-2a4a-4b56-b2b5-c6bd473a7adc)

I am using .net 4.8 Framework running on Windows 10. 
Using VS2022 Community Edition - version 17.9.6

Have looked for any other projects in my solution that would reference Version 0.17.0 of AngleSharp but did not find. I have followed all manner of instructions from copilot to resolve this issue, but to no avail. 
Version 0.17.0 of AngleSharp does not even exist as such.

**Comment by tiesont** [comment]
Should probably check existing issues. See #544 and #528. 

Basically: AngleSharp.Css has a hard dependency/reference on AngleSharp 0.17.**0**, but HtmlSanitizer references AngleSharp 0.17.**1**. Adding a binding redirect will solve the reference error.
