### ISSUE TITLE
CoreCLR support

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#59]
Any plans to move to xproj / with CoreCLR support? 

[AngleSharp](https://www.nuget.org/packages/AngleSharp/) has it already, so won't be that difficult I guess.

**Comment by mganss** [comment]
What's necessary to do this? The analyzer says 100%.

**Comment by 304NotModified** [comment]
Move to the new project.json format.  Vs2015 is required.  Appveyor needs A config change.

**Comment by mganss** [comment]
Can you point me to some docs? I don't see project.json in AngleSharp.

**Comment by 304NotModified** [comment]
Ow indeed.  I was wrong,  angelsharp doesn't support coreclr. 

Starter would be https://dotnet.github.io

**Comment by 304NotModified** [comment]
FYI CoreCLR support for AngleSharp is planned for version 1.0

https://github.com/AngleSharp/AngleSharp/issues/270

**Comment by gdoron** [comment]
I need CoreCLR support too.
+1

**Comment by mganss** [comment]
This is now being worked on. See #72.

**Comment by mganss** [comment]
Done (3.3.122-beta).
