### ISSUE TITLE
Add exception for youtube iframe

### ISSUE THREAD

**Issue by ro31337** [mganss/HtmlSanitizer#6]
Iframes with src to youtube should not be stripped.

**Comment by beowshawitz** [comment]
This link does not work any longer. How would you recommend permitting iframes with URLs going to youtube?

**Comment by tiesont** [comment]
@beowshawitz Probably something similar to this: https://github.com/mganss/HtmlSanitizer/commit/d8c6ac0598f032d5a51b5e419ab17a429df7708b

**Comment by mganss** [comment]
The code linked to originally is now here: https://github.com/mganss/HtmlSanitizer/blob/6191a5e0dc4a9c642291fed1a3398ce2f9960b81/test/HtmlSanitizer.Tests/Tests.cs#L2058-L2065

**Comment by beowshawitz** [comment]
Thanks! The way I handled it was to attach to the RemovingTag event. From there I checked if the tag was an IFRAME and had a YouTube URL in the SRC attribute.
```
if(e.Tag.NodeName.Equals("IFRAME", StringComparison.OrdinalIgnoreCase))
{
	string src = e.Tag.GetAttribute("src");
	if(!string.IsNullOrEmpty(src) && Regex.IsMatch(src, @"YOUTUBEREGEXOFYOURCHOICE", RegexOptions.IgnoreCase))
	{
		e.Cancel = true;
	}
}
```
