### ISSUE TITLE
HtmlSanitizer doesn't sanitize html attribute values

### ISSUE THREAD

**Issue by amitandhale** [mganss/HtmlSanitizer#60]
Hi,
I am using HtmlSanitizer library. My use case is to whitelist some html attributes like OnMouseHover but I don't want javascript "alert" as a value of OnMouseHover. For example: following is my Html which I want to sanitize:
&lt;h1 onmouseover=&quot;alert(&#39;This is XSS attack&#39;)&quot;&gt;XSS&lt;/h1&gt;

So I want Sanitization library to check the value of attributes which is not currently supported. Currently I downloaded the source code and made customizations as per my requirement. Do you have any plans to support attribute value sanitization? Please do let me know. 

Thanks
Amit

**Comment by 304NotModified** [comment]
You can do this by using the remove event?

**Comment by mganss** [comment]
Elaborating on what @304NotModified has already said: For your specific use case, you don't want to whitelist onmousehover, but rather subscribe to the RemovingAttribute event and implement your whitelisting logic in the handler. For example:

```C#
sanitizer.RemovingAttribute += (s, e) => e.Cancel = e.Attribute.Name == "onmousehover"
    && !e.Attribute.Value.StartsWith("alert", StringComparison.OrdinalIgnoreCase);
```

That said, I think it will be very hard to get this bullet proof. The code above would let `window.alert('xss')` through, for example.

**Comment by 304NotModified** [comment]
> That said, I think it will be very hard to get this bullet proof. The code above would let window.alert('xss') through, for example.

The filtering should be a white-list of course :)
