### ISSUE TITLE
HtmlSanitizer doesn't recursively sanitize the input data.

### ISSUE THREAD

**Issue by amitandhale** [mganss/HtmlSanitizer#61]
Hi,

I am using HtmlSanitization library in my project to sanitize the input data. It works very nicely in all inputs and thanks a lot for the library. While testing I came across scenario in which I want HtmlSanitizer to recursively sanitize the input string which it is not currently doing.

Following is my input string:
&lt;&lt;abc&gt;&lt;/abc&gt;script&gt;alert(&#39;XSS&#39;)&lt;&lt;abc&gt;&lt;/abc&gt;/script&gt;

"abc" is my custom tag which is not whitelisted. As expected HtmlSanitizer removes the &lt;abc&gt;&lt;/abc&gt; tag. But since this one level sanitization, it the output string still contains malicious input data which is 
&lt;script&gt;alert(&#39;XSS&#39;)&lt;/script&gt; 

HtmlSanitization should be iteration based and it should recursively sanitize the input string. Do you have any plans to support such functionality as it will be much needed functionality.

Please do let me know your road map and your thoughts.

Thanks
Amit.

**Comment by 304NotModified** [comment]
That would be a big issue!

Which version did you have tested? V3 or V2? Can you also test with the other version?

**Comment by mganss** [comment]
In v3 the input results in
```HTML
&lt;script&gt;alert('XSS')&lt;/script&gt;
```
This is expected behavior. I haven't tested with v2.

**Comment by amitandhale** [comment]
I tested it with v3. But if this is the expected behavior then this is the issue as above script will get executed in any input.

**Comment by mganss** [comment]
Why would it be executed? There is no script tag in the output, the angle brackets are encoded are HTML entities.

**Comment by 304NotModified** [comment]
I would also expected that the sanitizer would remove (not encode) dangerous elements, so you can do: read as text, display as HTML

**Comment by mganss** [comment]
There is no dangerous element in the example input:
```HTML
<<abc></abc>script>alert('XSS')<<abc></abc>/script>
```
There's a lone left angle bracket, then an empty abc element (gets removed), the text "script", a lone right angle bracket, the text "alert('xss')", lone left angle bracket, empty abc element (gets removed), the text "/script", lone right angle bracket.

I believe it's a feature that we are using a real, sophisticated HTML parser with AngleSharp and are not just removing text between < and >.

**Comment by 304NotModified** [comment]
> In v3 the input results in
> 
> &lt;script&gt;alert('XSS')&lt;/script&gt;

isn;t `&lt;script&gt;` unsafe? (`<script>` decoded)

**Comment by mganss** [comment]
BTW, this is exactly what the [sanitizer GitHub uses](https://github.com/rgrove/sanitize) produces as a result. Here's the input string pasted verbatim into this comment:

<<abc></abc>script>alert('XSS')<<abc></abc>/script>

**Comment by mganss** [comment]
> isn;t `&lt;script&gt;` unsafe? (`<script>` decoded)

What's unsafe about it? You can render it into your HTML document without having to worry about Javascript being executed.

**Comment by 304NotModified** [comment]
put `&lt;script&gt;alert('oops')` in value attribute in [this CodePen](http://codepen.io/anon/pen/qbGLQy), like this

![image](https://cloud.githubusercontent.com/assets/5808377/13190310/bb312e1a-d75c-11e5-874e-b947852f904c.png)

Press OK:

![image](https://cloud.githubusercontent.com/assets/5808377/13190329/d49399b0-d75c-11e5-895b-552a26f821a1.png)

note: cannot save this Pen with the attribute prefilled ;)

**Comment by mganss** [comment]
I don't see the point. Everything seems to be ok, except you're not sanitizing the user input in your Javascript.

**Comment by 304NotModified** [comment]
This input is sanitised (it the result of this library)

**Comment by mganss** [comment]
Sorry, I still don't get what you're aiming at. The way I see it is that the JavaScript in your example represents the instance that processes the user input. This instance needs to sanitize the input before it renders it back out.

The input that the JavaScript gets is not sanitized because the browser renders ’&lt;’ as < etc. It's the same value a server side application receives when a form is posted (making it necessary to sanitize).

But the HTML that contains the input field is sanitized, otherwise the alert might pop up when it is rendered (before you submit).

**Comment by 304NotModified** [comment]
Did you checked the html source in the code pen? 

If it's still unclear, I will try to explain it in another view point. I'm pretty sure this is an important subject for this library.

**Comment by mganss** [comment]
Yes, please elaborate.

**Comment by 304NotModified** [comment]
To prevent XSS you can do 3 things.

1. Remove all the HTML before printing, e.g. `<script>evil<script><b>fat</b>text` => `text`
2. HTML encode the input . `<script>evil<script><b>fat</b>text` => `&lt;script&gt;evil&lt;script&gt;&lt;b&gt;fat&lt;/b&gt;text`
3. Use a sanitizer: `<script>evil<script><b>fat</b>text` =>  `<b>fat</b>text`

Remove all the HTML (1) has the downside of missing all the markup, HTML encode (2) has the downside that this can be still dangerous when other components has bugs (e.g. interpret text as html). A sanitizer (3) should be the perfect solution because we known for sure that the (potential) evil stuff  has been removed.

As you can see in the code pen, not only `<script>evil<script>` is evil but also `&lt;script&gt;evil&lt;script&gt;`. As we can't be sure that all the components in the application are bug-free, we like to remove (potential) evil stuff.

**Comment by amitandhale** [comment]
Yes, I do agree with Julian.

This is what I would like to convey also. In my application there are
various rich text editors hence once HtmlSanitizer sanitizes following
input:
<<abc></abc>script>alert('XSS')<<abc></abc>/script>

The sanitization output will be <script>alert('XSS')</script> which will
get executed in my rich text editors. So I want to make sure that whatever
user in entering is not an evil stuff. So HtmlSanitizer should also remove
<script>alert('XSS')</script>.

On Sat, Feb 20, 2016 at 10:35 PM, Julian Verdurmen <notifications@github.com

**Comment by mganss** [comment]
@304NotModified:
I agree with the first part, it's the reason this library exists. But I don't agree with the following:
> As you can see in the code pen, not only `<script>evil<script>` is evil but also `&lt;script&gt;evil&lt;script&gt;`.

It seems to me you're confusing the visible text with the source HTML. It only becomes evil once the visible text is again inserted as raw HTML by the Javascript code.

Let's assume you have a discussion site that sanitizes user input in the way you propose (stripping  `&lt;script&gt;evil&lt;script&gt;` etc): How could you have a discussion about HTML? All snippets posted by users as escaped HTML would be stripped.

The perfect example are the comments in this very issue on GitHub.

Please show me a reputable sanitizing library that works the way you propose.

@amitandhale:

> The sanitization output will be `<script>alert('XSS')</script>`

No, it will be `&lt;script&gt;alert('XSS')&lt;/script&gt;` and not get executed.

**Comment by tiesont** [comment]
For what it's worth, I've used HtmlSanitizer with TinyMCE to edit a chunk of HTML containing an embedded Gist (so, a <script> tag) and it did **not** execute the script, so my experience says @mganss is correct.
