### ISSUE TITLE
Option to not encode symbols

### ISSUE THREAD

**Issue by SovietSam** [mganss/HtmlSanitizer#62]
Hi! Is there any option to not HTMLEncode certain symbols. For example, to not encode `&` to `&amp;`?

**Comment by 304NotModified** [comment]
isn't then invalid HTML?

**Comment by SovietSam** [comment]
Maybe. But for my case invalidation doesn't matter. So is there any option or event to hook?

**Comment by mganss** [comment]
I don't think it's possible. You can pass an `IMarkupFormatter` instance to the `Sanitize()` method which is useful if you want XHTML output but AFAICT it doesn't allow you to tweak the output of entities.

**Comment by mganss** [comment]
You can try and subscribe to the `PostProcessNode` event and see if you can transform entity nodes back to regular text.

**Comment by SovietSam** [comment]
Ok. Sad that encoding is not optional. Works ugly with default ASP.NET Razor encoding behaviour. Everything is double encoded.

**Comment by mganss** [comment]
I don't understand the use case. Are you using `@Html.Raw()` and things still get double encoded?

**Comment by SovietSam** [comment]
No. I'm talking about default behaviour when Razor encodes everything by default. Very wise implementation of last line of defense. I prefer to not disable it. It would be nice if there was option in HtmlSanitizer to just sanitize (remove unwanted tags), and don't encode output.

**Comment by 304NotModified** [comment]
Well if you like to print html in Razor, you `@Html.Raw()` OR `HtmlString` for that. Razor can't otherwise know this is safe html.

**Comment by mganss** [comment]
If you use the default Razor behavior (`@xyz`) then you don't need a sanitizer. A sanitizer is for when you want to let some limited amount of unencoded HTML through and still be safe from XSS.

**Comment by SlyNet** [comment]
The thing is that 

```
class direct_tests
{
    private HtmlSanitizer sanitizer;

    [SetUp]
    public void Setup()
    {
        sanitizer = new HtmlSanitizer();
        sanitizer.AllowedAttributes.Clear();
        sanitizer.AllowedTags.Clear();
    }

    [Test]
    public void when_text_contains_gt_symbol()
    {
        var oneTwo = "one > two";
        var noTags = sanitizer.Sanitize(oneTwo);
        Assert.That(noTags, Is.EqualTo(oneTwo));
    }

    [Test]
    public void if_text_contains_encoded_html_and_RemoveHtmlAndDecode_used()
    {
        var oneTwo = "one &gt; two";
        var noTags = sanitizer.Sanitize(oneTwo);
        Assert.That(noTags, Is.EqualTo(oneTwo));
    }
}
```

first test is failing, so its not possible to just call HtmlDecode on `noTags` to get unencoded text. Is it possible to presereve `>` unencoded somehow?

**Comment by mganss** [comment]
I don't think it's possible. The HTML parser in AngleSharp encodes the `>` . It's the same in the browser:

```javascript
var e = document.createElement("div");
e.innerHTML = 'one > two';
e.innerHTML // -> "one &gt; two"
```

What's your use case?

**Comment by SlyNet** [comment]
the case is that from html `<font color="red">one > two</font>` I need to keep only `one > two` but `>` should not be encoded

**Comment by 304NotModified** [comment]
that's clearly invalid html

**Comment by mganss** [comment]
Surprisingly, this not invalid HTML (at least not according to the HTML5 validator at https://html5.validator.nu/):

```HTML
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<p>
a > b
</p>
</body>
</html>
```

while this IS invalid:

```HTML
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<p>
a < b
</p>
</body>
</html>
```

Anyway, IMO it doesn't matter whether it's invalid or not. If you want to keep only the text output, see the discussion at #116.
