### ISSUE TITLE
Incompability with AngleSharp 0.9.5

### ISSUE THREAD

**Issue by xaviergonz** [mganss/HtmlSanitizer#64]
While using Sanitize in ASP.net MVC using AngleSharp 0.9.5 I get the following error:

Could not load type 'AngleSharp.FormatExtensions' from assembly 'AngleSharp, Version=0.9.5.41771, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'.

The binding is properly set to:

```XML
<dependentAssembly>
  <assemblyIdentity name="AngleSharp" publicKeyToken="e83494dcdc6d31ea" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-0.9.5.41771" newVersion="0.9.5.41771" />
</dependentAssembly>
```

It does not happen with 0.9.4.

**Comment by 304NotModified** [comment]
I Guess you need a `<assemblyBinding>` in your .config

**Comment by mganss** [comment]
There was a breaking change in AngleSharp 0.9.5. I made a new release.
@xaviergonz Does this fix it for you?

**Comment by xaviergonz** [comment]
Yep that fixed it, thanks
