### ISSUE TITLE
br tag is allowed but if added like <br/> it gets sanitized and gets changed to <br> only.

### ISSUE THREAD

**Issue by sehgalg** [mganss/HtmlSanitizer#65]

**Comment by mganss** [comment]
`<br>` is legal HTML syntax that is compatible with HTML 4 and 5. If you want XHTML syntax, you can try the `Sanitize()` overload that takes an `IMarkupFormatter` instance and pass in `AngleSharp.Xml.XmlMarkupFormatter.Instance`.
