### ISSUE TITLE
replacement in url of #  with %23

### ISSUE THREAD

**Issue by h4d3s2004** [mganss/HtmlSanitizer#67]
Hi !
How can one avoid the transformation of  
     < a href="http://domain.com/index.html?test=#value#" >
to  < a href="http://domain.com/index.html?test=#value%23" > 
```? 
Thanks.

**Comment by mganss** [comment]
I can't repro (using the latest version). The input URI is invalid according to RFC 3986, though.

**Comment by h4d3s2004** [comment]
ok, thanks ... but in the latest I get &amp;  instead of & in urls ... (i.e.<a href="domain.com?test=#test#&amp;va=1"></a>)

**Comment by mganss** [comment]
This behavior is expected. Ampersands must be encoded in HTML.
