### ISSUE TITLE
HTMLSanitizer not supporting "face" attribute

### ISSUE THREAD

**Issue by biancarus88** [mganss/HtmlSanitizer#69]
Hi!

In our application, we are using an Infragistics WebHtmlEditor, which when you set a font face, you will end up with the following markup : "< p > < font face = "Impact" size = "3" > font face test < /font > < /p >".
After I sanitize this, I end up with : "< p > < font size = "3" > font face test < /font > < /p >". Shouldn't "face" attribute be supported?
I did fix this by using sanitizer.AllowedAttributes.Add("face"), however, my concern is what other tags/attributes, etc might be missing from this list : https://pythonhosted.org/feedparser/html-sanitization.html as we might be having trouble with some other stylings as well.
Thanks

**Comment by mganss** [comment]
The tags, attributes, and CSS properties allowed by default are listed in the [README](https://github.com/mganss/HtmlSanitizer/blob/0ec9e0557641a98c30c00259947140e40166aff3/README.md). Although there may be some tags, attributes etc. which do no pose a security threat but are still not allowed by default, I'd rather not expand the default list right now.

**Comment by 304NotModified** [comment]
I think that's a wise choice. :+1:
