### ISSUE TITLE
how to allow all data- attributes

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#7]
Is it possible to allow all data- attributes?

**Comment by jsdev17** [comment]
Hello @mganss.
I came across this thread because I was looking into how to enable data-* attributes.
I tried this
```csharp
sanitizer.RemovingAttribute += (s, e) => e.Cancel = e.Attribute.Key.StartsWith("data-");
```
But am getting an error saying:
>Error	CS1061	'IAttr' does not contain a definition for 'Key' and no accessible extension method 'Key' accepting a first argument of type 'IAttr' could be found (are you missing a using directive or an assembly reference?)

I looked into `IAttr` definition and there is not a `Key` property, but there is `Name`.

Will this achieve the same results?

```csharp
sanitizer.RemovingAttribute += (s, e) => e.Cancel = e.Attribute.Name.StartsWith("data-");
```

**Comment by jsdev17** [comment]
For anyone who might run into this:
Just tested it and it does work.

**Comment by jsdev17** [comment]
Hah! Even better. Thanks!
