### ISSUE TITLE
Is it possible to get a clear indication if the HTML was modified?

### ISSUE THREAD

**Issue by DumboJet** [mganss/HtmlSanitizer#70]
Hello and thanks for this good library! :)
A small issue that I have:

I feed it with this (clean and valid) input:

```
<p><img src=\"/Customization/CustomImage/?ImageGuid=4c8989dd-d57a-4d57-9b44-c40d8bd60312\" alt=\"\" /></p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<div>&nbsp;</div>\r\n<p>Test</p>
```

and I get back this:

```
<p><img src=\"/Customization/CustomImage/?ImageGuid=4c8989dd-d57a-4d57-9b44-c40d8bd60312\" alt=\"\"></p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n<div>&nbsp;</div>\n<p>Test</p>
```

Notice the removal of the / from the `<img>` self-closing tag.
Is it possible to get a clear indication if the HTML was modified (not based on string comparison that returns false indications (as in the case above), but based on the actual end result on the DOM)?

I want to log the original user inputs when they get modified by sanitization and this creates false log entries for me.

Thanks! :)

**Edit:**
I am not sure if it will be good to use the events to detect changes:
```
                    _sanitizer.RemovingAttribute += (s, e) => { };
                    _sanitizer.RemovingStyle += (s, e) => { };
                    _sanitizer.RemovingTag += (s, e) => { };
                    _sanitizer.RemovingAtRule += (s, e) => { };
```

**Comment by DumboJet** [comment]
Also, another question that might be good to be added to the main project page:

Is it safe to use the same instance of the sanitizer in multiple threads?
Or I should create a new one for each thread?

**Comment by DumboJet** [comment]
> I am not sure if it will be good to use the events to detect changes

That seems to work.
Just you are forced to create a new sanitizer for each sanitization (so that you don't have problems with multiple threads using a single one).

**Comment by 304NotModified** [comment]
> Is it safe to use the same instance of the sanitizer in multiple threads?

That most of the cases easy in .Net - only `static` methods are thread-safe until otherwise stated ;)

AFAIK it's now not thread-safe, so create new instances

**Comment by DumboJet** [comment]
OK. :)
Thanks.
I guess I can close this issue then. ;)

**Comment by mganss** [comment]
As long as you only call `Sanitize()` from different threads (i.e. set all properties like allowed tags etc. beforehand) it *should* be thread-safe but as @304NotModified said, there are no guarantees. We're creating a new instance of the HTML parser for each call to `Sanitize()` and there is no per-instance state that is modified during the call.

**Comment by DumboJet** [comment]
Thanks for the info. :)
