### ISSUE TITLE
Strong name is wrong in beta version

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#73]
The strong name has been changed in the beta version, which is not recommend (developers get trouble with that). 

Current stable:

![image](https://cloud.githubusercontent.com/assets/5808377/15960583/c6b16402-2f00-11e6-9d32-bf6a1b0830a1.png)

The beta:

![image](https://cloud.githubusercontent.com/assets/5808377/15960591/d11b42f0-2f00-11e6-98e2-05ff57881b43.png)

The strong name should be "3.0.0.0"

You can check the strong name with "NuGet Package Explorer"

**Comment by mganss** [comment]
Thanks for noticing. I was overambitious in ripping out stuff from AssemblyInfo.cs :smile:

**Comment by 304NotModified** [comment]
This is indeed fixed in 125. Thanks!
