### ISSUE TITLE
Error using Sanitize after updating AngleSharp to 0.9.7

### ISSUE THREAD

**Issue by xaviergonz** [mganss/HtmlSanitizer#76]
[MissingMethodException: Method not found: 'Void AngleSharp.Configuration..ctor(System.Collections.Generic.IEnumerable`1<System.Object>, System.Globalization.CultureInfo)'.]
   Ganss.XSS.HtmlSanitizer.CreateParser() +0
   Ganss.XSS.HtmlSanitizer.Sanitize(String html, String baseUrl, IMarkupFormatter outputFormatter) +27

I think AngleSharp changed something in their latest release.

**Comment by tiesont** [comment]
@mganss This seems like a repeating issue (#64, #68, to name a few previous issues). Would it be worth setting a max version in the NuGet package?

**Comment by 304NotModified** [comment]
I think that would be wise

**Comment by mganss** [comment]
:ok: I've pinned the version to 0.9.7 in 3.3.127-beta.
