### ISSUE TITLE
Can't install on 4.5.2/4.6

### ISSUE THREAD

**Issue by sickboy** [mganss/HtmlSanitizer#77]
```
Failed to add reference. The package 'HtmlSanitizer' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance
```
Probably: https://github.com/NuGet/Home/issues/3103

**Comment by sickboy** [comment]
There was a similar issue in SharpCompress https://github.com/adamhathcock/sharpcompress/issues/152
and got resolved with https://github.com/adamhathcock/sharpcompress/commit/89fd778bd8092f612797623a359075080b24ed18

**Comment by sickboy** [comment]
@mganss thanks, could we get a nuget build please?

**Comment by mganss** [comment]
The latest NuGet package 3.3.128-beta includes this fix. Forgot to add the release here on GitHub, though :smile_cat:

**Comment by 304NotModified** [comment]
Ps. If you update the version number (always) by hand, you can always push automatically to nuget ;)
