### ISSUE TITLE
The Sanitizer Seems to be Unencoding Some HTML Entities.

### ISSUE THREAD

**Issue by htgold** [mganss/HtmlSanitizer#82]
I was testing the use of the sanitizer on my application, and it's pretty great! The one issue I've run into though, is that it seems to unencode some of the HTML Entities my users frequently use, mainly the `&copy;` entity.

Any time I put `&copy;` through the sanitizer, it comes out as the actual copyright circle-c character (&copy;), and not the entity we're trying to enter. Does it do this for any other entities? I noticed it keeps `&lt;` and `&gt;` as the entities, so I know it can pass them through successfully.

Is there a way to ensure that any HTML Entity passed through the sanitizer will remain the actual entity?

**Comment by nallar** [comment]
I think you can change this behaviour by passing a custom IMarkupFormatter instance to the Sanitize method, and encoding more characters as entities than the default formatter.

> Is there a way to ensure that any HTML Entity passed through the sanitizer will remain the actual entity?

Generally speaking, no. AngleSharp, when parsing HTML, does not differentiate between an `©` character and a `&copy;` entity. The created text node ends up with the same value in it. This means you can either output all as entities, or all as `©`. You can't exactly preserve the input.

**Comment by nallar** [comment]
Really horrible workaround which tries to preserve entities exactly as they come in:

https://gist.github.com/nallar/d91160cd6a30b15ccb5265677f0cf29a

I am not sure if this is safe to do and don't recommend using it unless someone more knowledgeable about this can confirm that it is reasonable.

**Comment by htgold** [comment]
> This means you can either output all as entities, or all as ©. You can't exactly preserve the input.

Do you mean out put all inputted text as entities, or all entities as entities? The "can't preserve the input" is worrying, as that's exactly what I need to be able to do...

**Comment by htgold** [comment]
OK, looking at the HTMLSanitizer code, it seems that it's relying on AngleSharp's toHTML function, and the InnerHTML property of the DOM (starting on line 387: https://github.com/mganss/HtmlSanitizer/blob/master/src/HtmlSanitizer/HtmlSanitizer.cs#L378 ), which would explain why entities are being converted to characters.

How much of the HTMLSanitizer would break if I change it to use the TextContent property instead of InnerHTML, as mentioned in this thread: https://github.com/AngleSharp/AngleSharp/issues/361 ?

My app already handles HTML encoding/decoding where it's necessary, so I don't need anything else to do it for me, I just need the straight text sanitized.

**Comment by nallar** [comment]
I'm not sure I understand what you are trying to do.

HtmlSanitizer is intended for sanitizing HTML content entered by users, for example from a rich text editor like CKEditor. It is not intended for sanitising text content which is not intended to contain HTML. In that case, encoding on output is the correct solution.

If you call .TextContent, you remove all the HTML. Are you trying to convert HTML to plain text? That's not what this library is for...

**Comment by htgold** [comment]
Ah, sorry, .NET developer here, so the .Text property of an element is just whatever text is inputted, HTML tags included, vs. the innerHTML property, which renders the HTML tags. It sounds like it's different in JS?

Our site just has straight TEXTAREAs, so that people can enter HTML Tags and Entities to format their text however they please. So we do need to sanitize the text for any SCRIPT tags, etc., but we also need all of the rest of the text preserved exactly how the users enter it.

**Comment by mganss** [comment]
AngleSharp's parser works exactly like that in a browser. Try this in a browser console:

```JavaScript
document.body.innerHTML = "&copy;"
document.body.innerHTML
→ "©"
document.body.innerHTML = "&lt;"
document.body.innerHTML
→ "&lt;"
```

If you want to keep the original input so that when a user comes back to edit their text they see exactly what they had entered previously, then you might want to keep the original, unsanitized input in addition to the sanitized HTML. Then, render the unsanitized content into the textarea (encoded, of course) and use the sanitized HTML for regular display.

**Comment by mganss** [comment]
We'll keep the current behavior for now.
