### ISSUE TITLE
How to make markdown code blocks not be sanitized.

### ISSUE THREAD

**Issue by liamwang** [mganss/HtmlSanitizer#83]
Is there any way to make markdown code blocks not be sanitized?

Markdown multi-line code blocks like:

\`\`\`html
&lt;html&gt;
   html code here ...
&lt;/html&gt;
\`\`\`

and markdown inline code blocks like:  

  ``  `<html> ... </html>` ``

I want to keep them raw.

**Comment by mganss** [comment]
HtmlSanitizer is only meant to sanitize HTML. Can't you perform the Markdown to HTML transformation first, then sanitize the resulting HTML?

**Comment by liamwang** [comment]
@mganss Year, what I currently do is  like what you said. But for the performance, I want to sanitize html only once before saving them to the DB. If sanitize html at displaying time(such as display a article or a list of article preview), it could call sanitize method tens of thousands of times per day.

Sorry for my poor english. In short, I mean, sanitizing html at saving time has much better performance than at displaying time to some high PV websites.

Is there any workaround for this ? 

Thanks.

**Comment by mganss** [comment]
I don't think sanitizing Markdown with HtmlSanitizer is a good idea. You can try your luck by using the event `RemovingTag` and canceling removal whenever you believe you are in a code block or span. What about regular indented Markdown code blocks, though? What about unescaped < and & which are legal in Markdown?

Can't you do both steps (transform Markdown to HTML, then sanitize) and save the resulting HTML in your DB alongside the original Markdown?

If that's not possible, another option would be to cache the resulting HTML so the transformation takes place only once within a defined timespan (say, one hour). Of course this would mean you might have slightly outdated content displaying on your site.

**Comment by liamwang** [comment]
@mganss Thanks a lot for your precious suggestions. Saving the resulting HTML alongside the original Markdown is the better choice. It even also save the time of Markdown transformation when displaying.
