### ISSUE TITLE
What about thread safety?

### ISSUE THREAD

**Issue by strohhut** [mganss/HtmlSanitizer#86]
Can I reuse a `HtmlSanitizer` instance? Are `Sanitize` and `SanitizeDocument` safe to use in parallel/concurrent scenarios?

**Comment by mganss** [comment]
This has been discussed [here](https://github.com/mganss/HtmlSanitizer/issues/70#issuecomment-218704365) previously. tl;dr No guarantees, but should be ok.

**Comment by 304NotModified** [comment]
Maybe it would be nice to guarantee it?

**Comment by strohhut** [comment]
I'll use it multithreaded then. I'll let you know if I encounter problems.

**Comment by mganss** [comment]
@304NotModified Yes, that would be nice. Do you have experience in proving (or disproving) thread safety? [CHESS](https://www.microsoft.com/en-us/research/project/chess-find-and-reproduce-heisenbugs-in-concurrent-programs/) looks interesting as a tool to help with this.

**Comment by 304NotModified** [comment]
Well, if the class isn't holding data/side effects, it is guaranteed thread safe?

AFAIK the current implementation is thread-safe (please double check), but the difference between guarantee and the current situation is that it should be thread-safe with future changes (so with every feature this is a limitation)

**Comment by mganss** [comment]
I couldn't get CHESS to work 😞 It seems to be no longer maintained and hasn't been updated in a few years. As a poor man's alternative, I've added a [unit test](https://github.com/mganss/HtmlSanitizer/blob/1e2ae13f1a7bb32a70f549dd895fa935d7f252ee/test/HtmlSanitizer.Tests/Tests.cs#L2798-L2840) based on [this idea](http://stackoverflow.com/a/9468889/1970064) ([see also](https://github.com/mgravell/protobuf-net/blob/66bf12175c97db969bb3c06fe22c66e59b8d0b9d/protobuf-net.unittest/Meta/ThreadRace.cs#L39-L104)).

I've also added a paragraph to the README.
