### ISSUE TITLE
.NET 4

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#88]
Why did this nice library dropped the support of .NET 4.0? 

The dependency (AngleSharp) does support .NET 4. 

See http://stackoverflow.com/a/39838977/201303

**Comment by tiesont** [comment]
I assume it's from #72, specifically, https://github.com/mganss/HtmlSanitizer/pull/72#issuecomment-223939723

**Comment by mganss** [comment]
That was easy, just added a net40 section to project.json 😺

**Comment by 304NotModified** [comment]
Yes indeed! Curious how it will work in the build system after project.json
