### ISSUE TITLE
Feature request: To make allowed classes.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [mganss/HtmlSanitizer#90]
I think this will be very usefull to restricked allowed classes for tags.
For example
classes: user1, user2, article_header is allowed
and 
classes: site_header, site_menu_nav is disalowed

**Comment by Dmitrij-Polyanin** [comment]
Mabe to make event on any tag, attribute OnParce with return value true or false when to restrict?
so i can restrict not good classes by myself.

**Comment by mganss** [comment]
Yes, you can use it like this:

```C#
sanitizer.RemovingAttribute += (s, e) =>
{
	if (e.Attribute.Name == "class")
	{
		e.Tag.ClassList.Remove(e.Tag.ClassList.Except(new[] { "good", "oktoo" }, StringComparer.OrdinalIgnoreCase).ToArray());
		e.Cancel = e.Tag.ClassList.Any();
	}
};
```
