### ISSUE TITLE
AllowedAtRules not in IHtmlSanitizer

### ISSUE THREAD

**Issue by ClintRemedios** [mganss/HtmlSanitizer#92]
I noticed the AllowedAtRules is missing from IHtmlSanitizer. I am not sure if this was intentional.

**Comment by 304NotModified** [comment]
Adding it is a breaking change though

**Comment by mganss** [comment]
Thanks for reporting this @ClintRemedios. @304NotModified is right. Options I can think of:

1. Add a new interface `IHtmlSanitizer2` which implements `IHtmlSanitizer` and adds the property. Seems ugly.
2. Add the property to the existing interface and increase the major version. Seems like overkill.
3. Don't add it until other breaking changes have to be introduced.

Thoughts?

**Comment by 304NotModified** [comment]
I would prefer 3

**Comment by mganss** [comment]
Fixed in 4.0.179.
