### ISSUE TITLE
Sanitizer process attributes with no values

### ISSUE THREAD

**Issue by Baidaly** [mganss/HtmlSanitizer#93]
I use special ExtJS HTML templates that need to have attributes without value. E.g.
```
<tpl if="true">
    TEST
<tpl else>
    TEST 2
</tpl>
```

When I run Sanitizer, it converts it to 
```
<tpl if="true">
    TEST
<tpl else="">
    TEST 2
</tpl>
```

Which is not valid for ExtJS. Is there a way to leave attributes as is?

Thank you!

**Comment by tiesont** [comment]
I think that's actually due to AngleSharp (see [AngleSharp #434](https://github.com/AngleSharp/AngleSharp/issues/434)), and it's likely because the latter is correct XML. From reading that issue, it seems like this is intentional, at least for now.

**Comment by mganss** [comment]
Browsers seem to behave the same way:
```JS
var d = document.createElement("div");
d.innerHTML = '<span title>Test</span>';
d.innerHTML ⇒ <span title="">Test</span>
```

The [sanitizer used on GitHub](https://github.com/rgrove/sanitize) does the opposite: `<b title="">Test</b>` becomes `<b title>Test</b>`: <b title="">Test</b>

Besides what @tiesont suggested, you can also provide your own instance of `IMarkupFormatter` to the `OutputFormatter` property by copying the `HtmlFormatter` class (I'll make the methods virtual in the next release) and changing the `Attribute` method. Adding the following line before [this line](https://github.com/mganss/HtmlSanitizer/blob/e0cdf4cac6b003d5788dfe25de1dfa7b6f05cd39/src/HtmlSanitizer/HtmlFormatter.cs#L55) should do the trick:

```C#
if (string.IsNullOrEmpty(value)) return temp.ToString();
```
