### ISSUE TITLE
Unicode behaviour change

### ISSUE THREAD

**Issue by arangas** [mganss/HtmlSanitizer#94]
It looks the behaviour of Unicode has changed in the move from CsQuery to AngleSharp. For example i've noticed that text in a CDATA block of "you shouldn&#8217;t Black Friday shop" is now converted to "you shouldn’t Black Friday shop".

This suggests that #29 would now work as the issue reporter originally intended. For my scenario, this affects a great deal of data that now converts differently.

Is it possible to use an option to change this?

**Comment by mganss** [comment]
Unfortunately no, you'll have to supply a custom `IMarkupFormatter` to achieve this. You could copy the default [HtmlFormatter class](https://github.com/mganss/HtmlSanitizer/blob/master/src/HtmlSanitizer/HtmlFormatter.cs), and copy the [Text method](https://github.com/AngleSharp/AngleSharp/blob/fe3eb2702c2da4cc9cb75c60fdc0fb8a68e13a18/src/AngleSharp/Html/HtmlMarkupFormatter.cs#L40-L57) from the HtmlMarkupFormatter class in AngleSharp and modify it according to your needs.

**Comment by arangas** [comment]
OK, thank you.
