### ISSUE TITLE
Inject attributes to an element while scrubbing

### ISSUE THREAD

**Issue by vivekscripts** [mganss/HtmlSanitizer#96]
is there a way that while scrubbing, the sanitizer can inject any attribute to an element. Such as while scrubbing anchor tags , I want to add target="_blank" to every anchor tag encountered by sanitizer?

**Comment by tiesont** [comment]
There isn't anything built in, but you could probably do that by subscribing to the `PostProcessNode` event, and adding that logic. 

Since HtmlSanitizer uses the AngleSharp library for parsing HTML, you could also just use it directly on the sanitized markup.

**Comment by mganss** [comment]
Here's how you could do this using the `PostProcessNode` event:

```C#
sanitizer.PostProcessNode += (s, e) => (e.Node as IHtmlAnchorElement)?.SetAttribute("target", "_blank");
```

**Comment by richardtallent** [comment]
Perfect! This fixes my use case as well -- securing `<a>` tags with `rel="noreferrer noopener nofollow"`.

**Comment by hammond13** [comment]
Nice example. I would think that adding "nofollow" to anchor tags would be a very common use case. I suggest adding that as an example in the wiki.

**Comment by mganss** [comment]
@hammond13 🆗, I've added example 5 to the wiki.

**Comment by vanillajonathan** [comment]
To anyone who stumbled across this, other rels which may be of interest include `sponsored` and `ucg` (user-generated content) according to Google.
https://developers.google.com/search/docs/advanced/guidelines/qualify-outbound-links

As well as `external`.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel
