### ISSUE TITLE
DoSanitize always calls RemoveComments. Any chance of making this optional?

### ISSUE THREAD

**Issue by ChrisMaunder** [mganss/HtmlSanitizer#98]
Comments, especially things like conditional includes (eg. IE CSS hacks) can be important. At the moment RemoveComments is called no matter what. It would be nicer to have a flag that allows us to decide whether or not we want comments removed.

**Comment by tiesont** [comment]
You _might_ open yourself to an XSS issue, though: https://github.com/mganss/HtmlSanitizer/blob/master/test/HtmlSanitizer.Tests/Tests.cs#L1022 (I haven't tested to see if it does or not).

Have you tried doing this on a local copy and checking whether the tests still pass?

**Comment by ChrisMaunder** [comment]
You're correct. Please consign this request to the bit bucket.

**Comment by mganss** [comment]
I've added the `RemovingComment` event which is raised when a comment node is about to be removed. You can subscribe to this event and set the `Cancel` property to true if you want to keep the comment. This is in 3.4.152-beta.

**Comment by ChrisMaunder** [comment]
Ah - you've given us enough rope. :) Much appreciated.
