### ISSUE TITLE
Issue with version 2 of the library

### ISSUE THREAD

**Issue by aederrar** [mganss/HtmlSanitizer#99]
I'm using version 2 of the library because my actual project is based on the version 4 of the .NET framework and i can't integrate a higher version of the library than version 2 for a reason i ignore actually.

I've noticed that i can inject nested tags and execute the script succesfully as shown in the following code :
```
<script><script>alert('xss')</script></script>
```

After processing by the library, the output is :

```
<script>alert('xss')</script>
```

**Comment by 304NotModified** [comment]
That sounds like a security bug? @mganss

**Comment by aederrar** [comment]
yes, it is !
I'm not able to test a newer version because of my actual configuration (.NET 4)

**Comment by 304NotModified** [comment]
Version 3 also supports NET 4

![image](https://cloud.githubusercontent.com/assets/5808377/21137766/5d1e067c-c12b-11e6-9bff-7bb58180ccba.png)

**Comment by aederrar** [comment]
I tried that version, but i had a problem with AngleSharp dependencies with .NET 4.

**Comment by mganss** [comment]
I can't repro (using 2.0.5735.24296).

```C#
var sanitizer = new HtmlSanitizer();
var h = sanitizer.Sanitize("<script><script>alert('xss')</script></script>");
// h == ""
```

Can you post a minimal example?

Also, I had no problems with v3 in a new .NET 4.0 project.

**Comment by aederrar** [comment]
I've created a new project and effectively i can't reproduce the issue. But i still have the problem with V3 in my project.

**Comment by mganss** [comment]
What is the message you are getting?

**Comment by aederrar** [comment]
- Microsoft.Bcl.Async\1.0.168\lib\net40\Microsoft.Threading.Tasks.dll
- Microsoft.Bcl.Async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.Desktop.dll
- Microsoft.Bcl.Async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll

The version of these libraries isn't compatible with AngleSharp

**Comment by mganss** [comment]
Looks like AngleSharp/AngleSharp#307.
